<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>

    <?= $this->getHelper('Krugozor_Html_Title')->getHtml() ?>

    <?= $this->getCss('/http/css/reset.css', false) ?>
    <?= $this->getCss('/http/css/tags.css', true) ?>
    <?= $this->getCss('/http/css/backend.css', true) ?>
</head>
<body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>

<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<table class="datatable">
    <tr>
        <td>
            <a class="add_element" href="/module/edit-module/"><?= $this->getLang()['content']['add_module'] ?></a>
        </td>
    </tr>
</table>

<table class="datatable">
    <? if ($this->modulesList->getList()->count()): ?>
        <colgroup>
            <col width="5%"/>
            <col width="35%"/>
            <col width="20%"/>
            <col width="20%"/>
            <col width="10%"/>
            <col width="10%"/>
        </colgroup>
        <tr>
            <th colspan="6"><?= $this->getLang()['content']['list_of_modules'] ?></th>
        </tr>
        <tr class="head_params">
            <td>
                <?php
                $linker = $this->getHelper('Krugozor_Helper_SortLink')
                    ->setFieldName('id')
                    ->setAnchor($this->getLang()['content']['id'])
                    ->setUrl($this->getRequest()->getUri()->getEscapeUriValue())
                    ->setIconSrc(Krugozor_Registry::getInstance()->APPLICATION['SYSTEM_ICONS'])
                    ->setCurrentFieldName($this->modulesList->getAlias())
                    ->setCurrentSortOrder($this->modulesList->getOrder());

                echo $linker->getHtml();
                ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('name')
                    ->setAnchor($this->getLang()['content']['module_name'])
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('key')
                    ->setAnchor($this->getLang()['content']['module_key'])
                    ->getHtml(); ?>
            </td>
            <td><?= $this->getLang()['content']['controllers_count'] ?></td>
            <td colspan="2"><?= $this->getLang()['content']['actions'] ?></td>
        </tr>

        <? foreach ($this->modulesList->getList() as $module): ?>
            <tr class="center color_hover">
                <td><?= $module->getId() ?></td>
                <td><?= $this->getHelper('Krugozor_Helper_Format')->run($module->getName()) ?></td>
                <td><?= $module->getKey() ?></td>
                <td>
                    <? if ($module->getControllers()): ?>
                        <?= $module->getControllers()->count() ?>
                        <?= $this->getHelper('Krugozor_Helper_Format')->triumviratForm($module->getControllers()->count(), $this->getLang()['content']['triumvirat_controllers']) ?>
                    <? else: ?>
                        контроллеров нет
                    <? endif; ?>
                </td>
                <td class="td_actions"><a href="/module/edit-module/?id=<?= $module->getId() ?>"><img
                                src="<?= Krugozor_Registry::getInstance()->APPLICATION['SYSTEM_ICONS'] ?>edit.png"
                                alt=""/></a></td>
                <td class="td_actions">
                    <?php
                    $str = Krugozor_Helper_Format::js(
                        $this->getLang()['content']['question_delete_module'],
                        ['module_name' => $module->getName(), 'module_id' => $module->getId()]
                    );
                    ?>
                    <a onclick="return confirm('<?= $str ?>')"
                       href="/module/delete-module/?id=<?= $module->getId() ?>&amp;referer=<?= $this->getRequest()->getRequestUri()->getUrlencodeUriValue(true) ?>">
                        <img src="<?= Krugozor_Registry::getInstance()->APPLICATION['SYSTEM_ICONS'] ?>delete.png"
                             alt=""/>
                    </a>
                </td>
            </tr>
        <? endforeach; ?>

    <? else: ?>
        <tr>
            <th><?= $this->getLang()['content']['list_of_modules'] ?></th>
        </tr>
        <tr class="center">
            <td><?= $this->getLang()['content']['not_found_request_data'] ?></td>
        </tr>
    <? endif; ?>
</table>

<?php
$pagination = $this->modulesList->getPagination();
$pagination
    ->getHelper()
    ->setCssNormalLinkClass('navigation_normal_link')
    ->setRequestUriParameter('field_name', $this->modulesList->getAlias())
    ->setRequestUriParameter('sort_order', $this->modulesList->getOrder())
    ->setPaginationType(\Krugozor\Pagination\Helper::PAGINATION_NORMAL_TYPE);
?>

<? include $this->getRealTemplatePath('Common/BackendNavigation') ?>

<? include $this->getRealTemplatePath('Common/DebugInfo') ?>

</body>
</html>