<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <?= $this->getHelper('Krugozor_Html_Title')->getHtml() ?>
    <?= $this->getCss('/http/css/tags.css', true) ?>
    <?= $this->getCss('/http/css/backend.css', true) ?>
</head>
<body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>
<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<table class="datatable">
    <tr>
        <td>
            <a href="/module/edit-module/?id=<?= $this->controller->getModule()->getId() ?>"><?= $this->getHelper('Krugozor_Helper_Format')->run($this->controller->getModule()->getName()) ?></a>
            &raquo;
            <? if ($this->controller->getId()): ?>
                <?= $this->getLang()['content']['editing_controller'] ?> &laquo;<?= $this->getHelper('Krugozor_Helper_Format')->run($this->controller->getName()) ?>&raquo;
            <? else: ?>
                <?= $this->getLang()['content']['add_controller'] ?>
            <? endif; ?>
        </td>
    </tr>
</table>

<form method="post" action="<?= $this->getRequest()->getRequestUri()->getEscapeUriValue() ?>">
    <table class="datatable edit">
        <colgroup>
            <col/>
            <col/>
        </colgroup>
        <tr>
            <th colspan="2">
                <? if ($this->controller->getId()): ?>
                    <?= $this->getLang()['content']['editing_controller'] ?> &laquo;<?= $this->getHelper('Krugozor_Helper_Format')->run($this->controller->getName()) ?>&raquo;
                <? else: ?>
                    <?= $this->getLang()['content']['add_controller'] ?>
                <? endif; ?>
            </th>
        </tr>
        <tr>
            <td class="compulsory"><?= $this->getLang()['content']['module'] ?>:</td>
            <td><?
                $select = $this->getHelper('Krugozor_Helper_Form')->inputSelect('controller[id_module]', $this->controller->getIdModule());
                $select->addOption($this->getHelper('Krugozor_Helper_Form')->inputOption(0, $this->getLang()['content']['select_value']));
                foreach ($this->modules as $module):
                    $select->addOption($this->getHelper('Krugozor_Helper_Form')->inputOption($module->getId(), $this->getHelper('Krugozor_Helper_Format')->run($module->getName())));
                endforeach;
                echo $select->getHtml();
                ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['id_module']) ?></td>
        </tr>
        <tr>
            <td class="compulsory">Имя контроллера:</td>
            <td>
                <?= $this->getHelper('Krugozor_Helper_Form')->inputText('controller[name]', $this->controller->getName(), array('maxlength' => 255, 'class' => 'textSmall'))->getHtml() ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['name']) ?>
            </td>
        </tr>
        <tr>
            <td class="compulsory">Ключ контроллера:</td>
            <td>
                <?= $this->getHelper('Krugozor_Helper_Form')->inputText('controller[key]', $this->controller->getKey(), array('maxlength' => 30, 'class' => 'textSmall'))->getHtml() ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['key']) ?>
            </td>
        </tr>
        <tr align="center">
            <td colspan="2">
                <?= $this->getHelper('Krugozor_Helper_Form')->inputHidden('controller[id]', $this->controller->getId())->getHtml() ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->inputSubmit('submit', $this->getLang()['content']['save_changes'])->getHtml() ?>
                &nbsp;&nbsp;&nbsp;
                <?= $this->getHelper('Krugozor_Helper_Form')->inputFullCheckbox('return_on_page', 1, 0, $this->return_on_page, array('id' => 'label_return_on_page')) ?>
                &nbsp;<?= $this->getHelper('Krugozor_Helper_Form')->Label($this->getLang()['content']['return_to_this_page'], 'label_return_on_page')->getHtml() ?>
            </td>
        </tr>
    </table>
</form>

<? include $this->getRealTemplatePath('Common/DebugInfo') ?>

</body>
</html>