<!DOCTYPE html>
<html lang="ru">
<head>

    <!-- common meta -->
    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>
    <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getHtml() ?>
    <!-- /common meta -->

    <!-- common css -->
    <?= $this->getCss('local', 'reset.css') ?>
    <?= $this->getCss('local', 'tags.css') ?>
    <?= $this->getCss('local', 'backend.css') ?>
    <!-- /common css -->

</head>
<body>

<? include $this->getRealTemplatePath('Local/BackendNotification') ?>
<? include $this->getRealTemplatePath('Local/BackendMenu') ?>

<?php if ($this->module->getId()): ?>
    <table class="datatable menu">
        <tr>
            <td>
                <a class="add_element" href="/module/edit-controller/?id_module=<?= $this->module->getId() ?>">
                    <?= $this->getLang()['content']['add_controller'] ?>
                </a>
            </td>
        </tr>
    </table>
<?php endif; ?>

<form method="post" action="<?= $this->getRequest()->getRequestUri()->getEscapeUriValue() ?>">
    <table class="datatable edit">
        <colgroup>
            <col/>
            <col/>
        </colgroup>
        <tr>
            <th colspan="2">
                <? if ($this->module->getId()): ?>
                    <?= $this->getLang()['content']['editing_module'] ?> &laquo;<?= $this->getHelper('\Krugozor\Framework\Helper\Format')->run($this->module->getName()) ?>&raquo;
                <? else: ?>
                    <?= $this->getLang()['content']['add_module'] ?>
                <? endif; ?>
            </th>
        </tr>
        <tr>
            <td class="compulsory">Имя модуля:</td>
            <td>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText('module[name]', $this->module->getName(), array('maxlength' => 50, 'class' => 'textSmall'))->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['name']) ?>
            </td>
        </tr>
        <tr>
            <td class="compulsory">Ключ модуля:</td>
            <td>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText('module[key]', $this->module->getKey(), array('maxlength' => 30, 'class' => 'textSmall'))->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['key']) ?>
            </td>
        </tr>
        <tr>
            <td>Контроллеры:</td>
            <td>
                <? if ($this->module->getControllers()->count()): ?>
                    <table>
                        <tr>
                            <th colspan="3">Контоллеры</th>
                        </tr>
                        <? foreach ($this->module->getControllers() as $controller): ?>
                            <tr>
                                <td><?= $this->getHelper('\Krugozor\Framework\Helper\Format')->hsc($controller->getName()) ?></td>
                                <td>
                                    <a href="/module/edit-controller/?id=<?= $controller->getId() ?>&amp;id_module=<?= $controller->getIdModule() ?>">
                                        <img src="/img/local/system/icon/edit.png"
                                             alt=""/>
                                    </a>
                                </td>
                                <td>
                                    <?php
                                    $str = \Krugozor\Framework\Helper\Format::js(
                                        $this->getLang()['content']['question_delete_controller'],
                                        ['controller_name' => $controller->getName(), 'controller_id' => $controller->getId()]
                                    );
                                    ?>
                                    <a onclick="return confirm('<?= $str ?>')"
                                       href="/module/delete-controller/?id=<?= $controller->getId() ?>&amp;id_module=<?= $controller->getIdModule() ?>">
                                        <img src="/img/local/system/icon/delete.png"
                                             alt=""/>
                                    </a>
                                </td>
                            </tr>
                        <? endforeach; ?>
                    </table>
                <? else: ?>
                    <p>Контроллеров нет</p>
                <? endif; ?>
            </td>
        </tr>
        <tr align="center">
            <td colspan="2">
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('module[id]', $this->module->getId())->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputSubmit('submit', $this->getLang()['content']['save_changes'])->getHtml() ?>
                &nbsp;&nbsp;&nbsp;
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox('return_on_page', 1, 0, $this->return_on_page, array('id' => 'label_return_on_page')) ?>
                &nbsp;<?= $this->getHelper('\Krugozor\Framework\Helper\Form')->Label($this->getLang()['content']['return_to_this_page'], 'label_return_on_page')->getHtml() ?>
            </td>
        </tr>
    </table>
</form>

<? include $this->getRealTemplatePath('Local/DebugInfo') ?>

</body>
</html>