<!DOCTYPE html>
<html lang="ru">
<head>

    <!-- common meta -->
    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>
    <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getHtml() ?>
    <!-- /common meta -->

    <!-- common css -->
    <?= $this->getCss('local', 'reset.css') ?>
    <?= $this->getCss('local', 'tags.css') ?>
    <?= $this->getCss('local', 'backend.css') ?>
    <!-- /common css -->

</head>
<body>

<? include $this->getRealTemplatePath('Local/BackendNotification') ?>
<? include $this->getRealTemplatePath('Local/BackendMenu') ?>

<table class="datatable menu">
    <tr>
        <td>
            <a href="/module/edit-module/?id=<?= $this->controller->getModule()->getId() ?>"><?= $this->getHelper('\Krugozor\Framework\Helper\Format')->run($this->controller->getModule()->getName()) ?></a>
            &raquo;
            <? if ($this->controller->getId()): ?>
                <?= $this->getLang()['content']['editing_controller'] ?> &laquo;<?= $this->getHelper('\Krugozor\Framework\Helper\Format')->run($this->controller->getName()) ?>&raquo;
            <? else: ?>
                <?= $this->getLang()['content']['add_controller'] ?>
            <? endif; ?>
        </td>
    </tr>
</table>

<form method="post" action="<?= $this->getRequest()->getRequestUri()->getEscapeUriValue() ?>">
    <table class="datatable edit">
        <colgroup>
            <col/>
            <col/>
        </colgroup>
        <tr>
            <th colspan="2">
                <? if ($this->controller->getId()): ?>
                    <?= $this->getLang()['content']['editing_controller'] ?> &laquo;<?= $this->getHelper('\Krugozor\Framework\Helper\Format')->run($this->controller->getName()) ?>&raquo;
                <? else: ?>
                    <?= $this->getLang()['content']['add_controller'] ?>
                <? endif; ?>
            </th>
        </tr>
        <tr>
            <td class="compulsory"><?= $this->getLang()['content']['module'] ?>:</td>
            <td><?
                $select = $this->getHelper('\Krugozor\Framework\Helper\Form')->inputSelect('controller[id_module]', $this->controller->getIdModule());
                $select->addOption($this->getHelper('\Krugozor\Framework\Helper\Form')->inputOption(0, $this->getLang()['content']['select_value']));
                foreach ($this->modules as $module):
                    $select->addOption($this->getHelper('\Krugozor\Framework\Helper\Form')->inputOption($module->getId(), $this->getHelper('\Krugozor\Framework\Helper\Format')->run($module->getName())));
                endforeach;
                echo $select->getHtml();
                ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['id_module']) ?></td>
        </tr>
        <tr>
            <td class="compulsory">Имя контроллера:</td>
            <td>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText('controller[name]', $this->controller->getName(), array('maxlength' => 255, 'class' => 'textSmall'))->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['name']) ?>
            </td>
        </tr>
        <tr>
            <td class="compulsory">Ключ контроллера:</td>
            <td>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText('controller[key]', $this->controller->getKey(), array('maxlength' => 30, 'class' => 'textSmall'))->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['key']) ?>
            </td>
        </tr>
        <tr align="center">
            <td colspan="2">
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('controller[id]', $this->controller->getId())->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputSubmit('submit', $this->getLang()['content']['save_changes'])->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox('return_on_page', 1, 0, $this->return_on_page, array('id' => 'label_return_on_page')) ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->Label($this->getLang()['content']['return_to_this_page'], 'label_return_on_page')->getHtml() ?>
            </td>
        </tr>
    </table>
</form>

<? include $this->getRealTemplatePath('Local/DebugInfo') ?>

</body>
</html>