<!DOCTYPE html>
<html lang="ru">
<head>

    <!-- common meta -->
    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>
    <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getHtml() ?>
    <!-- /common meta -->

    <!-- common css -->
    <?= $this->getCss('common', 'reset.css') ?>
    <?= $this->getCss('common', 'tags.css') ?>
    <?= $this->getCss('common', 'backend.css') ?>
    <!-- /common css -->
    <?= $this->getCss() ?>

    <?= $this->getJs('common', 'library/krugozor.js') ?>
    <?= $this->getJs('common', 'library/krugozor.forms.js') ?>
    <?= $this->getJs('common', 'library/krugozor.ajax.js') ?>
    <?= $this->getJs('common', 'library/krugozor.ui.popup.ajaxselect.js') ?>
    <?= $this->getJs('common', 'opacity.js') ?>
    <?= $this->getJs('common', 'jquery/jquery-1.11.1.min.js') ?>
    <?= $this->getJs('common', 'library/krugozor.locations.js') ?>
    <?= $this->getJs('common', 'library/krugozor.thumbnail.js') ?>
    <?= $this->getJs() ?>

    <script type="text/javascript">
        var is_guest = 0;
        var max_upload_files = <?=\Krugozor\Framework\Registry::getInstance()->UPLOAD['MAX_FILES_COUNT']?>;
    </script>

</head>
<body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>
<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<form method="post" id="main_form" action="<?= $this->getRequest()->getRequestUri()->getEscapeUriValue() ?>">

    <table class="datatable edit">
        <colgroup>
            <col/>
            <col/>
        </colgroup>
        <tr>
            <th colspan="2">
                <? if ($this->advert->getId()): ?>
                    Редактирование объявления &laquo;<?= $this->getHelper('\Krugozor\Framework\Helper\Format')->hsc($this->advert->getHeader()) ?>&raquo;
                <? else: ?>
                    Добавление объявления
                <? endif; ?>
            </th>
        </tr>
        <tr>
            <td>
                <strong class="compulsory">Объявление активно:</strong></td>
            <td>
                <?
                $select = $this->getHelper('\Krugozor\Framework\Helper\Form')->inputSelect(
                    'advert[active]', $this->advert->getActive(), ['class' => 'width_auto']
                );
                $select->addOption(
                    $this->getHelper('\Krugozor\Framework\Helper\Form')->inputOption(1, $this->lang['content']['yes'])
                );
                $select->addOption(
                    $this->getHelper('\Krugozor\Framework\Helper\Form')->inputOption(0, $this->lang['content']['no'])
                );
                echo $select->getHtml();
                ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['active']) ?>
            </td>
        </tr>
        <tr>
            <td>Объявление оплачено:</td>
            <td>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox(
                    'advert[payment]', 1, 0, $this->advert->getPayment()
                ) ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['payment']) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Категория:</strong></td>
            <td><?
                $select = $this->getHelper('\Krugozor\Framework\Helper\Form')->inputSelect(
                    'advert[category]', $this->advert->getCategory(), array('id' => 'advert_category')
                );
                $select->addOption(
                    $this->getHelper('\Krugozor\Framework\Helper\Form')->inputOption('0', 'Выберите')
                );
                $categories = $this->getHelper('\Krugozor\Framework\Module\Category\Helper\OptionsListWithOptgroup', $this->tree)->getOptions();
                foreach ($categories as $option):
                    $select->addOption($option);
                endforeach;
                echo $select->getHtml();
                ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['category']) ?></td>
        </tr>
        <tr>
            <td>ID пользователя:</td>
            <td>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                    'advert[id_user]', $this->advert->getIdUser(), array('maxlength' => 11)
                )->getHtml() ?>
                <?php if ($this->advert->getIdUser() != \Krugozor\Framework\Module\User\Model\User::GUEST_USER_ID): ?>
                    [<a href="/user/backend-edit/?id=<?= $this->advert->getIdUser() ?>">профиль</a>]
                <? endif; ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['id_user']) ?>
            </td>
        </tr>
        <tr>
            <td>Дата создания:</td>
            <td><p><?= $this->advert->getCreateDate()->formatAsMysqlDatetime() ?></p></td>
        </tr>
        <tr>
            <td>Дата редактирования:</td>
            <td>
                <?php if ($this->advert->getEditDate()): ?>
                    <p><?= $this->advert->getEditDate()->formatAsMysqlDatetime() ?></p>
                    <p class="after_field_text">будет изменена после редактирования</p>
                <?php else: ?>
                    <p>Не редактировалось</p>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td>VIP:</td>
            <td><?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                    'advert[vip_date]',
                    $this->advert->getVipDate() ? $this->advert->getVipDate()->formatAsMysqlDatetime() : null,
                    array('id' => 'vip_date', 'maxlength' => 19)
                )->getHtml() ?>
                <div class="after_field_text">
                    <p>Назначить:
                        <?php
                        $date = new \Krugozor\Framework\Type\Datetime();
                        $date->add(new \DateInterval('P7D')); ?>
                        <a href="#" class="set_vip_date" data-time="<?= $date->formatAsMysqlDatetime(); ?>">+7 дней</a>,
                        <?php
                        $date = new \Krugozor\Framework\Type\Datetime();
                        $date->add(new \DateInterval('P14D')); ?>
                        <a href="#" class="set_vip_date" data-time="<?= $date->formatAsMysqlDatetime(); ?>">+14 дней</a>,
                        <?php
                        $date = new \Krugozor\Framework\Type\Datetime();
                        $date->add(new \DateInterval('P1M')); ?>
                        <a href="#" class="set_vip_date" data-time="<?= $date->formatAsMysqlDatetime(); ?>">+месяц</a>,
                        <?php
                        $date = new \Krugozor\Framework\Type\Datetime();
                        $date->add(new \DateInterval('P1Y')); ?>
                        <a href="#" class="set_vip_date" data-time="<?= $date->formatAsMysqlDatetime(); ?>">+год</a>
                    </p>
                </div>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['vip_date']) ?></td>
        </tr>
        <tr>
            <td>Спецпредложение:</td>
            <td><?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                    'advert[special_date]',
                    $this->advert->getSpecialDate() ? $this->advert->getSpecialDate()->formatAsMysqlDatetime() : null,
                    array('id' => 'special_date', 'maxlength' => 19)
                )->getHtml() ?>
                <div class="after_field_text">
                    <p>Назначить:
                        <?php
                        $date = new \Krugozor\Framework\Type\Datetime();
                        $date->add(new \DateInterval('P7D')); ?>
                        <a href="#" class="set_special_date" data-time="<?= $date->formatAsMysqlDatetime(); ?>">+7
                            дней</a>,
                        <?php
                        $date = new \Krugozor\Framework\Type\Datetime();
                        $date->add(new \DateInterval('P14D')); ?>
                        <a href="#" class="set_special_date" data-time="<?= $date->formatAsMysqlDatetime(); ?>">+14
                            дней</a>,
                        <?php
                        $date = new \Krugozor\Framework\Type\Datetime();
                        $date->add(new \DateInterval('P1M')); ?>
                        <a href="#" class="set_special_date"
                           data-time="<?= $date->formatAsMysqlDatetime(); ?>">+месяц</a>,
                        <?php
                        $date = new \Krugozor\Framework\Type\Datetime();
                        $date->add(new \DateInterval('P1Y')); ?>
                        <a href="#" class="set_special_date" data-time="<?= $date->formatAsMysqlDatetime(); ?>">+год</a>
                    </p>
                </div>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['special_date']) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Тип пользователя:</strong></td>
            <td><?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('advert[user_type]', '')->getHtml() ?>
                <?php foreach (\Krugozor\Framework\Module\User\Type\Type::getTypes() as $type => $value): ?>
                    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputRadio(
                        'advert[user_type]',
                        $type,
                        $this->advert->getUserType()->getValue(),
                        array('id' => 'user_type_' . $type)
                    )->getHtml() ?>
                    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->Label(
                        $value, 'user_type_' . $type
                    )->getHtml() ?>
                <?php endforeach; ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['user_type']) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Тип объявления:</strong></td>
            <td><?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('advert[type]', '')->getHtml() ?>
                <? foreach (\Krugozor\Framework\Module\Advert\Type\AdvertType::getTypes() as $type => $value): ?>
                    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputRadio(
                        'advert[type]',
                        $type,
                        $this->advert->getType()->getValue(),
                        array('id' => 'advert_type_' . $type))->getHtml()
                    ?>
                    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->Label(
                        $value, 'advert_type_' . $type
                    )->getHtml() ?>
                <? endforeach; ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['type']) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Заголовок объявления:</strong></td>
            <td><?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                    'advert[header]', $this->advert->getHeader(), array('maxlength' => 255)
                )->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['header']) ?></td>
        </tr>
        <tr>
            <td><strong class="compulsory">Текст объявления:</strong></td>
            <td><?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputTextarea(
                    'advert[text]', $this->advert->getText(), array('id' => 'advert_text', 'class' => 'large')
                )->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['text']) ?>
            </td>
        </tr>
        <tr>
            <td>Цена:</td>
            <td><?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                    'advert[price]', $this->advert->getPrice(), array('id' => 'advert_price', 'maxlength' => 11, 'onkeyup' => 'Krugozor.Forms.filterDigit(this)')
                )->getHtml() ?>
                <?
                $select = $this->getHelper('\Krugozor\Framework\Helper\Form')->inputSelect(
                    'advert[price_type]', $this->advert->getPriceType()->getValue(), ['class' => 'width_auto']
                );
                foreach (\Krugozor\Framework\Module\Advert\Type\PriceType::getTypes() as $price_code => $price_data):
                    $select->addOption(
                        $this->getHelper('\Krugozor\Framework\Helper\Form')->inputOption($price_code, $price_data[0])
                    );
                endforeach;
                echo $select->getHtml();
                ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['price']) ?>
                <p>
                    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox(
                        'advert[free]', 1, 0, $this->advert->getFree(), array('id' => 'label_free', 'onclick' => "if (this.checked) document.getElementById('advert_price').value = '';")
                    ) ?>
                    <label for="label_free">даром</label>
                    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['free']) ?>
                </p>
            </td>
        </tr>

        <?php if ($this->err['contact_info']): ?>
            <tr>
                <td colspan="2">
                    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['contact_info']) ?>
                </td>
            </tr>
        <?php endif; ?>

        <tr>
            <td>Контактное лицо:</td>
            <td><?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                    'advert[user_name]', $this->advert->getUserName(), array('maxlength' => 255, 'id' => 'advert_user_name', 'class' => 'textSmall')
                )->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['user_name']) ?>

                <?php if ($this->user->getFullName() && !$this->user->isGuest()): ?>
                    <p>
                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox(
                            'advert[main_user_name]', 1, 0, $this->advert->getMainUserName(), array('id' => 'label_main_user_name', 'onchange' => "set_contact_input_state('advert_user_name')")
                        ) ?>
                        <label for="label_main_user_name">Контактное лицо &mdash;
                            <b><?= $this->user->getFullName() ?></b></label>
                        <?php if (!$this->advert->getUserName() || $this->advert->getMainUserName()): ?>
                            <script type="text/javascript">
                                // <![CDATA[
                                set_contact_input_state('advert_user_name');
                                // ]]>
                            </script>
                        <?php endif; ?>
                    </p>
                <?php else: ?>
                    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('advert[main_user_name]', 0)->getHtml() ?>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td>Телефон:</td>
            <td><?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                    'advert[phone]', $this->advert->getPhone(), array('maxlength' => 255, 'class' => 'medium', 'id' => 'advert_phone')
                )->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['phone']) ?>

                <?php if ($this->user->getPhone()): ?>
                    <p>
                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox(
                            'advert[main_phone]', 1, 0, $this->advert->getMainPhone(), array('id' => 'label_main_phone', 'onchange' => "set_contact_input_state('advert_phone')")
                        ) ?>
                        <label for="label_main_phone">Использовать для связи мой основной телефон
                            <b><?= $this->user->getPhone() ?></b></label>
                        <?php if (!$this->advert->getPhone() || $this->advert->getMainPhone()): ?>
                            <script type="text/javascript">
                                // <![CDATA[
                                set_contact_input_state('advert_phone');
                                // ]]>
                            </script>
                        <?php endif; ?>
                    </p>
                <?php else: ?>
                    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('advert[main_phone]', 0)->getHtml() ?>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td>Email-адрес:</td>
            <td><?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                    'advert[email]', $this->advert->getEmail()->getValue(), array('maxlength' => 255, 'class' => 'medium', 'id' => 'advert_email')
                )->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['email']) ?>

                <?php if ($this->user->getEmail()->getValue() && $this->user->getEmail()->getValue()): ?>
                    <p>
                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox(
                            'advert[main_email]', 1, 0, $this->advert->getMainEmail(), array('id' => 'label_main_email', 'onchange' => "set_contact_input_state('advert_email')")
                        ) ?>
                        <label for="label_main_email">Использовать для связи мой основной email-адрес
                            <b><?= $this->user->getEmail()->getValue() ?></b></label>
                        <?php if (!$this->advert->getEmail()->getValue() || $this->advert->getMainEmail()): ?>
                            <script type="text/javascript">
                                // <![CDATA[
                                set_contact_input_state('advert_email');
                                // ]]>
                            </script>
                        <?php endif; ?>
                    </p>
                <?php else: ?>
                    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('advert[main_email]', 0)->getHtml() ?>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td>URL:</td>
            <td><?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                    'advert[url]', $this->advert->getUrl()->getValue(), array('maxlength' => 255, 'class' => 'medium', 'id' => 'advert_url')
                )->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['url']) ?>

                <?php if ($this->user->getUrl()->getValue()): ?>
                    <p>
                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox(
                            'advert[main_url]', 1, 0, $this->advert->getMainUrl(), array('id' => 'label_main_url', 'onchange' => "set_contact_input_state('advert_url')")
                        ) ?>
                        <label for="label_main_url">Использовать для связи мой основной URL-адрес
                            <b><?= $this->user->getUrl()->getNiceAnchor() ?></b></label>
                        <?php if (!$this->advert->getUrl()->getValue() || $this->advert->getMainUrl()): ?>
                            <script type="text/javascript">
                                // <![CDATA[
                                set_contact_input_state('advert_url');
                                // ]]>
                            </script>
                        <?php endif; ?>
                    </p>
                <?php else: ?>
                    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('advert[main_url]', 0)->getHtml() ?>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td>ICQ:</td>
            <td><?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                    'advert[icq]', $this->advert->getIcq(), array('maxlength' => 10, 'class' => 'medium', 'onkeyup' => "Krugozor.Forms.filterDigit(this)", 'id' => 'advert_icq')
                )->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['icq']) ?>

                <?php if ($this->user->getIcq()): ?>
                    <p>
                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox(
                            'advert[main_icq]', 1, 0, $this->advert->getMainIcq(), array('id' => 'label_main_icq', 'onchange' => "set_contact_input_state('advert_icq')")
                        ) ?>
                        <label for="label_main_icq">Использовать для связи мой основной ICQ
                            <b><?= $this->user->getIcq() ?></b></label>
                        <?php if (!$this->advert->getIcq() || $this->advert->getMainIcq()): ?>
                            <script type="text/javascript">
                                // <![CDATA[
                                set_contact_input_state('advert_icq');
                                // ]]>
                            </script>
                        <?php endif; ?>
                    </p>
                <?php else: ?>
                    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('advert[main_icq]', 0)->getHtml() ?>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td>Skype:</td>
            <td><?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                    'advert[skype]', $this->advert->getSkype(), array('maxlength' => 32, 'class' => 'medium', 'id' => 'advert_skype')
                )->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['skype']) ?>

                <?php if ($this->user->getSkype()): ?>
                    <p>
                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox(
                            'advert[main_skype]', 1, 0, $this->advert->getMainSkype(), array('id' => 'label_main_skype', 'onchange' => "set_contact_input_state('advert_skype')")
                        ) ?>
                        <label for="label_main_skype">Использовать для связи мой основной Skype
                            <b><?= $this->user->getSkype() ?></b></label>
                        <?php if (!$this->advert->getSkype() || $this->advert->getMainSkype()): ?>
                            <script type="text/javascript">
                                // <![CDATA[
                                set_contact_input_state('advert_skype');
                                // ]]>
                            </script>
                        <?php endif; ?>
                    </p>
                <?php else: ?>
                    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('advert[main_skype]', 0)->getHtml() ?>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td>
                <small>Местоположение, в котором будет проходить сделка, осмотр объектов сделки или в котором находится
                    объект сделки:
                </small>
            </td>
            <td>
                <p>
                    <span id="js_country_select_wrap"></span>
                    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['place_country']) ?>
                </p>
                <p>
                    <span id="js_region_select_wrap"></span>
                    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['place_region']) ?>
                </p>
                <p>
                    <span id="js_city_select_wrap"></span>
                    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['place_city']) ?>
                </p>
            </td>
        </tr>
        <tr class="center">
            <td colspan="2">
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('advert[was_moderated]', 1)->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('advert[id]', $this->advert->getId())->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputSubmit('submit', $this->lang['content']['save_changes'])->getHtml() ?>
                &nbsp;&nbsp;&nbsp;
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox('return_on_page', 1, 0, $this->return_on_page, array('id' => 'label_return_on_page')) ?>
                &nbsp;<?= $this->getHelper('\Krugozor\Framework\Helper\Form')->Label($this->lang['content']['return_to_this_page'], 'label_return_on_page')->getHtml() ?>
            </td>
        </tr>
    </table>

    <?php if ($this->advert->getThumbnailsList()->count()): ?>
        <?php foreach ($this->advert->getThumbnailsList() as $thumbnail): ?>
            <input type="hidden" name="thumbnail[]" value="<?= $thumbnail->getId() ?>"/>
        <?php endforeach; ?>
    <?php endif; ?>
</form>

<table class="datatable edit">
    <colgroup>
        <col/>
        <col/>
    </colgroup>
    <tr>
        <th colspan="2">Изображения</th>
    </tr>
    <tr>
        <td></td>
        <td>
            <div id="uploaded_images"<?php if ($this->advert->getThumbnailsList()->count()): ?> class="display"<? endif; ?>>
                <?php if ($this->advert->getThumbnailsList()->count()): ?>
                    <?php foreach ($this->advert->getThumbnailsList() as $thumbnail): ?>
                        <span><img src="/i/150x100<?= $thumbnail->getFullHttpPath() ?>" alt=""/><a
                                    data-advert="<?= $thumbnail->getIdAdvert() ?>" data-id="<?= $thumbnail->getId() ?>"
                                    title="Удалить изображение" href="#"></a></span>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <iframe width="0" height="0" name="iframe"></iframe>

            <form id="file_upload_form" method="post" enctype="multipart/form-data" target="iframe">
                <div id="thumbnail_errors"></div>
                <input type="hidden" name="MAX_FILE_SIZE" value="<?= $this->max_file_size ?>"/>
                Загрузить изображение: <input type="file" name="file" id="file" checked="0"/>
                <? if ($this->advert->getThumbnailsList()->count() == \Krugozor\Framework\Registry::getInstance()->UPLOAD['MAX_FILES_COUNT']): ?>
                    <div class="fieldErrorMessage">Загружено максимально-допустимое количество изображений.</div>
                <? endif; ?>
            </form>
        </td>
    </tr>
</table>

<script type="text/javascript">
    Krugozor.Location.addCheckedUserLocation(1, '<?=$this->advert->getPlaceCountry()?>');
    Krugozor.Location.addCheckedUserLocation(2, '<?=$this->advert->getPlaceRegion()?>');
    Krugozor.Location.addCheckedUserLocation(3, '<?=$this->advert->getPlaceCity()?>');

    var select_country_attributes = {
        name: 'advert[place_country]',
        value: '<?=$this->advert->place_country?>'
    };
    var selectCountryObj = Krugozor.Location.createLocation(select_country_attributes, 'Выберите страну проживания');
    document.getElementById('js_country_select_wrap').appendChild(selectCountryObj.SelectElement);

    var select_region_attributes = {
        name: 'advert[place_region]',
        value: '<?=$this->advert->place_region?>'
    };
    var selectRegionObj = Krugozor.Location.createLocation(select_region_attributes, 'Выберите регион проживания');
    document.getElementById('js_region_select_wrap').appendChild(selectRegionObj.SelectElement);

    var select_city_attributes = {
        name: 'advert[place_city]',
        value: '<?=$this->advert->place_city?>'
    };
    var selectCityObj = Krugozor.Location.createLocation(select_city_attributes, 'Выберите город проживания');
    document.getElementById('js_city_select_wrap').appendChild(selectCityObj.SelectElement);

    selectCountryObj.create(1, 0);
    selectRegionObj.create(2, <?=(int)$this->advert->getPlaceCountry()?>);
    selectCityObj.create(3, <?=(int)$this->advert->getPlaceRegion()?>);
</script>

<? include $this->getRealTemplatePath('Common/DebugInfo') ?>

</body>
</html>