<!DOCTYPE html>
<html lang="ru">
<head>

    <!-- common meta -->
    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>
    <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getHtml() ?>
    <!-- /common meta -->

    <!-- common css -->
    <?= $this->getCss('common', 'reset.css') ?>
    <?= $this->getCss('common', 'tags.css') ?>
    <?= $this->getCss('common', 'backend.css') ?>
    <!-- /common css -->
    <?= $this->getCss() ?>

    <?= $this->getJs('common', 'library/krugozor.js') ?>
    <?= $this->getJs('common', 'library/krugozor.forms.js') ?>
    <?= $this->getJs('common', 'library/krugozor.ajax.js') ?>
    <?= $this->getJs('common', 'library/krugozor.ui.popup.ajaxselect.js') ?>
    <?= $this->getJs() ?>

</head>
<body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>
<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<table class="datatable">
    <tr>
        <td>
            <a class="add_element" href="/advert/backend-edit/"><?= $this->getLang()['content']['adding_advert'] ?></a>
            <span class="vhr">|</span>
            <span>
            <?php
            $select = $this->getHelper('\Krugozor\Framework\Helper\Form')->inputSelect('advert[category]', $this->id_category, array('id' => 'advert_category'));
            $select->addOption($this->getHelper('\Krugozor\Framework\Helper\Form')->inputOption('0', 'Выберите'));
            $categories = $this->getHelper('\Krugozor\Framework\Module\Category\Helper\OptionsListWithOptgroup', $this->tree)->getOptions();
            foreach ($categories as $option):
                $select->addOption($option);
            endforeach;
            echo $select->getHtml();
            ?>
            </span>
        </td>
    </tr>
</table>

<?php
/* @var $pagination Krugozor\Pagination\Manager */
$pagination = $this->advertsList->getPagination();
$pagination->getHelper()
    ->setCssNormalLinkClass('navigation_normal_link')
    ->setCssActiveLinkClass('navigation_active_link')
    ->setRequestUriParameter('field_name', $this->advertsList->getAlias())
    ->setRequestUriParameter('sort_order', $this->advertsList->getOrder())
    ->setRequestUriParameter('id_category', $this->id_category)
    ->setRequestUriParameter('id_user', $this->id_user)
    ->setPaginationType(\Krugozor\Pagination\Helper::PAGINATION_NORMAL_TYPE);
?>

<?php include $this->getRealTemplatePath('Common/BackendNavigation') ?>

<form action="/advert/backend-set-actions/" method="post">

    <table class="datatable">
        <? if ($this->advertsList->getList()->count()): ?>
            <colgroup>
                <col><col><col><col><col>
                <col><col><col><col><col>
                <col><col><col>
            </colgroup>
            <tr>
                <th colspan="13"><?= $this->getLang()['content']['list_of_adverts'] ?></th>
            </tr>
            <tr class="head_params">
                <td>
                    <?php
                    /* @var $linker \Krugozor\Framework\Helper\SortLink */
                    $linker = $this->getHelper('\Krugozor\Framework\Helper\SortLink')
                        ->setFieldName('id')
                        ->setAnchor($this->getLang()['content']['id'])
                        ->setUrl($this->getRequest()->getCanonicalRequestUri()->getEscapeUriValue())
                        ->setIconSrc(\Krugozor\Framework\Registry::getInstance()->APPLICATION['SYSTEM_ICONS'])
                        ->setCurrentFieldName($this->advertsList->getAlias())
                        ->setCurrentSortOrder($this->advertsList->getOrder())
                        ->setQueryStringFromArray(array(
                            'sep' => $this->advertsList->getPagination()->getCurrentSeparator(),
                            'page' => $this->advertsList->getPagination()->getCurrentPage(),
                            'id_category' => $this->id_category,
                            'id_user' => $this->id_user
                        ));

                    echo $linker->getHtml();
                    ?>
                </td>
                <td>
                    <?php
                    echo $linker->setFieldName('advert_create_date')
                        ->setAnchor($this->getLang()['content']['advert_create_date'])
                        ->getHtml(); ?>
                </td>
                <td>
                    <?php
                    echo $linker->setFieldName('vip')
                        ->setAnchor($this->getLang()['content']['advert_vip_date'])
                        ->getHtml(); ?>
                </td>
                <td>
                    <?php
                    echo $linker->setFieldName('special')
                        ->setAnchor($this->getLang()['content']['advert_special_date'])
                        ->getHtml(); ?>
                </td>
                <td>
                    <?php
                    echo $linker->setFieldName('was_moderated')
                        ->setAnchor($this->getLang()['content']['advert_was_moderated'])
                        ->getHtml(); ?>
                </td>
                <td>
                    <?php
                    echo $linker->setFieldName('image')
                        ->setAnchor($this->getLang()['content']['advert_image'])
                        ->getHtml(); ?>
                </td>
                <td>
                    <a id="js_advert_delete_all" href="#"><?= $this->getLang()['content']['select_all'] ?></a>
                </td>
                <td>
                    <?php
                    echo $linker->setFieldName('header')
                        ->setAnchor($this->getLang()['content']['advert_header'])
                        ->getHtml(); ?>
                </td>
                <td>
                    <?php
                    echo $linker->setFieldName('category')
                        ->setAnchor($this->getLang()['content']['advert_category'])
                        ->getHtml(); ?>
                </td>
                <td>
                    <?php
                    echo $linker->setFieldName('user_name')
                        ->setAnchor($this->getLang()['content']['advert_user_name'])
                        ->getHtml(); ?>
                </td>
                <td colspan="3"><?= $this->getLang()['content']['actions'] ?></td>
            </tr>

            <? foreach ($this->advertsList->getList() as $row): ?>
                <tr class="color_hover">
                    <td class="center">
                        <?= $row['advert']->getId() ?>
                    </td>
                    <td class="center small_text">
                        <?= $row['advert']->getCreateDate()->formatDateForPeople() ?>
                    </td>
                    <td class="center<? if (!$row['advert']->getVipDate()): ?> lighttext<?php endif; ?>">
                        <? if ($row['advert']->getVipDate()): ?>
                            <img src="/img/common/system/icon/star.png"
                                 alt=""/>
                            <small><?= $row['advert']->getVipDate()->format('Y-m-d H:i') ?></small>
                        <?php else: ?>
                            <?= $this->getLang()['content']['no'] ?>
                        <? endif; ?>
                    </td>
                    <td class="center<? if (!$row['advert']->getSpecialDate()): ?> lighttext<?php endif; ?>">
                        <? if ($row['advert']->getSpecialDate()): ?>
                            <img src="/img/common/system/icon/star.png"
                                 alt=""/>
                            <small><?= $row['advert']->getSpecialDate()->format('Y-m-d H:i') ?></small>
                        <? else: ?>
                            <?= $this->getLang()['content']['no'] ?>
                        <? endif; ?>
                    </td>
                    <td class="center redtext<? if ($row['advert']->getWasModerated()): ?> lighttext<?php endif; ?>">
                        <? if ($row['advert']->getWasModerated()): ?>
                            <?= $this->getLang()['content']['yes'] ?>
                        <? else: ?>
                            <span><?= $this->getLang()['content']['no'] ?></span>
                        <? endif; ?>
                    </td>
                    <td class="center<?php if (!$row['advert']->getThumbnailCount()): ?> lighttext<?php endif; ?>">
                        <?php if ($row['advert']->getThumbnailCount() > 1): ?>
                            <img src="/img/common/system/icon/photos.png"
                                 alt="" title="Изображений: <?= $row['advert']->getThumbnailCount() ?>"/>
                        <?php elseif ($row['advert']->getThumbnailCount() == 1): ?>
                            <img src="/img/common/system/icon/photo.png"
                                 alt="" title="Изображений: <?= $row['advert']->getThumbnailCount() ?>"/>
                        <?php else: ?>
                            <?= $this->getLang()['content']['no'] ?>
                        <?php endif; ?>
                    </td>
                    <td class="center">
                        <label for="label_delete_<?= $row['advert']->getId() ?>">
                            <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputCheckbox('ids[]', $row['advert']->getId(), 0)->getHtml() ?>
                        </label>
                    </td>
                    <td>
                        <p>
                            <b>
                                <a class="external" target="_blank" href="/advert/<?= $row['advert']->getId() ?>.xhtml">
                                    <?= \Krugozor\Framework\Helper\Format::hsc($row['advert']->getHeader()) ?>
                                </a>
                            </b>
                        </p>
                    </td>
                    <td>
                        <a href="?id_category=<?= $row['category']->getId() ?>"><?= $row['category']->getName() ?></a>
                    </td>
                    <td>
                        <? if ($row['user']->isGuest()): ?>
                            <a href="?id_user=<?= $row['user']->getId() ?>"><?= \Krugozor\Framework\Helper\Format::hsc($row['user']->getFullNameOrLogin()) ?></a>
                        <? else: ?>
                            <? if ($row['advert']->getMainUserName()): ?>
                                <a href="?id_user=<?= $row['user']->getId() ?>"><?= \Krugozor\Framework\Helper\Format::hsc($row['user']->getFullName() ?: $row['advert']->getUserName()) ?></a>
                            <? else: ?>
                                <?php if ($row['advert']->getUserName()): ?>
                                    <a href="?id_user=<?= $row['user']->getId() ?>"><?= \Krugozor\Framework\Helper\Format::hsc($row['user']->getFullNameOrLogin()) ?></a>
                                    от имени
                                    <strong><?= \Krugozor\Framework\Helper\Format::hsc($row['advert']->getUserName()) ?></strong>
                                <?php else: ?>
                                    <a href="?id_user=<?= $row['user']->getId() ?>"><?= \Krugozor\Framework\Helper\Format::hsc($row['user']->getFullNameOrLogin()) ?></a>
                                <?php endif; ?>
                            <? endif; ?>
                            <span class="lighttext">[<a class="lighttext"
                                                        href="/user/backend-edit/?id=<?= $row['user']->getId() ?>">профиль</a>]</span>
                        <? endif; ?>
                    </td>
                    <td class="td_actions">
                        <?php if ($row['user']->isGuest() && $row['advert']->getEmail()->getValue()): ?>
                            <a class="invite-anonymous-user"
                               href="/user/backend-invite-anonymous-user/advert/<?= $row['advert']->getId() ?>"><img
                                        src="/img/common/system/icon/email.png" alt=""/></a>
                            <?php if ($row['invite_anonymous_user']->getSendDate()): ?>
                                <small><?= $row['invite_anonymous_user']->getSendDate()->format('d.m.Y') ?></small>
                            <?php endif; ?>
                        <?php endif; ?>
                    </td>
                    <td class="td_actions">
                        <a href="/advert/backend-edit/?id=<?= $row['advert']->getId() ?>&amp;referer=<?= $this->getRequest()->getRequestUri()->getUrlencodeUriValue(true) ?>">
                            <img src="/img/common/system/icon/edit.png" alt=""/>
                        </a>
                    </td>
                    <td class="td_actions">
                        <?php if (!$row['advert']->getVipDate() && !$row['advert']->getSpecialDate()): ?>
                            <?php
                            $str = \Krugozor\Framework\Helper\Format::js(
                                $this->getLang()['content']['question_delete_advert'],
                                ['advert_header' => $row['advert']->getHeader()]
                            );
                            ?>
                            <a onclick='return confirm("<?= $str ?>")'
                               href="/advert/backend-delete/?id=<?= $row['advert']->getId() ?>&amp;referer=<?= $this->getRequest()->getRequestUri()->getUrlencodeUriValue(true) ?>">
                                <img src="/img/common/system/icon/delete.png" alt=""/>
                            </a>
                        <?php else: ?>
                            <img title="Нельзя удалять объявления со статусом VIP или находящиеся в Спецпредложении"
                                 src="/img/common/system/icon/delete_empty.png" alt=""/>
                        <? endif; ?>
                    </td>
                </tr>
            <? endforeach; ?>

        <? else: ?>

            <tr>
                <th>
                    <h4><?= $this->getLang()['content']['list_of_adverts'] ?></h4>
                </th>
            </tr>
            <tr class="center">
                <td>
                    <?= $this->getLang()['content']['empty_list_of_adverts'] ?>
                </td>
            </tr>

        <? endif; ?>
    </table>

    <? if ($this->advertsList->getList()->count()): ?>
        <table class="datatable searchtable">
            <colgroup>
                <col>
            </colgroup>
            <tr>
                <th colspan="3">C отмеченными:</th>
            </tr>
            <tr class="center">
                <td>
                    <input type="hidden" value="<?= $this->getRequest()->getRequestUri()->getEscapeUriValue(true) ?>"
                           name="referer"/>

                    <input name="delete" type="submit" value="<?= $this->getLang()['content']['advert_delete'] ?>"/>
                    <input name="payment" type="submit" value="<?= $this->getLang()['content']['advert_payment'] ?>"/>

                    <span><?= $select->setAttribute('name', 'category')->setAttribute('id', 'category')->removeAttribute('onchange')->getHtml() ?></span>
                    <input name="change_advert_category" type="submit"
                           value="<?= $this->getLang()['content']['change_advert_category'] ?>"/>
                </td>
            </tr>
        </table>
    <?php endif; ?>

</form>

<? include $this->getRealTemplatePath('Common/BackendNavigation') ?>
<? include $this->getRealTemplatePath('Common/DebugInfo') ?>

</body>
</html>