<!DOCTYPE html>
<html lang="ru">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />

<?=$this->getHelper('Krugozor_Html_Title')->getHtml()?>

<?=$this->getCss('/http/css/reset.css', false)?>
<?=$this->getCss('/http/css/tags.css', true)?>
<?=$this->getCss('/http/css/backend.css', true)?>

<?=$this->getJs('/http/js/library/index.js', true);?>
<?=$this->getJs('/http/js/library/krugozor.ui.popup.ajaxselect.js', true);?>
<?=$this->getPathToJsModule(true)?>

</head><body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>
<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<table class="datatable">
	<tr>
		<td><a class="add_element" href="/advert/backend-edit/"><?=$this->lang['content']['adding_advert']?></a> <span class="vhr">|</span>
		<span>
        <?php
            $select = $this->getHelper('Krugozor_Helper_Form')->inputSelect('advert[category]', $this->id_category, array('id' => 'advert_category'));
            $select->addOption( $this->getHelper('Krugozor_Helper_Form')->inputOption('0', 'Выберите') );
            $categories = $this->getHelper('Krugozor_Module_Category_Helper_Select', $this->tree)->getHtml();
            foreach ($categories as $option):
                $select->addOption($option);
            endforeach;
            echo $select->getHtml();
        ?>
        </span>
		</td>
	</tr>
</table>

<?php
$pagination = $this->advertsList->getPagination();
$pagination->getHelper()
           ->setCssNormalLinkClass('navigation_normal_link')
           ->setCssActiveLinkClass('navigation_active_link')
           ->setRequestUriParameter('field_name', $this->advertsList->getAlias())
           ->setRequestUriParameter('sort_order', $this->advertsList->getOrder())
           ->setRequestUriParameter('id_category', $this->id_category)
           ->setRequestUriParameter('id_user', $this->id_user)
           ->setPaginationType(\Krugozor\Pagination\Helper::PAGINATION_NORMAL_TYPE);
?>

<?php include $this->getRealTemplatePath('Common/BackendNavigation')?>

<form action="/advert/backend-set-actions/" method="post">

<table class="datatable">
    <? if ($this->advertsList->getList()->count()): ?>
        <colgroup>
            <col width="5%" />
            <col width="5%" />
            <col width="5%" />
            <col width="5%" />
            <col width="5%" />
            <col width="5%" />
            <col width="5%" />
            <col width="30%" />
            <col width="10%" />
            <col width="10%" />
            <col width="5%" />
            <col width="5%" />
            <col width="5%" />
        </colgroup>
        <tr>
            <th colspan="13"><?=$this->lang['content']['list_of_adverts']?></th>
        </tr>
        <tr class="head_params">
            <td>
            <?php
                $linker = $this->getHelper('Krugozor_Helper_SortLink')
                               ->setFieldName('id')
                               ->setAnchor($this->lang['content']['id'])
                               ->setUrl('/advert/backend-main/')
                               ->setIconSrc('/http/image/system/icon/')
                               ->setCurrentFieldName($this->advertsList->getAlias())
                               ->setCurrentSortOrder($this->advertsList->getOrder())
                               ->setQueryStringFromArray(array(
                                   'sep' => $this->advertsList->getPagination()->getCurrentSeparator(),
                                   'page' => $this->advertsList->getPagination()->getCurrentPage(),
                                   'id_category' => $this->id_category,
                                   'id_user' => $this->id_user
                                   ));

                echo $linker->getHtml();
            ?>
            </td>
            <td>
            <?php
                echo $linker->setFieldName('advert_create_date')
                            ->setAnchor($this->lang['content']['advert_create_date'])
                            ->getHtml(); ?>
            </td>
            <td>
            <?php
                echo $linker->setFieldName('vip')
                            ->setAnchor($this->lang['content']['advert_vip_date'])
                            ->getHtml(); ?>
            </td>
            <td>
            <?php
                echo $linker->setFieldName('special')
                            ->setAnchor($this->lang['content']['advert_special_date'])
                            ->getHtml(); ?>
            </td>
            <td>
            <?php
                echo $linker->setFieldName('was_moderated')
                            ->setAnchor($this->lang['content']['advert_was_moderated'])
                            ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('image')
                    ->setAnchor($this->lang['content']['advert_image'])
                    ->getHtml(); ?>
            </td>
            <td>
                <a id="js_advert_delete_all" href="#"><?=$this->lang['content']['select_all']?></a>
            </td>
            <td>
            <?php
                echo $linker->setFieldName('header')
                            ->setAnchor($this->lang['content']['advert_header'])
                            ->getHtml(); ?>
            </td>
            <td>
            <?php
                echo $linker->setFieldName('category')
                            ->setAnchor($this->lang['content']['advert_category'])
                            ->getHtml(); ?>
            </td>
            <td>
            <?php
                echo $linker->setFieldName('user_name')
                            ->setAnchor($this->lang['content']['advert_user_name'])
                            ->getHtml(); ?>
            </td>
            <td colspan="3"><?=$this->lang['content']['actions']?></td>
        </tr>

        <? foreach($this->advertsList->getList() as $row): ?>
            <tr class="color_hover">
                <td class="center">
                    <?=$row['advert']->getId()?>
                </td>
                <td class="center small_text">
                    <?=$row['advert']->getCreateDate()->formatDateForPeople()?>
                </td>
                <td class="center<? if(!$row['advert']->getVipDate()): ?> lighttext<?php endif; ?>">
                    <? if($row['advert']->getVipDate()): ?>
                        <img src="<?=Krugozor_Registry::getInstance()->APPLICATION['SYSTEM_ICONS']?>star.png" alt="" />
                        <small><?=$row['advert']->getVipDate()->format('Y-m-d H:i')?></small>
                    <?php else: ?>
                        <?=$this->lang['content']['no']?>
                    <? endif; ?>
                </td>
                <td class="center<? if(!$row['advert']->getSpecialDate()): ?> lighttext<?php endif; ?>">
                    <? if($row['advert']->getSpecialDate()): ?>
                        <img src="<?=Krugozor_Registry::getInstance()->APPLICATION['SYSTEM_ICONS']?>star.png" alt="" />
                        <small><?=$row['advert']->getSpecialDate()->format('Y-m-d H:i')?></small>
                    <? else: ?>
                        <?=$this->lang['content']['no']?>
                    <? endif; ?>
                </td>
                <td class="center redtext<? if($row['advert']->getWasModerated()): ?> lighttext<?php endif; ?>">
                    <? if($row['advert']->getWasModerated()):?>
                        <?=$this->lang['content']['yes']?>
                    <? else: ?>
                        <span><?=$this->lang['content']['no']?></span>
                    <? endif; ?>
                </td>
                <td class="center<?php if(!$row['advert']->getThumbnailCount()): ?> lighttext<?php endif; ?>">
                    <?php if ($row['advert']->getThumbnailCount() > 1): ?>
                        <img src="<?=Krugozor_Registry::getInstance()->APPLICATION['SYSTEM_ICONS']?>photos.png" alt="" title="Изображений: <?=$row['advert']->getThumbnailCount()?>" />
                    <?php elseif ($row['advert']->getThumbnailCount() == 1): ?>
                        <img src="<?=Krugozor_Registry::getInstance()->APPLICATION['SYSTEM_ICONS']?>photo.png" alt="" title="Изображений: <?=$row['advert']->getThumbnailCount()?>" />
                    <?php else: ?>
                        <?=$this->lang['content']['no']?>
                    <?php endif; ?>
                </td>
                <td class="center">
                    <label for="label_delete_<?=$row['advert']->getId()?>">
                        <?=$this->getHelper('Krugozor_Helper_Form')->inputCheckbox('ids[]', $row['advert']->getId(), 0)->getHtml()?>
                    </label>
                </td>
                <td>
                    <p><b><a class="external" target="_blank" href="/advert/<?=$row['advert']->getId()?>.xhtml"><?=Krugozor_Helper_Format::hsc($row['advert']->getHeader())?></a></b></p></td>
                <td>
                    <a href="?id_category=<?=$row['category']->getId()?>"><?=$row['category']->getName()?></a>
                </td>
                <td>
                <? if ($row['user']->isGuest()): ?>
                    <a href="?id_user=<?=$row['user']->getId()?>"><?=Krugozor_Helper_Format::hsc($row['user']->getFullNameOrLogin())?></a>
                <? else: ?>
                    <? if ($row['advert']->getMainUserName()): ?>
                        <a href="?id_user=<?=$row['user']->getId()?>"><?=Krugozor_Helper_Format::hsc($row['user']->getFullName() ?: $row['advert']->getUserName())?></a>
                    <? else: ?>
                        <?php if ($row['advert']->getUserName()): ?>
                            <a href="?id_user=<?=$row['user']->getId()?>"><?=Krugozor_Helper_Format::hsc($row['user']->getFullNameOrLogin())?></a>
                            от имени <strong><?=Krugozor_Helper_Format::hsc($row['advert']->getUserName())?></strong>
                        <?php else: ?>
                            <a href="?id_user=<?=$row['user']->getId()?>"><?=Krugozor_Helper_Format::hsc($row['user']->getFullNameOrLogin())?></a>
                        <?php endif;?>
                    <? endif; ?>
                    <span class="lighttext">[<a class="lighttext" href="/user/backend-edit/?id=<?=$row['user']->getId()?>">профиль</a>]</span>
                <? endif; ?>
                </td>
                <td class="td_actions">
                    <?php if ($row['user']->isGuest() && $row['advert']->getEmail()->getValue()): ?>
                        <a class="invite-anonymous-user" href="/user/backend-invite-anonymous-user/advert/<?=$row['advert']->getId()?>"><img src="/http/image/system/icon/email.png" alt="" /></a>
                        <?php if ($row['invite_anonymous_user']->getSendDate()): ?>
                            <small><?=$row['invite_anonymous_user']->getSendDate()->format('d.m.Y')?></small>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
                <td class="td_actions">
                    <a href="/advert/backend-edit/?id=<?=$row['advert']->getId()?>&amp;referer=<?=$this->getRequest()->getRequestUri()->getUrlencodeUriValue(true)?>">
                        <img src="/http/image/system/icon/edit.png" alt="" />
                    </a>
                </td>
                <td class="td_actions">
                    <?php if (!$row['advert']->getVipDate() && !$row['advert']->getSpecialDate()): ?>
                        <?php
                        $str = Krugozor_Helper_Format::js(
                            $this->getLang()['content']['question_delete_advert'],
                            ['advert_header' => $row['advert']->getHeader()]
                        );
                        ?>
                        <a onclick='return confirm("<?=$str?>")' href="/advert/backend-delete/?id=<?=$row['advert']->getId()?>&amp;referer=<?=$this->getRequest()->getRequestUri()->getUrlencodeUriValue(true)?>">
                            <img src="/http/image/system/icon/delete.png" alt="" />
                        </a>
                    <?php else: ?>
                        <img title="Нельзя удалять объявления со статусом VIP или находящиеся в Спецпредложении" src="/http/image/system/icon/delete_empty.png" alt="" />
                    <? endif; ?>
                </td>
            </tr>
        <? endforeach; ?>

    <? else: ?>
        <tr>
          <th>
              <h4><?=$this->lang['content']['list_of_adverts']?></h4>
          </th>
        </tr>
        <tr class="center">
            <td>
                <?=$this->lang['content']['empty_list_of_adverts']?>
            </td>
        </tr>
    <? endif; ?>
</table>

<? if ($this->advertsList->getList()->count()): ?>
    <table class="datatable">
        <colgroup>
            <col width="3%" />
            <col width="93%" />
            <col width="3%" />
        </colgroup>
        <tr>
            <th colspan="3">C отмеченными:</th>
        </tr>
        <tr class="center">
            <td></td>
            <td>
                <input type="hidden" value="<?=$this->getRequest()->getRequestUri()->getEscapeUriValue(true)?>" name="referer" />

                <input name="delete" type="submit" value="<?=$this->lang['content']['advert_delete']?>" />
                <input name="payment" type="submit" value="<?=$this->lang['content']['advert_payment']?>" />

                <span><?=$select->setAttribute('name', 'category')->setAttribute('id', 'category')->removeAttribute('onchange')->getHtml()?></span>
                <input name="change_advert_category" type="submit" value="<?=$this->lang['content']['change_advert_category']?>" />
            </td>
            <td></td>
        </tr>
    </table>
<?php endif; ?>

</form>

<? include $this->getRealTemplatePath('Common/BackendNavigation') ?>
<? include $this->getRealTemplatePath('Common/DebugInfo') ?>

</body></html>