<!DOCTYPE html>
<html lang="ru">
<head>

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" sizes="16x16" href="/favicon.ico" />

<?=$this->getHelper('Krugozor_Html_Title')->getHtml()?>

<link rel="stylesheet" href="/http/css/main.css" type="text/css" />
<?=$this->getCss('/http/css/modules/advert/_adverts-list.css', true)?>
<?=$this->getPathToCssModule(true)?>

<?=$this->getJs('/http/js/tooltip.js', false)?>
<?=$this->getJs('/http/js/jquery-1.11.1.min.js', false)?>
<?=$this->getJs('/http/js/jquery.lazyload.min.js', false)?>
<?=$this->getJs('/http/js/library/index.js', false)?>
<?=$this->getJs('/http/js/modules/advert/_adverts-list.js', true)?>

</head><body>

<? include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div class="content">

    <h2>
        <a class="space_nowrap" href="/my/"><?=$this->getHelper('Krugozor_Html_Title')->getByIndex(1)?></a> /
        <span class="space_nowrap"><?=$this->getHelper('Krugozor_Html_Title')->getByIndex(2)?></span>
    </h2>

    <? include $this->getRealTemplatePath('Common/FrontendNotification')?>

    <? include_once($this->getRealTemplatePath('Advert/AdvertsList')); ?>

    <?php
    $this->pagination
         ->getHelper()
         ->setCssNormalLinkClass('navigation_normal_link')
         ->setCssActiveLinkClass('navigation_open_link');
    include $this->getRealTemplatePath('Common/FrontendNavigation');
    ?>
</div>

<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>

</body></html>