<!DOCTYPE html>
<html lang="ru">
<head>

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="keywords" content="бесплатные объявления<?=$this->bread_crumbs_postfix_text?>, <?=($this->category->getKeywords() ? strip_tags($this->category->getKeywords()) : $this->lang['meta']['keywords'])?>" />
<meta name="description" content="<?=($this->category->getDescription() ? strip_tags($this->category->getDescription() . $this->bread_crumbs_postfix_text) : $this->getHelper('Krugozor_Html_Title')->getLastElement())?>" />
<meta property="og:title" content="<?=$this->getHelper('Krugozor_Html_Title')->getLastElement()?>"/>
<meta property="og:description" content="<?=($this->category->getDescription() ? strip_tags($this->category->getDescription() . $this->bread_crumbs_postfix_text) : $this->getHelper('Krugozor_Html_Title')->getLastElement())?>" />
<meta property="og:image" content="/http/image/desing/snippet.jpg" />
<link rel="shortcut icon" sizes="16x16" href="/favicon.ico" />
<link rel="index" href="<?=$this->territories->getLast()->getUrl()?>/categories/" />
<link rel="start" href="<?=$this->territories->getLast()->getUrl()?>/categories<?=$this->category->getParentCategoryUrl()?>" />

<?=$this->getHelper('Krugozor_Html_Title')->getHtml()?>

<?=$this->getCss('/http/css/main.css', false)?>
<?=$this->getCss('/http/css/modules/advert/_adverts-list.css', true)?>
<?=$this->getPathToCssModule(true)?>

<?=$this->getJs('/http/js/tooltip.js', false)?>
<?=$this->getJs('/http/js/jquery-1.11.1.min.js', false)?>
<?=$this->getJs('/http/js/jquery.lazyload.min.js', false)?>
<?=$this->getJs('/http/js/library/index.js', false)?>
<?=$this->getJs('/http/js/modules/advert/_adverts-list.js', true)?>
<?=$this->getJs('/http/js/library/krugozor.locations.js', true);?>
<?=$this->getPathToJsModule()?>

</head><body>

<? include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div id="<?=$this->getPageId()?>" class="content">

<div class="hgroup">
	<h2>
        <?php $i=1; foreach ($this->territories as $territory): ?>
            <?php if ($i != 1): ?>/<?php endif; ?>
            <a href="<?=$territory->getUrl()?>/categories/"><? if($i==1): ?>Объявления <? endif; ?><?=$territory->getNameRu()?></a>
        <?php $i++; endforeach; ?>

	    <?=$this->getHelper('Krugozor_Module_Category_Helper_BreadCrumbs', $this->path_to_category, $this->territories->getLast()->getUrl() . '/categories', '/')->getHtml()?>
	</h2>
	<?php if ($this->category->getDescription()) :?>
	<p><?=$this->category->getDescription() . $this->bread_crumbs_postfix_text?>.</p>
	<?php endif;?>
</div>

<? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

<?php if ($this->subcategories && $this->subcategories->count()): ?>
    <div class="subcategories categories_list
        <? if ($this->subcategories->count() < 20): ?> precent_50<? endif; ?>
        <? if ($this->subcategories->count() < 5): ?> precent_100<? endif; ?>
    ">
        <?=$this->getHelper(
            'Krugozor_Module_Category_Helper_Subcategories',
            $this->subcategories,
            $this->territories->getLast()->getUrl() . '/categories'
        )->getHtml()?>
    </div>
<?php endif; ?>

<div class="subcategories filter">
	<div class="two_column">
		<div class="left_column">
			<div class="left_column_content">
                <div class="bheader">Фильтр по объявлениям:</div>
				<form method="get" action="<?=$this->getRequest()->getUri()->getEscapeUriValue()?>">
				<div class="field_row">
					<label>Вас интересует:</label>
		 			<div class="group nice_radiobuttons">
		 				<?php foreach (Krugozor_Module_Advert_Type_AdvertType::getTypes() as $type => $value): ?>
			                <?=$this->getHelper('Krugozor_Helper_Form')->inputRadio('type', $type, $this->getRequest()->getGet('type', 'string'), array('id'=>'label_' . $type))->getHtml()?>
			                <?=$this->getHelper('Krugozor_Helper_Form')->Label($value, 'label_' . $type)->getHtml()?>
			            <?php endforeach; ?>
			            <?=$this->getHelper('Krugozor_Helper_Form')->inputRadio('type', '', $this->getRequest()->getGet('type', 'string'), array('id'=>'label_all'))->getHtml()?>
			            <?=$this->getHelper('Krugozor_Helper_Form')->Label('всё', 'label_all')->getHtml()?>
					</div>
				</div>
				<div class="field_row">
					<label for="search">Поиск по слову:</label>
		 			<div class="group">
		 				<?=$this->getHelper('Krugozor_Helper_Form')->inputText('search', $this->getRequest()->getGet('search', 'string'), array('maxlength'=>100, 'id' => 'search'))->getHtml()?>
						<div class="animate_field_description">
						    <div class="animate_field_content">
    							<div class="description_before_fields">
    							Укажите ключевые слова для поиска по базе объявлений.
    							Не стоит писать обобщённые слова, такие как &laquo;телевизор&raquo; или &laquo;машина&raquo;, указывайте наиболее чёткие поисковые запросы.
    							Например: &laquo;Телевизор LG 32LB561V&raquo;, &laquo;Lada Priora&raquo;.
    							Ключевые слова должны состоять не менее чем из 4 символов.
    							</div>
							</div>
							<div class="triangle-right-border"></div>
                            <div class="triangle-right"></div>
						</div>
		 				<input<?php if ($this->category->getParentCategoryUrl() == '/'): ?> class="with_margin"<?php endif; ?> type="submit" name="submit" value="Поиск" />
					</div>
				</div>
				</form>

			</div>
		</div>
        <?php if ($this->category->getParentCategoryUrl() != '/'): ?>
            <div id="js_add_advert" class="right_column">
                <div data-country="<?php if ($this->territories->country): ?><?=$this->territories->country->getId()?><?php endif; ?>" data-region="<? if ($this->territories->region): ?><?=$this->territories->region->getId()?><?php endif; ?>" data-city="<? if ($this->territories->city): ?><?=$this->territories->city->getId()?><?php endif; ?>" data-category="<?=$this->category->getId()?>" class="right_column_content">
                    <?php if ($this->category->getParentCategoryUrl() != '/'): ?>
                        <a href="/my/adverts/edit/">Подать объявление бесплатно и без регистрации</a> в раздел &laquo;<span class="with_decoration"><span class="other_color"><?=$this->category->getName()?></span></span>&raquo;<?=$this->bread_crumbs_postfix_text?> </a>
                    <?php endif; ?>
                </div>
            </div>
        <? endif; ?>
	</div>
</div>

<?php if($this->adverts && $this->adverts->count()): ?>
    <? include_once($this->getRealTemplatePath('Advert/AdvertsList')); ?>
<?php else: ?>
	<div class="subcategories">
		<p>Объявлений не найдено. Вы можете <a href="/my/adverts/edit/">подать объявление бесплатно и без регистрации</a> или посмотреть другие <a href="/">объявления</a>.</p>
	</div>
<?php endif; ?>

<?php
$this->pagination
     ->getHelper()
     ->setCssNormalLinkClass('navigation_normal_link')
     ->setCssActiveLinkClass('navigation_open_link')
     ->setRequestUriParameter('type', $this->type)
     ->setViewLastPageLabel(false)
     ->setRequestUriParameter('search', $this->getRequest()->getRequest('search', 'string'))
     ->setRequestUriParameter('type', $this->getRequest()->getRequest('type', 'string'));
include $this->getRealTemplatePath('Common/FrontendNavigation');
?>

<?php if ($this->category->isTopCategory() && $this->categories && $this->categories->count()): ?>
    <div class="subcategories categories_list bottom">
        <div class="bheader">Другие категории сайта объявлений<?=$this->bread_crumbs_postfix_text?>:</div>
        <?=$this->getHelper(
            'Krugozor_Module_Category_Helper_Subcategories',
            $this->categories,
            $this->territories->getLast()->getUrl() . '/categories'
        )
            ->setCurrentCategory($this->category)
            ->getHtml()
        ?>
    </div>
<?php endif; ?>

<?php if ($this->pagination->getCurrentPage() == 1): ?>
    <div class="category_text">
        <p><?=Krugozor_Static_String::createMessageFromParams($this->category->getText(), ['city' => $this->territories->getLast()->getNameRu2()])?></p>
    </div>
<?php endif; ?>

</div>
<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>

</body></html>