<!DOCTYPE html>
<html lang="ru">
<head>

    <!-- common meta -->
    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="<?= $this->getLang()['meta']['keywords'] ?>"/>
    <meta name="description" content="<?= $this->getLang()['meta']['description'] ?>"/>
    <meta property="og:title" content="<?= $this->getHelper('\Krugozor\Framework\Html\Title')->getTitle() ?>"/>
    <meta property="og:description" content="<?= $this->getLang()['meta']['description'] ?>"/>
    <meta property="og:image" content="/http/image/desing/snippet.jpg"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>
    <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getHtml() ?>
    <!-- common meta -->

    <!-- common css -->
    <?= $this->getCss('common', 'reset.css', false) ?>
    <?= $this->getCss('common', 'tags.css', false) ?>
    <?= $this->getCss('common', 'classes.css', false) ?>
    <?= $this->getCss('common', 'structure.css', false) ?>
    <!-- /common css -->

    <?= $this->getCss('advert', '_adverts-list.css', true) ?>
    <?= $this->getCss() ?>

</head>
<body>

<? include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div class="content">

    <h2>
        <a class="space_nowrap" href="/authorization/frontend-login/"><?= $this->getHelper('\Krugozor\Framework\Html\Title')->getByIndex(1) ?></a>
        /
        <span class="space_nowrap"><?= $this->getHelper('\Krugozor\Framework\Html\Title')->getByIndex(2) ?></span>
    </h2>

    <? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

    <?php if ($this->adverts && $this->adverts->count()): ?>
        <? include_once($this->getRealTemplatePath('Advert/AdvertsList')); ?>
    <?php else: ?>
        <p>Вы еще не создали ни одного объявления.</p>
        <p>Для создания объявления <a href="/advert/frontend-edit-advert/">пройдите по этой ссылке</a>.</p>
    <?php endif; ?>

    <?php
    $this->pagination
        ->getHelper()
        ->setCssNormalLinkClass('navigation_normal_link')
        ->setCssActiveLinkClass('navigation_open_link');
    ?>

    <? include $this->getRealTemplatePath('Common/FrontendNavigation'); ?>
</div>

<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>

</body>
</html>