<!DOCTYPE html>
<html lang="ru">
<head>

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="keywords" content="<?=$this->lang['meta']['keywords']?>" />
<meta name="description" content="<?=$this->lang['meta']['description']?>" />
<link rel="shortcut icon" sizes="16x16" href="/favicon.ico" />

<?=$this->getHelper('Krugozor_Html_Title')->getHtml()?>

<?=$this->getCss('/http/css/main.css', false)?>
<?=$this->getPathToCssModule(true)?>

<?=$this->getJs('/http/js/library/index.js', false)?>
<?=$this->getJs('/http/js/tooltip.js', false)?>
<?=$this->getJs('/http/js/jquery-1.11.1.min.js', false)?>

</head><body>

<? include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div id="<?=$this->getPageId()?>" class="content">

	<? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

	<h2><?=$this->getHelper('Krugozor_Html_Title')->getByIndex(1)?></h2>

	<div class="two_column">
		<div class="left_column">
			<div class="left_column_content">
				<h3>Подать объявление без регистрации на сайте</h3>
				<ul class="plus">
		        	<li>Быстрая подача объявления &mdash; нет процедуры регистрации.</li>
	            </ul>
	            <ul class="minus">
	                <li>Нет возможности редактировать добавленные объявления, удалять или поднимать их в результатах поиска.</li>
	                <li>При подаче каждого нового объявления приходится заново заполнять свои контактные данные.</li>
	                <li>Анонимные объявления из базы удаляются через несколько месяцев.</li>
	            </ul>
	            <ul class="information">
	                <li>Данный способ подачи объявления идеально подходит для тех, кто хочет быстро разместить объявление и &laquo;забыть&raquo; о нем.</li>
	        	</ul>
        	</div>
        </div>
		<div class="right_column">
			<div class="right_column_content">
				<h3>Подать объявление с регистрацией на сайте</h3>
				<ul class="plus">
	                <li>Возможность управлять созданными ранее объявлениями, масса функций.</li>
	                <li>Единый аккаунт пользователя для всех объявлений &mdash; нет необходимости каждый раз заполнять свои контактные данные.</li>
                    <li>Объявления зарегестрированных пользователей не удаляются из базы.</li>
	            </ul>
	            <ul class="information">
	                <li>Данный способ подачи объявления подходит для тех, кто хочет разместить объявление на сайте и иметь  возможность редактировать объявление и контактную информацию, изменять цену, поднимать объявление в результатах поиска, создавать большое количество новых объявлений и, в случае надобности, удалять объявление с сайта.</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="two_column add">
		<div class="left_column">
			<div class="left_column_content">
				<a href="/my/adverts/edit/">Подать объявление без регистрации</a>
			</div>
		</div>
		<div class="right_column">
			<div class="right_column_content">
				<a href="/registration.xhtml">Зарегистрироваться и подать объявление</a>
			</div>
		</div>
	</div>
</div>

<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>

</body></html>