<!DOCTYPE html>
<html lang="ru">
<head>

    <!-- common meta -->
    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="<?= $this->getLang()['meta']['keywords'] ?>"/>
    <meta name="description" content="<?= $this->getLang()['meta']['description'] ?>"/>
    <meta property="og:description" content="<?= $this->getLang()['meta']['description'] ?>"/>
    <meta property="og:image" content="/http/image/desing/snippet.jpg"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>
    <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getHtml() ?>
    <!-- common meta -->

    <!-- common css -->
    <?= $this->getCss('common', 'reset.css', false) ?>
    <?= $this->getCss('common', 'tags.css', false) ?>
    <?= $this->getCss('common', 'classes.css', false) ?>
    <?= $this->getCss('common', 'structure.css', false) ?>
    <!-- /common css -->
    <?= $this->getCss() ?>

    <script type="text/javascript">
        var is_guest = <?=(int)$this->current_user->isGuest()?>;
        var advert_category = <?=(int)$this->advert->getCategory()?>;
        var max_upload_files = <?=\Krugozor\Framework\Registry::getInstance()->UPLOAD['MAX_FILES_COUNT']?>
    </script>

    <?= $this->getJs('common', 'tooltip.js') ?>
    <?= $this->getJs('common', 'jquery/jquery-1.11.1.min.js') ?>

    <?= $this->getJs('common', 'library/krugozor.js') ?>
    <?= $this->getJs('common', 'library/krugozor.forms.js') ?>
    <?= $this->getJs('common', 'library/krugozor.ajax.js') ?>
    <?= $this->getJs('common', 'opacity.js'); ?>
    <?= $this->getJs('common', 'library/krugozor.locations.js', true); ?>
    <?= $this->getJs('common', 'library/krugozor.ui.popup.ajaxselect.js', true); ?>
    <?= $this->getJs('common', 'library/krugozor.thumbnail.js', true); ?>
    <?= $this->getJs() ?>

    <?php
    if ($this->current_user->isGuest()):
        $this->getHelper('\Krugozor\Framework\Html\Title')->add('Подать объявление ' . $this->header_postfix_text . ' бесплатно и без регистрации');
    elseif ($this->from_registration):
        $this->getHelper('\Krugozor\Framework\Html\Title')->add('Шаг 2. Размещение объявления');
    else:
        $this->getHelper('\Krugozor\Framework\Html\Title')->add('Мой личный кабинет');

        if ($this->advert->getId()):
            $this->getHelper('\Krugozor\Framework\Html\Title')->add('Мои объявления');
            $this->getHelper('\Krugozor\Framework\Html\Title')->add('Редактирование объявления № ' . $this->advert->getId());
        else:
            $this->getHelper('\Krugozor\Framework\Html\Title')->add('Создать новое объявление');
        endif;
    endif;
    ?>

    <meta property="og:title" content="<?= $this->getHelper('\Krugozor\Framework\Html\Title')->getTitle() ?>"/>
    <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getHtml() ?>
</head>
<body>

<?php include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div id="<?= $this->getPageId() ?>" class="content">

    <h2>
        <? if ($this->current_user->isGuest()): ?>
            <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getByIndex(1) ?>
        <? elseif ($this->from_registration): ?>
            <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getByIndex(1) ?>
        <? else: ?>
            <a class="space_nowrap"
               href="/authorization/frontend-login/"><?= $this->getHelper('\Krugozor\Framework\Html\Title')->getByIndex(1) ?></a> /
            <?php if ($this->advert->getId()): ?>
                <a class="space_nowrap"
                   href="/advert/frontend-user-adverts-list/"><?= $this->getHelper('\Krugozor\Framework\Html\Title')->getByIndex(2) ?></a> / <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getByIndex(3) ?>
            <?php else: ?>
                <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getByIndex(2) ?>
            <?php endif; ?>
        <? endif; ?>
    </h2>

    <? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

    <div id="aside_blocks">
        <aside class="rules">
            <div class="rules_text">
                <p>Запрещается публикация объявлений следующего характера и содержания:</p>
                <ul>
                    <li>Объявлений о предоставлении оккультных услуг, магии, нетрадиционной медицины.</li>
                    <li>Реклама любых благотворительных фондов, НКО, общин.</li>
                    <li>Реклама финансовых пирамид, средств быстрого заработка.</li>
                    <li>Объявлений о предоставлении любых займов и кредитов.</li>
                    <li>Реклама любых веб-сайтов.</li>
                    <li>Объявлений о купле-продаже товаров и о предоставлении услуг, расцениваемых действующим законодательством РФ как нелегальные (наркотики, оружие, подделка документов и пр.).</li>
                    <li>Объявлений о купле-продаже алькогольной продукции.</li>
                    <li>Предложения покупки готовых дипломных и курсовых работ.</li>
                </ul>
                <p>Подобные вышеописанным характеримстикам объявления УДАЛЯЮТСЯ в течении часа.</p>
            </div>
        </aside>

        <aside class="rules">
            <div class="rules_text">
                <p>Крайне не приветствуется:</p>
                <ul>
                    <li>Клонирование объявлений &mdash; не нужно по сто раз размещать одно и тоже объявление.
                    На нашем сайте для <a href="/user/frontend-registration/">зарегистрированных</a> пользователей есть специальная <strong>бесплатная функция</strong> &laquo;<strong>Поднять объявление</strong>&raquo;.<br /><br />
                    Клонированные объявления, вышедшие по своему количеству за пределы разумного, будут удалены.</li>
                    <li>Размещение объявлений, в которых описывается более одного объекта сделки. Такие объявления малоэффективны как для продавцов, так и для покупателей.</li>
                    <li>Размещение объявлений в неподходящих разделах каталога.</li>
                </ul>
            </div>
        </aside>

        <?php if ($this->current_user->isGuest()): ?>
        <aside class="rules">
            <div class="rules_text">
                <p>Полезный совет:</p>
                <p><strong>Если вы, будучи не зарегистрированным пользователем, подали на сайт объявления, то при <a href="/user/frontend-registration/">регистрации в системе</a> ваши объявления автоматически привяжутся к вашему аккаунту на сайте!</strong> Это произойдет при условии, если в момент регистрации вы будете использовать тот же обозреватель, через который изначально подавали объявления на наш сайт.</p>
                <p>Регистрация позволит вам управлять вашими объявлениями:</p>
                <ul>
                    <li>Редактировать объявления</li>
                    <li>Бесплатно поднимать их в результатах поиска</li>
                    <li>Приостанавливать или возобновлять показ объявлений</li>
                    <li>Удалять объявления</li>
               </ul>
               <p>Сайт бесплатных объявлений <?=\Krugozor\Framework\Registry::getInstance()->HOSTINFO['HOST_SIMPLE']?> &mdash; это удобно!</p>
            </div>
        </aside>
        <?php endif; ?>

        <aside class="rules">
            <div class="rules_text">
                <script type="text/javascript" src="//vk.com/js/api/openapi.js?121"></script>
                <!-- VK Widget -->
                <div id="vk_groups"></div>
                <script type="text/javascript">
                VK.Widgets.Group("vk_groups", {mode: 2, width: "236", height: "300"}, 120400274);
                </script>
            </div>
        </aside>
    </div>

    <div id="forms_wrap">
        <form method="post" action="<?=$this->getRequest()->getRequestUri()->getEscapeUriValue()?>" id="main_form">
            <fieldset>
                <legend>Основные параметры объявления</legend>

                <div class="table">
                    <div class="field_row_fake">
                        <div></div>
                        <div class="group">
                            <div class="description_before_fields">
                                Если вы не знаете, как правильно подать объявление,<br />ознакомьтесь с
                                <a target="_blank" href="/help/poleznye_sovety">советами по размещению объявлений</a> на нашем сайте.
                            </div>
                            <div class="description_before_fields attention">
                                Все объявления проверяются на соответствие правилам размещения объявлений.
                            </div>
                        </div>
                    </div>
                    <div class="field_row">
                        <label for="advert_category">
                            <span class="red_star">*</span> Категория:
                        </label>
                        <div class="group">
                            <div class="fields_wrap">
                                <?php
                                $select = $this->getHelper('\Krugozor\Framework\Helper\Form')->inputSelect(
                                    'advert[category]',
                                    $this->advert->getCategory(),
                                    ['id' => 'advert_category']
                                );
                                /* @var $select \Krugozor\Framework\Html\ElementSelect */
                                $select->addOption(
                                    $this->getHelper('\Krugozor\Framework\Helper\Form')->inputOption('0', 'Выберите')
                                );
                                $options = $this->getHelper('\Krugozor\Framework\Module\Category\Helper\OptionsListWithOptgroup', $this->tree)->getOptions();
                                foreach ($options as $option):
                                    $select->addOption($option);
                                endforeach;
                                echo $select->getHtml();
                                ?>
                                <div class="description_before_fields">
                                    <p>Почти в каждой тематической рубрике на нашем сайте есть раздел «Услуги» и «Товары».</p>
                                    <ul>
                                        <li>Если ваше объявление связано с предоставлением или спросом на услугу, то выбирайте раздел «Услуги».</li>
                                        <li>В противном случае выбирайте разделы связанные с купле-продажей товаров.</li>
                                    </ul>
                                </div>
                            </div>
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['category'])?>
                        </div>
                    </div>

                    <div class="field_row">
                        <label>
                            <span class="red_star">*</span> Кто вы:
                        </label>
                        <div class="group radiobuttons_classic">
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden(
                                'advert[user_type]',
                                '',
                                ['id' => 'user_type']
                            )->getHtml()?>
                            <?php foreach (Krugozor\Framework\Module\User\Type\Type::getTypes() as $type => $value): ?>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputRadio(
                                    'advert[user_type]',
                                    $type,
                                    ($this->advert->getUserType()->getValue() ?: $this->current_user->getType()->getValue()),
                                    array('id' => 'user_type_' . $type)
                                )->getHtml()?>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->Label(
                                    $value,
                                    'user_type_' . $type
                                )->getHtml()?>
                            <?php endforeach; ?>
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['user_type'])?>
                        </div>
                    </div>

                    <div class="field_row">
                        <label>
                            <span class="red_star">*</span> Предлагаете или ищете:
                        </label>
                        <div class="group radiobuttons_classic">
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden(
                                'advert[type]',
                                '',
                                ['id' => 'advert_type']
                            )->getHtml()?>
                            <?php foreach (\Krugozor\Framework\Module\Advert\Type\AdvertType::getSimpleTypes() as $type => $value): ?>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputRadio(
                                    'advert[type]',
                                    $type,
                                    $this->advert->getType()->getValue(),
                                    ['id' => 'advert_type_' . $type]
                                   )->getHtml()?>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->Label(
                                    $value,
                                    'advert_type_' . $type
                                )->getHtml()?>
                            <?php endforeach; ?>
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['type'])?>
                        </div>
                    </div>

                    <div class="field_row">
                        <label for="advert_header">
                            <span class="red_star">*</span> Заголовок объявления:
                        </label>
                        <div class="group">
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                                'advert[header]',
                                $this->advert->getHeader(),
                                ['maxlength'=>100, 'required' => 'required', 'id' => 'advert_header']
                            )->getHtml()?>
                            <div class="animate_field_description">
                                <div class="animate_field_content">
                                    <div class="description_before_fields">
                                    <p>Введите <b>заголовок объявления</b></p>
                                    <ul>
                                        <li>Не пишите в данном поле информацию про город &mdash; он подставится автоматически.</li>
                                        <li>Чётко опишите предмет совершения сделки или услуги.
                                            Например: &laquo;<em>Автомобиль ВАЗ-2108</em>&raquo;,  &laquo;<em>Строительство домов под ключ</em>&raquo;.<br />
                                        </li>
                                        <li>Не пишите в данном поле цену или контактные данные &mdash; для этой информации есть специальные поля ниже.</li>
                                    </ul>
                                    </div>
                                </div>
                                <div class="triangle-right-border"></div>
                                <div class="triangle-right"></div>
                            </div>
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['header'])?>
                        </div>
                    </div>

                    <div class="field_row">
                        <label for="advert_text">
                            <span class="red_star">*</span> Текст объявления:
                        </label>
                        <div class="group">
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputTextarea(
                                'advert[text]',
                                $this->advert->getText(),
                                ['id'=>'advert_text']
                            )->getHtml()?>
                            <div class="animate_field_description">
                                <div class="animate_field_content">
                                    <div class="description_before_fields">
                                        <p>Введите <b>текст объявления</b></p>
                                        <ul>
                                            <li>Не указывайте в данном поле цену или контактные данные &mdash; для этой информации есть специальные поля ниже.</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="triangle-right-border"></div>
                                <div class="triangle-right"></div>
                            </div>
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['text'])?>
                        </div>
                    </div>

                    <div class="field_row">
                        <label for="advert_price">Цена:</label>
                        <div class="group">
                            <div class="fields_wrap">
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                                    'advert[price]',
                                    $this->advert->getPrice(),
                                    ['maxlength'=>11, 'onkeyup' => 'Krugozor.Forms.filterDigit(this)', 'id' => 'advert_price']
                                )->getHtml()?>
                                <div class="animate_field_description">
                                    <div class="animate_field_content">
                                        <div class="description_before_fields">
                                            <p><b>Укажите цену</b> товара или услуги</p>
                                            <ul>
                                                <li>Пожалуйста, не указывайте в это поле &laquo;ложные&raquo; цены, наподобие 1 рубля. Если не хотите указывать цену &mdash; просто её не указывайте.</li>
                                                <li>Отсутствие цены будет расцениваться как «Цена договорная».</li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="triangle-right-border"></div>
                                    <div class="triangle-right"></div>
                                </div>

                                <?php
                                /* @var $select \Krugozor\Framework\Html\ElementSelect */
                                $select = $this->getHelper('\Krugozor\Framework\Helper\Form')->inputSelect(
                                    'advert[price_type]',
                                    $this->advert->getPriceType()->getValue()
                                );
                                foreach (\Krugozor\Framework\Module\Advert\Type\PriceType::getTypes() as $price_code => $price_data):
                                    $select->addOption(
                                        $this->getHelper('\Krugozor\Framework\Helper\Form')->inputOption($price_code, $price_data[0])
                                    );
                                endforeach;
                                echo $select->getHtml();
                                ?>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['price'])?>

                                <div>
                                    <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox(
                                        'advert[free]', 1, 0,
                                        $this->advert->getFree(),
                                        ['id' => 'label_free', 'onclick' => "if (this.checked) document.getElementById('advert_price').value = '';"]
                                    )?>
                                    <div class="animate_field_description animate_field_description_free">
                                        <div class="animate_field_content">
                                            <div class="description_before_fields">
                                                Отметьте этот параметр только в том случае, если Вы что-то отдаёте или хотите взять исключительно даром.
                                            </div>
                                        </div>
                                        <div class="triangle-right-border"></div>
                                        <div class="triangle-right"></div>
                                    </div>
                                    <label for="label_free">даром</label>
                                    <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['free'])?>
                                </div>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['price_type'])?>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>

            <fieldset>
                <legend>Контактная информация</legend>

                <div class="table">
                    <div class="field_row_fake">
                        <div></div>
                        <div class="group">
                            <?php if ($this->err['contact_info']): ?>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['contact_info'])?>
                            <?php endif; ?>

                            <div class="fields_wrap">
                                <div class="description_before_fields attention">
                                    Необходимо указать хотя бы один из способов связи.
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="field_row">
                        <label for="advert_user_name">Контактное лицо:</label>
                        <div class="group">
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                                'advert[user_name]',
                                $this->advert->getUserName(),
                                ['maxlength'=>255, 'id'=>'advert_user_name', 'autocomplete' => 'on']
                            )->getHtml()?>
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['user_name'])?>

                            <?php if ($this->current_user->getFullName() && !$this->current_user->isGuest()): ?>
                            <p>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox(
                                    'advert[main_user_name]', 1, 0,
                                    $this->advert->getMainUserName(),
                                    array('id' => 'label_main_user_name', 'onchange' => "set_contact_input_state('advert_user_name')")
                                )?>
                                <label for="label_main_user_name">Контактное лицо &mdash; <b><?=$this->current_user->getFullName()?></b></label>
                                <?php if (!$this->advert->getUserName() || $this->advert->getMainUserName()): ?>
                                <script type="text/javascript">
                                set_contact_input_state('advert_user_name');
                                </script>
                                <?php endif; ?>
                            </p>
                            <?php else: ?>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('advert[main_user_name]', 0)->getHtml()?>
                            <?php endif; ?>
                        </div>
                    </div>

                    <div class="field_row">
                        <label for="advert_phone">Телефон:</label>
                        <div class="group">
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                                'advert[phone]',
                                $this->advert->getPhone(),
                                array('maxlength'=>255, 'id'=>'advert_phone', 'autocomplete' => 'on')
                            )->getHtml()?>
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['phone'])?>

                            <?php if ($this->current_user->getPhone()): ?>
                            <p>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox(
                                    'advert[main_phone]', 1, 0,
                                    $this->advert->getMainPhone(),
                                    array('id' => 'label_main_phone', 'onchange' => "set_contact_input_state('advert_phone')")
                                )?>
                                <label for="label_main_phone">Использовать для связи мой основной телефон <b><?=$this->current_user->getPhone()?></b></label>
                                <?php if (!$this->advert->getPhone() || $this->advert->getMainPhone()): ?>
                                <script type="text/javascript">
                                set_contact_input_state('advert_phone');
                                </script>
                                <?php endif; ?>
                            </p>
                            <?php else: ?>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('advert[main_phone]', 0)->getHtml()?>
                            <?php endif; ?>
                        </div>
                    </div>

                    <div class="field_row">
                        <label for="advert_email">Email-адрес:</label>
                        <div class="group">
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputEmail(
                                'advert[email]',
                                $this->advert->getEmail()->getValue(),
                                array('maxlength'=>255, 'id'=>'advert_email', 'autocomplete' => 'on')
                            )->getHtml()?>
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['email'])?>

                            <?php if ($this->current_user->getEmail()->getValue()): ?>
                            <p>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox(
                                    'advert[main_email]', 1, 0,
                                    $this->advert->getMainEmail(),
                                    array('id' => 'label_main_email', 'onchange' => "set_contact_input_state('advert_email')")
                                )?>
                                <label for="label_main_email">Использовать для связи мой основной email-адрес <b><?=$this->current_user->getEmail()->getValue()?></b></label>
                                <?php if (!$this->advert->getEmail()->getValue() || $this->advert->getMainEmail()): ?>
                                <script type="text/javascript">
                                set_contact_input_state('advert_email');
                                </script>
                                <?php endif; ?>
                            </p>
                            <?php else: ?>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('advert[main_email]', 0)->getHtml()?>
                            <?php endif; ?>
                        </div>
                    </div>

                    <div class="field_row">
                        <label for="advert_url">Web-сайт:</label>
                        <div class="group">
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputUrl(
                                'advert[url]',
                                ($this->advert->getUrl()->getValue() ?: 'http://'),
                                array('maxlength' => 255, 'id' => 'advert_url', 'autocomplete' => 'on')
                            )->getHtml()?>
                            <div class="animate_field_description">
                                <div class="animate_field_content">
                                    <div class="description_before_fields">
                                        Введите адрес начиная с http:// или https://
                                    </div>
                                </div>
                                <div class="triangle-right-border"></div>
                                <div class="triangle-right"></div>
                            </div>
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['url'])?>

                            <?php if ($this->current_user->getUrl()->getValue()): ?>
                            <p>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox(
                                    'advert[main_url]', 1, 0,
                                    $this->advert->getMainUrl(),
                                    array('id' => 'label_main_url', 'onchange' => "set_contact_input_state('advert_url')")
                                )?>
                                <label for="label_main_url">Использовать для связи мой основной URL-адрес <b><?=$this->current_user->getUrl()->getNiceAnchor()?></b></label>
                                <?php if (!$this->advert->getUrl()->getValue() || $this->advert->getMainUrl()): ?>
                                <script type="text/javascript">
                                set_contact_input_state('advert_url');
                                </script>
                                <?php endif; ?>
                            </p>
                            <?php else: ?>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('advert[main_url]', 0)->getHtml()?>
                            <?php endif; ?>
                        </div>
                    </div>

                    <div class="field_row">
                        <label for="advert_icq">ICQ:</label>
                        <div class="group">
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                                'advert[icq]',
                                $this->advert->getIcq(),
                                array('maxlength' => 10, 'onkeyup' => "Krugozor.Forms.filterDigit(this)", 'id' => 'advert_icq', 'autocomplete' => 'on')
                            )->getHtml()?>
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['icq'])?>

                            <?php if ($this->current_user->getIcq()): ?>
                            <p>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox(
                                    'advert[main_icq]', 1, 0,
                                    $this->advert->getMainIcq(),
                                    array('id' => 'label_main_icq', 'onchange' => "set_contact_input_state('advert_icq')")
                                )?>
                                <label for="label_main_icq">Использовать для связи мой основной ICQ <b><?=$this->current_user->getIcq()?></b></label>
                                <?php if (!$this->advert->getIcq() || $this->advert->getMainIcq()): ?>
                                <script type="text/javascript">
                                set_contact_input_state('advert_icq');
                                </script>
                                <?php endif; ?>
                            </p>
                            <?php else: ?>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('advert[main_icq]', 0)->getHtml()?>
                            <?php endif; ?>
                        </div>
                    </div>

                    <div class="field_row">
                        <label for="advert_skype">Skype:</label>
                        <div class="group">
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                                'advert[skype]',
                                $this->advert->getSkype(),
                                array('maxlength' => 32, 'id' => 'advert_skype', 'autocomplete' => 'on')
                            )->getHtml()?>
                            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['skype'])?>

                            <?php if ($this->current_user->getSkype()): ?>
                            <p>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox(
                                    'advert[main_skype]', 1, 0,
                                    $this->advert->getMainSkype(),
                                    array('id' => 'label_main_skype', 'onchange' => "set_contact_input_state('advert_skype')")
                                )?>
                                <label for="label_main_skype">Использовать для связи мой основной Skype <b><?=$this->current_user->getSkype()?></b></label>
                                <?php if (!$this->advert->getSkype() || $this->advert->getMainSkype()): ?>
                                <script type="text/javascript">
                                set_contact_input_state('advert_skype');
                                </script>
                                <?php endif; ?>
                            </p>
                            <?php else: ?>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('advert[main_skype]', 0)->getHtml()?>
                            <?php endif; ?>
                        </div>
                    </div>

                    <div class="field_row">
                        <label>
                            <span class="red_star">*</span> Укажите территориальное<br>местоположение объекта<br />сделки:
                        </label>
                        <div class="group">
                            <div class="fields_wrap cities">
                                <p>
                                    <span class="city_field_description">Страна:</span>
                                    <span id="js_country_select_wrap"></span>
                                    <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['place_country'])?>
                                </p>

                                <p>
                                    <span class="city_field_description">Регион:</span>
                                    <span id="js_region_select_wrap"></span>
                                    <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['place_region'])?>
                                </p>

                                <p>
                                    <span class="city_field_description">Город:</span>
                                    <span id="js_city_select_wrap"></span>
                                    <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['place_city'])?>
                                </p>

                                <?php if (
                                    $this->current_user->isGuest() or
                                    !$this->current_user->isGuest() && !$this->current_user->getCountry() && !$this->current_user->getRegion() && !$this->current_user->getCity()):
                                ?>
                                    <div id="simple_city_checked">
                                        <p>Быстрое указание местоположения:</p>
                                        <dl>
                                            <dt id="ru_icon">Россия:</dt>
                                            <dd>
                                                <a href="#" onclick="return simple_city_checked(3159, 4312, 4400)">Москва</a>,
                                                <a href="#" onclick="return simple_city_checked(3159, 4925, 4962)">Санкт-Петербург</a>,
                                                <a href="#" onclick="return simple_city_checked(3159, 4528, 4549)">Новосибирск</a>,
                                                <a href="#" onclick="return simple_city_checked(3159, 5080, 5106)">Екатеринбург</a>,
                                                <a href="#" onclick="return simple_city_checked(3159, 3563, 3612)">Нижний Новгород</a>,
                                                <a href="#" onclick="return simple_city_checked(3159, 5246, 5269)">Казань</a>,
                                                <a href="#" onclick="return simple_city_checked(3159, 4891, 4917)">Самара</a>,
                                                <a href="#" onclick="return simple_city_checked(3159, 5507, 5539)">Челябинск</a>,
                                                <a href="#" onclick="return simple_city_checked(3159, 4561, 4580)">Омск</a>,
                                                <a href="#" onclick="return simple_city_checked(3159, 4800, 4848)">Ростов-на-Дону</a>,
                                                <a href="#" onclick="return simple_city_checked(3159, 3296, 3345)">Уфа</a>,
                                                <a href="#" onclick="return simple_city_checked(3159, 4105, 4149)">Красноярск</a>,
                                                <a href="#" onclick="return simple_city_checked(3159, 4689, 4720)">Пермь</a>
                                                <a href="#" onclick="return simple_city_checked(3159, 3468, 3472)">Волгоград</a>,
                                                <a href="#" onclick="return simple_city_checked(3159, 3529, 3538)">Воронеж</a>
                                            </dd>

                                            <dt id="nr_icon">Новороссия:</dt>
                                            <dd>
                                                <a href="#" onclick="return simple_city_checked(9909, 10002, 10029)">Донецк</a>,
                                                <a href="#" onclick="return simple_city_checked(9909, 10259, 10299)">Луганск</a>,
                                                <a href="#" onclick="return simple_city_checked(9909, 10002, 10046)">Макеевка</a>
                                            </dd>

                                            <dt id="by_icon">Белорусия:</dt>
                                            <dd>
                                                <a href="#" onclick="return simple_city_checked(248, 349, 269)">Минск</a>,
                                                <a href="#" onclick="return simple_city_checked(248, 304, 312)">Гомель</a>,
                                                <a href="#" onclick="return simple_city_checked(248, 377, 393)">Могилёв</a>,
                                                <a href="#" onclick="return simple_city_checked(248, 272, 281)">Витебск</a>,
                                                <a href="#" onclick="return simple_city_checked(248, 330, 334)">Гродно</a>,
                                                <a href="#" onclick="return simple_city_checked(248, 249, 255)">Брест</a>
                                            </dd>
                                            <dt id="ua_icon">Украина:</dt>
                                            <dd>
                                                <a href="#" onclick="return simple_city_checked(9908, 10165, 10184)">Киев</a>,
                                                <a href="#" onclick="return simple_city_checked(9908, 10504, 10532)">Харьков</a>,
                                                <a href="#" onclick="return simple_city_checked(9908, 10373, 10398)">Одесса</a>,
                                                <a href="#" onclick="return simple_city_checked(9908, 9964, 9977)">Днепропетровск</a>,
                                            </dd>
                                            <dt id="kz_icon">Казахстан:</dt>
                                            <dd>
                                                <a href="#" onclick="return simple_city_checked(1894, 1911, 1913)">Алматы</a>,
                                                <a href="#" onclick="return simple_city_checked(1894, 2128, 4778059)">Астана</a>,
                                                <a href="#" onclick="return simple_city_checked(1894, 2146, 2160)">Шымкент</a>
                                            </dd>
                                        </dl>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>

                    <?php if ($this->current_user->isGuest()): ?>
                    <div class="field_row">
                        <label for="captcha_code"><span class="red_star">*</span> Введите цифры<br />с изображения:</label>
                        <div class="group captcha_block">
                            <div class="fields_wrap">
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                                    'captcha_code',
                                    $this->captcha_code,
                                    array('onkeyup' => 'Krugozor.Forms.filterDigit(this)', 'maxlength' => 4, 'required' => 'required', 'id' => 'captcha_code')
                                )->getHtml()?><!--
                                 --><div class="animate_field_description animate_field_captcha">
                                        <div class="animate_field_content">
                                            <div class="description_before_fields">
                                                Если Вы не видите число на картинке, нажмите на картинку мышкой
                                            </div>
                                        </div>
                                        <div class="triangle-right-border"></div>
                                        <div class="triangle-right"></div>
                                    </div><!--
                                 --><img onclick="this.src=this.src+'&amp;'+Math.round(Math.random())" alt=""
                                         title="Если Вы не видите число на картинке, нажмите на картинку мышкой"
                                         src="/captcha/main/?session_name=<?= $this->session_name ?>&amp;session_id=<?= $this->session_id ?>"/>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden($this->session_name, $this->session_id)->getHtml()?>
                                <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['captcha'])?>
                            </div>
                        </div>
                    </div>
                    <?php endif; ?>
                </div>

            </fieldset>

            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('advert[id]', $this->advert->getId())->getHtml()?>

            <?php if ($this->advert->getThumbnailsList()->count()): ?>
                <?php foreach ($this->advert->getThumbnailsList() as $thumbnail): ?>
                    <input type="hidden" name="thumbnail[]" value="<?=$thumbnail->getId()?>" />
                <?php endforeach; ?>
            <?php endif; ?>
        </form>

        <fieldset><legend>Фотографии</legend>
            <div id="photo_rules">
                <p>Фотографии товаров, прикреплённые к объявлениям, повышают вероятность того, что ваше объявление заинтересует пользователя.</p>
                <ul>
                    <li>Первое загруженное изображение будет основным.</li>
                    <li>Загружаемый файл должен быть размером не более <?=\Krugozor\Framework\Registry::getInstance()->UPLOAD['MAX_FILE_SIZE']?>.</li>
                    <li>Максимальное количество изображений &mdash; <?=\Krugozor\Framework\Registry::getInstance()->UPLOAD['MAX_FILES_COUNT']?>.</li>
                </ul>
            </div>

            <div id="uploaded_images"<?php if ($this->advert->getThumbnailsList()->count()): ?> class="display"<? endif; ?>>
            <?php if ($this->advert->getThumbnailsList()->count()): ?>
                <?php foreach ($this->advert->getThumbnailsList() as $thumbnail): ?><span><img src="/i/150x100<?=$thumbnail->getFullHttpPath()?>" alt="" /><a data-advert="<?=$thumbnail->getIdAdvert()?>" data-id="<?=$thumbnail->getId()?>" title="Удалить изображение" href="#"></a></span><?php endforeach; ?>
            <?php endif; ?>
            </div>

            <iframe width="0" height="0" name="iframe"></iframe>

            <form id="file_upload_form" method="post" enctype="multipart/form-data" target="iframe">
                <div id="thumbnail_errors"></div>
                <input type="hidden" name="MAX_FILE_SIZE" value="<?=$this->max_file_size?>" />
                Загрузить изображение: <input type="file" name="file" id="file" checked="0" />
                <? if ($this->advert->getThumbnailsList()->count() == \Krugozor\Framework\Registry::getInstance()->UPLOAD['MAX_FILES_COUNT']): ?>
                    <div>Загружено максимально-допустимое количество изображений.</div>
                <? endif; ?>
            </form>
        </fieldset>

        <div class="submit_block">
            <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputButton(
                'submit_normal',
                $this->advert->getId() ? 'Сохранить объявление' : 'Разместить объявление'
            )->getHtml()?>
            <?php if(!$this->advert->getId()): ?>
                <div id="terms_of_service">Подавая объявление, Вы соглашаетесь с <a target="_blank" href="/help/terms_of_service">условиями использования сайта</a></div>
            <?php endif; ?>
        </div>

    </div>

    <!-- end content -->
</div>

<script type="text/javascript">
Krugozor.Location.addCheckedUserLocation(1, '<?=$this->advert->getPlaceCountry()?>');
Krugozor.Location.addCheckedUserLocation(2, '<?=$this->advert->getPlaceRegion()?>');
Krugozor.Location.addCheckedUserLocation(3, '<?=$this->advert->getPlaceCity()?>');

var select_country_attributes = {
	name: 'advert[place_country]',
	value: '<?=$this->advert->place_country?>'
};
var selectCountryObj = Krugozor.Location.createLocation(select_country_attributes, 'Выберите страну проживания');
document.getElementById('js_country_select_wrap').appendChild(selectCountryObj.SelectElement);

var select_region_attributes = {
	name: 'advert[place_region]',
	value: '<?=$this->advert->place_region?>'
};
var selectRegionObj = Krugozor.Location.createLocation(select_region_attributes, 'Выберите регион проживания');
document.getElementById('js_region_select_wrap').appendChild(selectRegionObj.SelectElement);

var select_city_attributes = {
	name: 'advert[place_city]',
	value: '<?=$this->advert->place_city?>'
};
var selectCityObj = Krugozor.Location.createLocation(select_city_attributes, 'Выберите город проживания');
document.getElementById('js_city_select_wrap').appendChild(selectCityObj.SelectElement);

selectCountryObj.create(1, 0);
selectRegionObj.create(2, <?=(int)$this->advert->getPlaceCountry()?>);
selectCityObj.create(3, <?=(int)$this->advert->getPlaceRegion()?>);
</script>

<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>

</body>
</html>