<!DOCTYPE html>
<html lang="ru">
<head>

<!-- todo -->

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="keywords" content="<?=$this->lang['meta']['keywords']?>" />
<meta name="description" content="<?=$this->lang['meta']['description']?>" />
<link rel="shortcut icon" sizes="16x16" href="/favicon.ico" />

<?=$this->getHelper('\Krugozor\Framework\Html\Title')->getHtml()?>

<?=$this->getCss('/http/css/main.css', false)?>

</head><body>

<? include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div id="<?=$this->getPageId()?>" class="content">
    <? include $this->getRealTemplatePath('Common/FrontendNotification') ?>
</div>

<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>

</body></html>