<!DOCTYPE html>
<html lang="ru">
<head>

    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="keywords"
          content="<?= ($this->category->getKeywords() ? strip_tags($this->category->getKeywords()) : $this->lang['meta']['keywords']) ?>"/>
    <meta name="description"
          content="<?= $this->getHelper('\Krugozor\Framework\Helper\Format')->userDataOutput($this->getHelper('\Krugozor\Framework\Html\Title')->getLastElement()) ?>"/>
    <meta property="og:title"
          content="<?= $this->getHelper('\Krugozor\Framework\Helper\Format')->userDataOutput($this->getHelper('\Krugozor\Framework\Html\Title')->getLastElement()) ?>"/>
    <meta property="og:description" content="<?= $this->getLang()['meta']['description'] ?>"/>
    <meta property="og:image"
          content="<?php if ($this->advert->getThumbnailsList()->count()): ?><?= \Krugozor\Framework\Registry::getInstance()->HOSTINFO['HOST_URL'] ?>/i/800x800<?= $this->advert->getThumbnailsList()->item(0)->getFullHttpPath() ?><?php else: ?>/http/image/desing/snippet.jpg<?php endif; ?>"/>
    <meta property="og:url" content="<?= $this->getRequest()->getCanonicalRequestUri()->getEscapeUriValue(true) ?>"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>
    <link rel="index" href="<?= $this->region_paths['city'] ?>/categories/"/>
    <link rel="start" href="<?= $this->region_paths['city'] ?>/categories<?= $this->category->getUrl() ?>"/>
    <?php if ($this->near_adverts['prev']->getId()): ?>
        <link rel="prev"
              title="<?= $this->getHelper('\Krugozor\Framework\Helper\Format')->userDataOutput($this->near_adverts['prev']->getHeader()) ?>"
              href="/advert/<?= $this->near_adverts['prev']->getId() ?>.xhtml"/>
    <?php endif; ?>
    <?php if ($this->near_adverts['next']->getId()): ?>
        <link rel="next"
              title="<?= $this->getHelper('\Krugozor\Framework\Helper\Format')->userDataOutput($this->near_adverts['next']->getHeader()) ?>"
              href="/advert/<?= $this->near_adverts['next']->getId() ?>.xhtml"/>
    <?php endif; ?>

    <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getHtml() ?>

    <!-- common css -->
    <?= $this->getCss('common', 'reset.css', false) ?>
    <?= $this->getCss('common', 'tags.css', false) ?>
    <?= $this->getCss('common', 'classes.css', false) ?>
    <?= $this->getCss('common', 'structure.css', false) ?>
    <!-- /common css -->
    <?= $this->getCss('advert', '_adverts-list.css', true) ?>
    <?= $this->getCss() ?>

    <?= $this->getJs('common', 'library/krugozor.js') ?>
    <?= $this->getJs('common', 'library/krugozor.ajax.js') ?>
    <?= $this->getJs('common', 'library/krugozor.ui.popup.image.js') ?>

    <?= $this->getJs('common', 'tooltip.js') ?>
    <?= $this->getJs('common', 'jquery/jquery-1.9.1.min.js') ?>
    <?= $this->getJs() ?>
    <?= $this->getJs('advert', '_adverts-list.js', true); ?>

</head>
<body>

<? include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div class="content">

    <h2>
        <a href="<?= $this->region_paths['city'] ?>/categories/">Объявления<?php if ($this->city): ?> в <?= $this->city->getNameRu2() ?><?php endif; ?></a>
        <?= $this->getHelper('\Krugozor\Framework\Module\Category\Helper\BreadCrumbs', $this->path_to_category, $this->region_paths['city'] . '/categories', '/')->lastElementIsLink(true)->getHtml() ?>
    </h2>

    <? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

    <?php if (
        ($this->advert->getActive() or !$this->advert->getActive() && $this->advert->getIdUser() === $this->current_user->getId())
        and
        ($this->user->getActive() && !$this->user->isGuest() or $this->user->isGuest())
    ): ?>
        <?php include_once($this->getRealTemplatePath('Advert/AdvertsList')); ?>
    <?php endif; ?>


    <?php if ($this->similar_adverts && $this->similar_adverts->count()): ?>
        <aside class="carousel">
            <div class="bheader">Другие объявления из категории &laquo;<?= $this->category->getName() ?>&raquo;:</div>
            <ul>
                <?php foreach ($this->similar_adverts as $data): ?>
                    <?php
                    $advert_text = $advert_text = \Krugozor\Framework\Helper\Format::getPreviewStr($data['advert']->getText(), 140, '...');
                    $advert_text = $this->getHelper('\Krugozor\Framework\Helper\Format')->userDataOutput($advert_text);
                    ?>
                    <li class="<?php if ($data['advert']->getDenormalizationThumbnailsList()->count()): ?>do_animaton<?php endif; ?> <?php if ($data['advert']->getId() == $this->advert->getId()): ?>selected<? endif; ?>">
                        <a title="<?= $advert_text ?>" href="/advert/<?= $data['advert']->getId() ?>.xhtml">
                            <span class="image_wrap">
                            <?php if ($data['advert']->getDenormalizationThumbnailsList()->count()): ?>
                                <img src="/i/150x100<?= $data['advert']->getDenormalizationThumbnailsList()->item(0)->getFullHttpPath() ?>"
                                     alt="<?= $this->getHelper('\Krugozor\Framework\Helper\Format')->userDataOutput($data['advert']->getHeader()) ?>"/>
                                <span class="photocamera"><span><?= $data['advert']->getThumbnailCount() ?></span></span>
                            <?php else: ?>
                                <img class="no_photo" src="/http/image/desing/icon/no_photo.png" alt=""/>
                            <?php endif; ?>

                                <?php if ($data['advert']->getId() != $this->advert->getId()): ?>
                                    <span class="similar_header">
                                    <span class="text"><?= $this->getHelper('\Krugozor\Framework\Helper\Format')->userDataOutput($data['advert']->getHeader(), 50) ?></span>
                                </span>
                                <?php endif; ?>
                            </span>
                        </a>
                        <a href="/advert/<?= $data['advert']->getId() ?>.xhtml">
                            <span>
                                <?= \Krugozor\Framework\Helper\Format::getPreviewStr($data['advert']->getText(), 170, '...') ?>
                            </span>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </aside>
    <?php endif; ?>

</div>

<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>

</body>
</html>