<table class="datatable menu">
    <tr>
        <td>
            <a href="/authorization/logout/?referer=/admin/">Выход из системы</a>
            <div>
                <a href="/user/backend-main/">Пользователи</a> <span class="vhr">|</span>
                <a href="/group/backend-main/">Административные группы</a> <span class="vhr">|</span>
                <a href="/module/backend-main/">Модули</a> <span class="vhr">|</span>
                <a href="/category/backend-main/">Категории</a> <span class="vhr">|</span>
                <a href="/user/backend-country-list/">Страны</a> <span class="vhr">|</span>
                <a href="/user/backend-region-list/">Регионы</a> <span class="vhr">|</span>
                <a href="/user/backend-city-list/">Города</a> <span class="vhr">|</span>
            </div>
        </td>
    </tr>
</table>