<?php use Krugozor\Framework\Notification; ?>
<?php /* @var $this \Krugozor\Framework\View */ ?>
<?php if ($this->getNotification() && !$this->getNotification()->getHidden()): ?>
    <div id="notification_<?= $this->getNotification()->getType() ?>"
         class="notification_<?= $this->getNotification()->getType() ?>">
        <h3>
            <?php if ($this->getNotification()->getHeader()) : ?>
                <?= $this->getNotification()->getHeader() ?>
            <?php else: ?>
                <?php
                switch ($this->getNotification()->getType()) {
                    case Notification::TYPE_ALERT:
                        echo $this->getLang()['notification']['header']['action_failed'];
                        break;
                    case Notification::TYPE_WARNING:
                        echo $this->getLang()['notification']['header']['action_warning'];
                        break;
                    case Notification::TYPE_NORMAL:
                    default:
                        echo $this->getLang()['notification']['header']['action_complete'];
                }
                ?>
            <?php endif; ?>
        </h3>
        <?= $this->getNotification()->getMessage() ?>
    </div>
<? endif; ?>