<footer>
    <div class="two_column">
	    <div class="left_column">
			<div class="left_column_content">
				<?=Krugozor_Registry::getInstance()->HOSTINFO['HOST_SIMPLE']?> 2009&mdash;<?=date('Y')?>
			</div>
		</div>
		<div class="right_column">
			<div class="right_column_content">
                <ul>
                    <li><a href="/help/faq">Вопросы и ответы</a><i>&nbsp;|</i></li>
                    <li><a href="/help/terms_of_service">Соглашение об условиях использования</a><i>&nbsp;|</i></li>
                    <li><a href="/help/sale">Инвесторам</a><i>&nbsp;|</i></li>
                    <li><a href="/help/about">О сайте</a></li>
                </ul>
			</div>
		</div>
	</div>


	<?php if ($this->online_users && $this->online_users->count()): ?>
        <!--noindex-->
        <div class="users_online">
            Зарегистрированных пользователей сейчас на сайте (<?=$this->online_users->count()?>):
            <?php $i=0; foreach($this->online_users as $user): $i++; ?>
                <span title="<?=$user->getVisitdate()->formatDateForPeople()?>"><?=$user->getFullNameOrLogin()?></span><?php if ($i < $this->online_users->count()): ?>, <?php endif; ?>
            <?php endforeach; ?>
        </div>
        <!--/noindex-->
	<?php endif; ?>

    <div class="bottom_buttons">
        <!--noindex-->
        <span>
            <!--LiveInternet counter--><script type="text/javascript"><!--
            document.write("<a href='http://www.liveinternet.ru/click' "+
            "target=_blank><img src='//counter.yadro.ru/hit?t16.10;r"+
            escape(document.referrer)+((typeof(screen)=="undefined")?"":
            ";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
            screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
            ";h"+escape(document.title.substring(0,80))+";"+Math.random()+
            "' alt='' title='LiveInternet: показано число просмотров за 24"+
            " часа, посетителей за 24 часа и за сегодня' "+
            "border='0' width='88' height='31'><\/a>")
            //--></script><!--/LiveInternet-->
        </span>
        <span>
            <a rel="nofollow" href="http://yandex.ru/cy?base=0&amp;host=<?=$_SERVER['HTTP_HOST']?>"><img src="http://www.yandex.ru/cycounter?<?=$_SERVER['HTTP_HOST']?>" width="88" height="31" alt="Яндекс цитирования" /></a>
        </span>
        <span>
            <a rel="nofollow" href="http://validator.w3.org/check?uri=referer"><img src="/http/image/desing/icon/html5valid.gif" alt="<?=Krugozor_Registry::getInstance()->HOSTINFO['HOST_SIMPLE']?> следует стандартам World Wide Web Consortium" title="<?=Krugozor_Registry::getInstance()->HOSTINFO['HOST_SIMPLE']?> следует стандартам World Wide Web Consortium" /></a>
        </span>
        <!--/noindex-->
    </div>
</footer>

<? include $this->getRealTemplatePath('Common/DebugInfo') ?>

</div> <!-- / end wrap -->