<!DOCTYPE html>
<html lang="ru">
<head>
    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="<?= $this->lang['meta']['keywords'] ?>"/>
    <meta name="description" content="<?= $this->lang['meta']['description'] ?>"/>
    <meta property="og:title" content="<?= $this->getHelper('\Krugozor\Framework\Html\Title')->getTitle() ?>"/>
    <meta property="og:description" content="<?= $this->lang['meta']['description'] ?>"/>
    <meta property="og:image" content="/http/image/desing/snippet.jpg"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>

    <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getHtml() ?>

    <!-- common js -->
    <?= $this->getCss('common', 'reset.css', false) ?>
    <?= $this->getCss('common', 'tags.css', false) ?>
    <?= $this->getCss('common', 'classes.css', false) ?>
    <?= $this->getCss('common', 'structure.css', false) ?>
    <!-- /common js -->
    <?= $this->getCss() ?>

</head>
<body>

<?php include $this->getRealTemplatePath('Local/FrontendTop') ?>

<div id="<?= $this->getPageId() ?>" class="content">
    <h2><?= $this->lang['content']['document_not_found_header'] ?></h2>
    <?= $this->lang['content']['document_not_found_body'] ?>
</div>

<?php require_once $this->getRealTemplatePath('Local/FrontendBottom'); ?>

</body>
</html>