<!DOCTYPE html>
<html lang="ru">
<head>

    <!-- common meta -->
    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="<?= $this->getLang()['meta']['keywords'] ?>"/>
    <meta name="description" content="<?= $this->getLang()['meta']['description'] ?>"/>
    <meta property="og:title" content="<?= $this->getHelper('\Krugozor\Framework\Html\Title')->getTitle() ?>"/>
    <meta property="og:description" content="<?= $this->getLang()['meta']['description'] ?>"/>
    <meta property="og:image" content="/img/local/snippet.jpg"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>
    <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getHtml() ?>
    <!-- /common meta -->

    <!-- common css -->
    <?= $this->getCss('common', 'reset.css', false) ?>
    <?= $this->getCss('common', 'tags.css', false) ?>
    <?= $this->getCss('common', 'classes.css', false) ?>
    <?= $this->getCss('common', 'structure.css', false) ?>
    <!-- /common css -->
    <?= $this->getCss() ?>

    <?= $this->getJs('common', 'library/krugozor.js') ?>

</head>
<body>

<? if ($path = $this->getRealTemplatePath('Local/FrontendTop')) include $path; ?>

<div id="<?= $this->getPageId() ?>" class="content">

    <? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

    <div class="three_column three_column_wrap">
        <div class="left_column">
            <div class="left_column_content">
                <!-- Левый столбец -->
                <!-- /Левый столбец -->
            </div>
        </div>

        <div class="center_column">
            <div class="center_column_content">
                <!-- Центральный столбец -->
                <!-- /Центральный столбец -->
            </div>
        </div>

        <div class="right_column">
            <div class="right_column_content">
                <!-- Правый столбец -->
                <!-- /Правый столбец -->
            </div>
        </div>
    </div>

</div>

<? if ($path = $this->getRealTemplatePath('Local/FrontendBottom')) include $path; ?>

</body>
</html>