<!DOCTYPE html>
<html lang="ru">
<head>

    <!-- common meta -->
    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>
    <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getHtml() ?>
    <!-- /common meta -->

    <!-- common css -->
    <?= $this->getCss('common', 'reset.css') ?>
    <?= $this->getCss('common', 'tags.css') ?>
    <?= $this->getCss('common', 'backend.css') ?>
    <!-- /common css -->
    <?= $this->getCss() ?>

    <?= $this->getJs('common', 'library/krugozor.js') ?>
    <?= $this->getJs('common', 'library/krugozor.forms.js') ?>
    <?= $this->getJs('authorization', 'login.js') ?>

</head>
<body>

<?php if (!$this->current_user->isGuest()): ?>

    <? include $this->getRealTemplatePath('Common/BackendNotification') ?>
    <? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<?php else: ?>

    <div id="center_block">
        <? include $this->getRealTemplatePath('Common/BackendNotification') ?>

        <h3><?= $this->getLang()['title'][1] ?></h3>

        <form id="auth" onsubmit="if (window.cform) return cform.checkTextFieldsOnEmpty();" method="post"
              action="<?= $this->getRequest()->getRequestUri()->getEscapeUriValue() ?>">
            <table class="datatable clear edit">
                <colgroup>
                    <col/>
                    <col/>
                </colgroup>
                <tr>
                    <td class="compulsory">
                        <?= $this->getLang()['content']['login'] ?>:
                    </td>
                    <td>
                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                            'user[login]',
                            $this->user->getLogin(),
                            array('class' => 'text', 'maxlength' => 255, 'id' => 'user_login', 'title' => 'Введите логин', 'class' => 'text')
                        )->getHtml() ?>
                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['authorization']) ?>
                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['login']) ?>
                    </td>
                </tr>
                <tr>
                    <td class="compulsory">
                        <?= $this->getLang()['content']['password'] ?>:
                    </td>
                    <td>
                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputPassword(
                            'user[password]',
                            '',
                            array('class' => 'text', 'maxlength' => 255, 'id' => 'user_password', 'title' => 'Введите пароль', 'class' => 'text')
                        )->getHtml() ?>
                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['password']) ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->Label(
                            $this->getLang()['content']['remember_password'] . ':', 'autologin'
                        )->getHtml() ?>
                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox(
                            'autologin', 1, 0, $this->autologin, array('id' => 'autologin')
                        ) ?>
                        <p id="change_cookie_days"
                           class="changeCookieDays<? if ($this->autologin): ?> show<? endif; ?>">
                            <?php
                            echo Krugozor\Framework\Statical\Strings::createMessageFromParams(
                                $this->getLang()['content']['remember_password_description'],
                                ['days' => $this->ml_autologin],
                                false
                            );
                            ?>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden(
                            'ml_autologin', $this->ml_autologin, array('id' => 'ml_autologin')
                        )->getHtml() ?>
                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden(
                            'referer', $this->referer
                        )->getHtml() ?>
                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputSubmit(
                            'submit', $this->getLang()['content']['login_in_panel']
                        )->getHtml() ?>
                    </td>
                </tr>
            </table>
        </form>
    </div>

    <script type="text/javascript">
        try {
            var cform = new Krugozor.Forms.Checker('auth');
            cform.putFocus();
        } catch (e) {
            console.log(e)
        }
    </script>

<?php endif; ?>

</body>
</html>