<!DOCTYPE html>
<html lang="ru">
<head>

    <!-- common meta -->
    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="<?= $this->getLang()['meta']['keywords'] ?>"/>
    <meta name="description" content="<?= $this->getLang()['meta']['description'] ?>"/>
    <meta property="og:title" content="<?= $this->getHelper('\Krugozor\Framework\Html\Title')->getTitle() ?>"/>
    <meta property="og:description" content="<?= $this->getLang()['meta']['description'] ?>"/>
    <meta property="og:image" content="/http/image/desing/snippet.jpg"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>
    <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getHtml() ?>
    <!-- /common meta -->

    <!-- common css -->
    <?= $this->getCss('common', 'reset.css') ?>
    <?= $this->getCss('common', 'tags.css') ?>
    <?= $this->getCss('common', 'classes.css') ?>
    <?= $this->getCss('common', 'structure.css') ?>
    <!-- /common css -->
    <?= $this->getCss() ?>

    <?= $this->getJs('common', 'library/krugozor.js') ?>
    <?= $this->getJs('common', 'library/krugozor.forms.js') ?>
    <?= $this->getJs('common', 'library/krugozor.ajax.js') ?>
    <?= $this->getJs('common', 'tooltip.js') ?>
    <?= $this->getJs('common', 'jquery/jquery-1.11.1.min.js') ?>
    <?= $this->getJs('authorization', 'login.js') ?>

</head>
<body>

<? include $this->getRealTemplatePath('Local/FrontendTop') ?>

<div id="<?= $this->getPageId() ?>" class="content">

    <h2><?= $this->getHelper('\Krugozor\Framework\Html\Title')->getByIndex(1) ?></h2>

    <? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

    <?php if (!$this->current_user->isGuest()): ?>
        <div class="two_column login">
            <div class="left_column">
                <ul id="my_actions">
                    <li class="adverts">
                        <a href="/advert/frontend-edit-advert/">Подать новое объявление</a>
                    </li>
                    <li class="new">
                        <a href="/advert/frontend-user-adverts-list/">Управлять моими объявлениями</a>
                    </li>
                    <li class="userinfo">
                        <a href="/user/frontend-edit/">Мои личные данные</a>
                    </li>
                    <li class="logout">
                        <a onclick="return confirm('Вы действительно хотите завершить работу с сайтом?')"
                           href="/authorization/logout/?referer=<?= $this->getRequest()->getRequestUri()->getUrlencodeUriValue(true) ?>">Выйти</a>
                    </li>
                </ul>
            </div>
            <div class="right_column">
                <script type="text/javascript" src="//vk.com/js/api/openapi.js?121"></script>
                <!-- VK Widget -->
                <div id="vk_groups"></div>
                <script type="text/javascript">
                    VK.Widgets.Group("vk_groups", {mode: 2, width: "500"}, 120400274);
                </script>
            </div>
        </div>
    <?php else: ?>
        <form id="auth" onsubmit="if (window.cform) return cform.checkTextFieldsOnEmpty();" method="post"
              action="<?= $this->getRequest()->getRequestUri()->getEscapeUriValue() ?>">
            <fieldset>
                <legend>Авторизация</legend>

                <div class="two_column logout">
                    <div class="left_column">
                        <div class="left_column_content">
                            <div class="table">
                                <?php if ($this->err['authorization']): ?>
                                    <div class="field_row_fake">
                                        <div></div>
                                        <div class="group">
                                            <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['authorization']) ?>
                                        </div>
                                    </div>
                                <?php endif; ?>

                                <div class="field_row">
                                    <label class="compulsory" for="user_login">
                                        <span class="red_star">*</span> Логин:
                                    </label>
                                    <div class="group">
                                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                                            'user[login]',
                                            $this->user->getLogin(),
                                            array('class' => 'text', 'maxlength' => 255, 'id' => 'user_login', 'class' => 'text')
                                        )->getHtml() ?>
                                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['login']) ?>
                                    </div>
                                </div>

                                <div class="field_row">
                                    <label class="compulsory" for="user_password">
                                        <span class="red_star">*</span> Пароль:
                                    </label>
                                    <div class="group">
                                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputPassword(
                                            'user[password]',
                                            '',
                                            array('class' => 'text', 'maxlength' => 255, 'id' => 'user_password', 'class' => 'text')
                                        )->getHtml() ?>
                                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['password']) ?>
                                    </div>
                                </div>

                                <div class="field_row">
                                    <label id="for_autologin" for="autologin">Запомнить пароль:</label>
                                    <div class="group">
                                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox(
                                            'autologin', 1, 0,
                                            $this->autologin,
                                            array('id' => 'autologin')
                                        ) ?>
                                        <div class="animate_field_description animate_field_description_remember_password">
                                            <div class="animate_field_content">
                                                <div class="description_before_fields">
                                                    <p>Включать данную опцию следует лишь в том случае, когда Вы твёрдо
                                                        убеждены,
                                                        что к данному компьютеру нет доступа посторонних лиц,
                                                        способных несанкционированно изменить или удалить Ваши
                                                        данные.</p>
                                                </div>
                                            </div>
                                            <div class="triangle-right-border"></div>
                                            <div class="triangle-right"></div>
                                        </div>
                                        <div id="change_cookie_days"<? if ($this->autologin): ?> style="display:block"<? endif; ?>>
                                            Запомнить пароль на <a title="изменить количество дней"
                                                                   id='CookieDays'><?= $this->ml_autologin ?></a> дней
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="right_column">
                        <div class="right_column_content">
                            <ul class="information">
                                <li>
                                    <p>Если Вы забыли свой пароль, то воспользуйтесь
                                        <a title="Восстановить забытый пароль" href="/getpassword/frontend-getpassword/">системой
                                            восстановления пароля</a>.</p>
                                </li>
                                <li>
                                    <p>Если Вы не зарегистрированы на сайте, то <a title="Регистрация"
                                                                                   href="/user/frontend-registration/">это можно
                                            сделать прямо сейчас</a>.</p>
                                </li>
                                <li>
                                    <p>Подавать объявления на сайт можно <a href="/advert/frontend-edit-advert/">без регистрации</a>.
                                    </p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

            </fieldset>

            <div class="submit_block">
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden(
                    'ml_autologin',
                    $this->ml_autologin,
                    array('id' => 'ml_autologin')
                )->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden(
                    'referer',
                    $this->referer
                )->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputSubmit(
                    'submit',
                    'Войти в личный кабинет'
                )->getHtml() ?>
            </div>
        </form>

        <script type="text/javascript">
            try {
                var cform = new Krugozor.Forms.Checker('auth');
                cform.putFocus();
            } catch (e) {
            }
        </script>
    <?php endif; ?>

</div>

<? include $this->getRealTemplatePath('Local/FrontendBottom') ?>

</body>
</html>