<aside id="payment_popup" class="payment_popup">
	<h3>Хотите привлечь больше внимание на своё объявление и повысить его эффективность?</h3>
	<p class="description_strong">Всего <span class="price">за <?=Krugozor_Registry::getInstance()->PAYMENTS['PAYMENT_ACTION_TOP']?> рублей</span> вы можете сделать ваше объявление более заметным &mdash; объявление будет выделено особым цветом, будет находиться выше других бесплатных объявлений, соответственно его увидят больше посетителей сайта:</p>
	<div class="center"><img src="/http/image/desing/vip_demo_1.jpg" alt=""></div>
	<div class="center">
<!-- 		<div class="formL"> -->
<!--     		<div> -->
<!--     			<a id="payment_button" href="http://auth.robokassa.ru/Merchant/Index.aspx" target="_top">оплатить</a> -->
<!--     			<img alt="robokassa" src="https://auth.robokassa.ru/Merchant/PaymentForm/Images/logo-xl.png" /> -->
<!--     		</div> -->
<!--         </div> -->
	   <input type="button" value="Выделить объявление за <?=Krugozor_Registry::getInstance()->PAYMENTS['PAYMENT_ACTION_TOP']?> рублей" />
	</div>
</aside>