<!DOCTYPE html>
<html lang="ru">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="keywords" content="<?=$this->lang['meta']['keywords']?>" />
<meta name="description" content="<?=$this->lang['meta']['description']?>" />
<link rel="stylesheet" href="/http/css/main.css" type="text/css" />
<link rel="shortcut icon" sizes="16x16" href="/favicon.ico" />
<!--[if lte IE 9]>
    <link rel="stylesheet" type="text/css" href="/http/css/frontend/all-ie.css" />
    <script src="https://raw.githubusercontent.com/aFarkas/html5shiv/master/src/html5shiv.js"></script>
<![endif]-->
<script type="text/javascript" src="/http/js/tooltip.js"></script>
<script type="text/javascript" src="/http/js/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="/http/js/library/index.js"></script>
<?=$this->getHelper('Krugozor_Html_Title')->add('О сайте')->getHtml()?>
</head><body>

<? include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div id="<?=$this->getPageId()?>" class="content">
<? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

    <h2>О сайте</h2>

    <article id="help">
		<p>Сайт бесплатных объявлений <a href="<?=Krugozor_Registry::getInstance()->HOSTINFO['HOST_URL']?>"><?=Krugozor_Registry::getInstance()->HOSTINFO['HOST_SIMPLE']?></a> появился после того, как нами было потрачено огромное количество времени на поиск бесплатной доски объявлений, отвечающей требованиям простоты размещения информации, отсутствия обязательной регистрации на сайте, удобной и логически понятной структуры категорий, эффективности поиска любых тематических объявлений. Т.е. сайтa, позволяющего пользователю свободно ориентироваться в огромном постоянно растущем количестве предложений.</p>

		<p>Наш сайт представляет собой электронную доску объявлений, которая поделена на несколько тысяч <a href="/russia/categories/">тематических категорий</a>, согласно содержанию самых предложений. Это сайт, где каждый желающий может разместить своё объявление, а все посетители сайта — прочитать его.</p>
		<p>Для размещения объявлений доступны следующие категории:

		<?php foreach($this->categories as $category): ?>
		    <a href="/russia/categories<?=$category->getUrl()?>"><?=$category->getName()?></a>,
		<?php endforeach; ?></p>

		<p>Таким образом, на сайте бесплатных объявлений <?=Krugozor_Registry::getInstance()->HOSTINFO['HOST_SIMPLE']?> вы можете абсолютно <strong>бесплатно и без регистрации подать объявление</strong> о покупке и продаже автомобиля, можете опубликовать предложение о продаже недвижимости или избавиться от старого ноутбука. Для этого надо всего лишь нажать на ссылку  «<a href="/add.xhtml">Подать объявление</a>», заполнить форму и ждать отклика!</p>
		<p>На сайте мы постарались учесть все нюансы и негативный опыт использования досок и сайтов бесплатных объявлений и надеемся, что <?=Krugozor_Registry::getInstance()->HOSTINFO['HOST_SIMPLE']?> оправдает все ваши ожидания и превратит процесс размещения объявления из утомительного и долгого занятия в дело нескольких минут!</p>
    </article>
</div>
<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>
</body></html>