<!DOCTYPE html>
<html lang="ru">
<head>
    <?=$this->getHelper('\Krugozor\Framework\Html\Title')->add('Продается сайт объявлений')->getHtml()?>

    <!-- common meta -->
    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="<?= $this->getLang()['meta']['keywords'] ?>"/>
    <meta name="description" content="<?= $this->getLang()['meta']['description'] ?>"/>
    <meta property="og:title" content="<?= $this->getHelper('\Krugozor\Framework\Html\Title')->getTitle() ?>"/>
    <meta property="og:description" content="<?= $this->getLang()['meta']['description'] ?>"/>
    <meta property="og:image" content="/http/image/desing/snippet.jpg"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>
    <!-- common meta -->

    <!-- common css -->
    <?= $this->getCss('common', 'reset.css', false) ?>
    <?= $this->getCss('common', 'tags.css', false) ?>
    <?= $this->getCss('common', 'classes.css', false) ?>
    <?= $this->getCss('common', 'structure.css', false) ?>
    <!-- /common css -->

    <?= $this->getCss('help', 'help.css', false) ?>
</head><body>

<? include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div id="<?=$this->getPageId()?>" class="content">
    <? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

    <article id="help">
        <h2>Инвесторам. Продается движок и/или сайт объявлений ADVERTS.RU</h2>

        <p>Создание бизнеса, базирующегося на концепции бесплатных объявлений &mdash; очень выгодное вложение средств, доказанное многолетним существованием таких гигантов рынка как &laquo;Из рук в руки&raquo; или &laquo;Авито&raquo;.</p>
        <p>Продавец, срочно нуждающийся в продаже и финансовой выгоде, готов платить относительно небольшие деньги для достижения быстрого и наилучшего результата.
            Предоставление пользователю таких эксклюзивных услуг, как наивысшая доступная позиция его объявления среди равных прочих, является эффективной как для продавца,
            так и для владельца сайта бесплатных объявлений &mdash; продавец продаёт товар, владелец сайта - получает доход от предоставляемых услуг.</p>
        <p>Средняя стоимость разработки сайта объявлений &laquo;с нуля&raquo; в рядовой веб-студии будет примерно <a target="_blank" href="/http/image/desing/sale/smeta.pdf">около 3 000 000 рублей</a>, и это в лучшем случае.
            Брать готовое решение (opensource) для ведения бизнеса &mdash; не лучший вариант, т.к. придется нанимать в штат программистов,
            которые  фактически с нуля будут знакомиться с незнакомой системой. По факту, не будет человека, знающего &laquo;от и до&raquo; весь проект, его технологические особенности и архитектуру.</p>
        <p>Если вы задумались о покупке движка сайта объявлений и ищите, где купить или заказать сайт объявлений под ключ, то мы можем вам в этом посодействовать.
            Мы заинтересованы в сотрудничестве на долгосрочной основе на основе нашего решения.</p>
        <p><strong>ADVERTS</strong> &mdash; английское слово &laquo;объявления&raquo;. <strong>ADVERTS.RU</strong> &mdash; очень перспективный домен, четко дающий понять назначение ресурса.</p>
        <p>Технические характеристики:</p>
		<ul>
            <li>Сайт написан на связке <a rel="nofollow" target="_blank" href="http://php.net/">PHP 5</a>/<a rel="nofollow" target="_blank" href="https://www.mysql.com/">MySql</a>, с использованием собственной <a rel="nofollow" target="_blank" href="https://ru.wikipedia.org/wiki/ORM">ORM</a>-системы
                по методологии <a rel="nofollow" target="_blank" href="https://ru.wikipedia.org/wiki/Model-View-Controller">MVC</a>.</li>
			<li>Валидная HTML-верстка, отделенная от бизнес-логики.</li>
			<li>Есть панель администрирования.</li>
			<li>Качественный и прозрачный программный код, разделенный на доменные объекты и источники данных.</li>
			<li>Более 1500 тематических категорий, захватывающих все основные направления жизнедеятельности и бизнеса.</li>
			<li>Оптимизация шаблонов и модулей под SEO-продвижение.</li>
		</ul>
		<p></p>
		<p><strong>Цена движка текущей версии, домена и контента</strong> &mdash; 1 000 000 рублей.<br />
		<strong>Цена движка текущей версии</strong> (без домена и контента) &mdash; 100 000 рублей.</p>
        <p>Владельцы проекта готовы к иным формам взаимодействия.</p>
		<p>Для связи звоните по номеру: +7-926 [три]5[ноль]-01-2[четыре]</p>

		<p style="text-align:center"><img style="outline:1px solid #666" src="/http/image/desing/sale/sale.jpg"></p>
		<p style="text-align:center"><img style="outline:1px solid #666" src="/http/image/desing/sale/sale1.jpg"></p>
		<p style="text-align:center"><img style="outline:1px solid #666" src="/http/image/desing/sale/sale2.jpg"></p>
		<p style="text-align:center"><img style="outline:1px solid #666" src="/http/image/desing/sale/sale3.jpg"></p>
		<p style="text-align:center"><img style="outline:1px solid #666" src="/http/image/desing/sale/sale4.jpg"></p>
		<p style="text-align:center"><img style="outline:1px solid #666" src="/http/image/desing/sale/sale5.jpg"></p>
    </article>
</div>
<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>
</body></html>