<!DOCTYPE html>
<html lang="ru">
<head>
    <?=$this->getHelper('\Krugozor\Framework\Html\Title')->add('Выделение объявлений бесплатно')->getHtml()?>

    <!-- common meta -->
    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="<?= $this->getLang()['meta']['keywords'] ?>"/>
    <meta name="description" content="<?= $this->getLang()['meta']['description'] ?>"/>
    <meta property="og:title" content="<?= $this->getHelper('\Krugozor\Framework\Html\Title')->getTitle() ?>"/>
    <meta property="og:description" content="<?= $this->getLang()['meta']['description'] ?>"/>
    <meta property="og:image" content="/http/image/desing/snippet.jpg"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>
    <!-- common meta -->

    <!-- common css -->
    <?= $this->getCss('common', 'reset.css', false) ?>
    <?= $this->getCss('common', 'tags.css', false) ?>
    <?= $this->getCss('common', 'classes.css', false) ?>
    <?= $this->getCss('common', 'structure.css', false) ?>
    <!-- /common css -->

    <?= $this->getCss('help', 'help.css', false) ?>
    <?= $this->getCss() ?>
</head><body>

<? include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div id="<?=$this->getPageId()?>" class="content">
    <?php include $this->getRealTemplatePath('Common/FrontendNotification') ?>

	<article id="help">
        <h2>Присвоение VIP-статуса вашим объявлениям</h2>

        <p>Если у вас есть аккаунт в какой-либо соцсети (Вконтакте, Одноклассники, Mail.ru и т.п.), вы можете <b>совершенно бесплатно</b> повысить эффективность Вашего объявления путем присвоения объявлению VIP-статуса.
            Объявление будет до 14 дней находиться всегда в самых первых позициях в своей и родительских рубриках каталога, будет выделено особым цветом:</p>

        <div class="image">
            <img src="/http/image/desing/vip.jpg" alt="">
        </div>

        <p>Для этого нажмите «поделиться ссылкой» на странице вашего объявления:</p>

        <div class="image">
            <img src="/http/image/desing/vipfree.jpg" alt="">
        </div>

        <p>...и <b>пришлите адрес вашей страницы в соцсети</b> для проверки наличия ссылки на наш сайт:</p>

        <form method="post" action="<?=$this->getRequest()->getCanonicalRequestUri()->getEscapeUriValue()?>">
            <fieldset><legend>Отослать ссылку для проверки</legend>
                <div class="field_row">
                    <label for="url">URL-адрес вашей страницы в соцсети<br />с размещённой ссылкой на ваше объявление на
                        <?=\Krugozor\Framework\Registry::getInstance()->HOSTINFO['HOST_SIMPLE']?>:</label>
                    <div class="group">
                        <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputUrl(
                            'url', '',
                            ['maxlength' => \Krugozor\Framework\Validator\StringLength::VARCHAR_MAX_LENGTH,
                             'id' => 'url',
                             'autocomplete' => 'off']
                            )->getHtml()?>
                        <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['url'])?>
                    </div>
                </div>
                <div class="field_row_fake">
                    <div></div>
                    <div class="group">
                        <?=$this->getHelper('\Krugozor\Framework\Helper\Form')->inputSubmit('submit', 'Отослать для проверки')->getHtml()?>
                    </div>
                </div>
                <p>Внимание!</p>
                <p>Ваша страница в соцсети должна быть доступна всему интернету (т.е. должна быть не закрыта настройками приватности).<br />
                Если наш робот не найдёт обратную ссылку на <?=\Krugozor\Framework\Registry::getInstance()->HOSTINFO['HOST_SIMPLE']?>,
                    то объявление будет автоматически снято c линейки VIP-объявлений!</p>
            </fieldset>
        </form>
	</article>

</div>

<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>

</body></html>