<!DOCTYPE html>
<html lang="ru">
<head>

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="keywords" content="<?=$this->lang['meta']['keywords']?>" />
<meta name="description" content="<?=$this->lang['meta']['description']?>" />
<link rel="shortcut icon" sizes="16x16" href="/favicon.ico" />

<?=$this->getHelper('Krugozor_Html_Title')->add('Выделение объявлений бесплатно')->getHtml()?>

<?=$this->getCss('/http/css/main.css', false)?>

</head><body>

<? include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div id="<?=$this->getPageId()?>" class="content">
    <? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

    <h2>Присвоение VIP-статуса вашим объявлениям</h2>

	<article>
        <h3>Вы можете <b>совершенно бесплатно</b> повысить эффективность Вашего объявления путем присвоения объявлению VIP-статуса.</h3>
        <p>Объявление будет до 14 дней находиться всегда в самых первых позициях в своей и родительских рубриках каталога, будет выделено особым цветом:</p>
        <div class="paragraph">
            <div class="center">
                <img src="/http/image/desing/vip.jpg" alt="">
            </div>
        </div>
        <p>Для этого нажмите «поделиться ссылкой» на странице вашего объявления...</p>
        <div class="paragraph">
            <div class="center">
                <img src="/http/image/desing/vipfree.jpg" alt="">
            </div>
        </div>
        <p>...и <b>пришлите адрес вашей страницы в соцсети</b> для проверки наличия ссылки на наш сайт:</p>

        <form method="post" action="<?=$this->getRequest()->getUri()->getEscapeUriValue()?>">
            <fieldset><legend>Отослать ссылку для проверки</legend>
                <div class="field_row">
                    <label for="url">URL-адрес вашей страницы в соцсети<br />с размещённой ссылкой на объявление:</label>
                    <div class="group">
                        <?=$this->getHelper('Krugozor_Helper_Form')->inputUrl(
                            'url', '',
                            ['maxlength' => Krugozor_Validator_StringLength::VARCHAR_MAX_LENGTH,
                             'id' => 'url',
                             'autocomplete' => 'off']
                            )->getHtml()?>
                        <?=$this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['url'])?>
                    </div>
                </div>
                <div class="field_row_fake">
                    <div></div>
                    <div class="group">
                        <?=$this->getHelper('Krugozor_Helper_Form')->inputSubmit('submit', 'Отослать для проверки')->getHtml()?>
                    </div>
                </div>
                <p>Внимание!</p>
                <p>Ваша страница в соцсети должна быть доступна всему интернету (т.е. должна быть не закрыта настройками приватности).<br />
                Если наш робот не найдёт обратную ссылку на <?=Krugozor_Registry::getInstance()->HOSTINFO['HOST_SIMPLE']?>, то объявление будет автоматически снято c линейки VIP-объявлений!</p>
            </fieldset>
        </form>
	</article>

</div>

<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>

</body></html>