<aside id="payment_popup" class="payment_popup">
    <div class="bheader add_star_header_icon">
        Хотите привлечь больше внимание на своё объявление и повысить его эффективность?
    </div>
    <p class="description_strong">
        Всего <span class="price">за <?=Krugozor_Registry::getInstance()->PAYMENTS['PAYMENT_ACTION_TOP']?> рублей</span>
        вы можете сделать ваше объявление более заметным &mdash; объявление будет выделено особым цветом,
        будет находиться выше других бесплатных объявлений, соответственно его увидят больше посетителей сайта:
    </p>
    <div class="center">
        <img src="/http/image/desing/vip.jpg" alt="">
    </div>
    <div class="center submit_block">
        <input type="button" value="Выделить объявление и разместить в VIP-линейке" />
    </div>
</aside>

<aside id="special_popup" class="payment_popup">
    <div class="bheader add_star_header_icon">
        Хотите привлечь больше внимание на своё объявление и повысить его эффективность?
    </div>
    <p class="description_strong">
        Всего <span class="price">за <?=Krugozor_Registry::getInstance()->PAYMENTS['PAYMENT_ACTION_SPECIAL']?> рублей</span>
        вы можете сделать ваше объявление более заметным, разместив его в блоке &laquo;Спецпредложений&raquo; &mdash; объявление будет
        отображаться на всех основных страницах в увеличенных пропорциях, максимально привлекая внимание посетителей сайта:
    </p>
    <div class="center"><img src="/http/image/desing/special.jpg" alt=""></div>
    <div class="center submit_block">
        <input type="button" value="Разместить объявление в &laquo;Спецпредложении&raquo;" />
    </div>
</aside>