<!DOCTYPE html>
<html lang="ru">
<head>

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" sizes="16x16" href="/favicon.ico" />

<?=$this->getHelper('Krugozor_Html_Title')->getHtml()?>

<?=$this->getCss('/http/css/main.css', false)?>
<?=$this->getPathToCssModule(true)?>

</head><body>

<?php include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div id="page404_404" class="content">
	<h2><?=$this->lang['content']['document_not_found_header']?></h2>
	<?=$this->lang['content']['document_not_found_body']?>
</div>

<?php require_once $this->getRealTemplatePath('Common/FrontendBottom'); ?>

</body></html>