<!DOCTYPE html>
<html lang="ru">
<head>

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="keywords" content="<?=$this->lang['meta']['keywords']?>" />
<meta name="description" content="<?=$this->lang['meta']['description']?>" />
<link rel="shortcut icon" sizes="16x16" href="/favicon.ico" />

<?=$this->getHelper('Krugozor_Html_Title')->getHtml()?>

<?=$this->getCss('/http/css/main.css', false)?>

<?=$this->getJs('/http/js/tooltip.js', false)?>
<?=$this->getJs('/http/js/jquery-1.11.1.min.js', false)?>
<?=$this->getJs('/http/js/library/index.js', false)?>

</head><body>

    <? include $this->getRealTemplatePath('Common/FrontendTop') ?>

    <div class="content">
        <h2><?=$this->getHelper('Krugozor_Html_Title')->getByIndex(1)?></h2>

        <? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

        <?=$this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['common_error'])?>
    </div>

    <? include $this->getRealTemplatePath('Common/FrontendBottom') ?>

</body></html>