<!DOCTYPE html>
<html lang="ru">
<head>

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="keywords" content="<?=$this->lang['meta']['keywords']?>" />
<meta name="description" content="<?=$this->lang['meta']['description']?>" />
<link rel="shortcut icon" sizes="16x16" href="/favicon.ico" />

<?=$this->getHelper('Krugozor_Html_Title')->getHtml()?>

<?=$this->getCss('/http/css/main.css', false)?>
<?=$this->getPathToCssModule(true)?>

<?=$this->getJs('/http/js/tooltip.js', false)?>
<?=$this->getJs('/http/js/jquery-1.11.1.min.js', false)?>
<?=$this->getJs('/http/js/library/index.js', false)?>

</head><body>

<? include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div id="<?=$this->getPageId()?>" class="content">

<h2><?=$this->getHelper('Krugozor_Html_Title')->getByIndex(1)?></h2>

<? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

<form method="post" action="<?=$this->getRequest()->getUri()->getEscapeUriValue()?>">
	<fieldset>
	    <legend>Идентификация пользователя</legend>

	    <div class="two_column">
			<div class="left_column">
				<div class="left_column_content">
					Если Вы забыли свой логин или пароль, введите какие-либо одни ваши данные, которые Вы указали при регистрации &mdash; логин или email-адрес и нажмите на кнопку &laquo;выслать код подтверждения&raquo;. Если при регистрации в системе Вы указали свой email-адрес, то на него придет письмо с уникальной ссылкой. Пройдя по этой ссылке, Вы подтвердите свою принадлежность к указанному аккаунту и новый пароль будет выслан на Ваш регистрационный почтовый ящик.
				</div>
			</div>
	    	<div class="right_column">
	    		<div class="right_column_content">
					<?php if ($this->err && $this->err['common_error']->count()): ?>
					<div class="field_row_fake">
						<div></div>
						<div class="group">
							<?=$this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['common_error'])?>
						</div>
					</div>
					<?php endif; ?>

	    			<div class="field_row">
				    	<label class="compulsory" for="user_login">Ваш логин:</label>
	    				<div class="group">
				    		<?=$this->getHelper('Krugozor_Helper_Form')->inputText('user[login]', $this->user_login, array('maxlength'=>255, 'id'=>'user_login', 'title'=>'Введите логин Вашего аккаунта'))->getHtml()?> или
						    <?=$this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['user_login'])?>
						</div>
					</div>
					<div class="field_row">
						<label class="compulsory" for="user_email">Ваш email:</label>
						<div class="group">
							<?=$this->getHelper('Krugozor_Helper_Form')->inputEmail('user[email]', $this->user_email, array('maxlength'=>255, 'id'=>'user_email', 'title'=>'Введите email-адрес Вашего аккаунта'))->getHtml()?>
							<?=$this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['user_email'])?>
						</div>
					</div>
				</div>
	    	</div>
	    </div>
	</fieldset>

	<div class="submit_block">
	    <?=$this->getHelper('Krugozor_Helper_Form')->inputSubmit('submit', 'Выслать код подтверждения')->getHtml()?>
	</div>
</form>

</div>
<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>
</body></html>