<!DOCTYPE html>
<html lang="ru">
<head>

    <!-- common meta -->
    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="<?= $this->getLang()['meta']['keywords'] ?>"/>
    <meta name="description" content="<?= $this->getLang()['meta']['description'] ?>"/>
    <meta property="og:title" content="<?= $this->getHelper('\Krugozor\Framework\Html\Title')->getTitle() ?>"/>
    <meta property="og:description" content="<?= $this->getLang()['meta']['description'] ?>"/>
    <meta property="og:image" content="/http/image/desing/snippet.jpg"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>
    <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getHtml() ?>
    <!-- common meta -->

    <!-- common css -->
    <?= $this->getCss('common', 'reset.css', false) ?>
    <?= $this->getCss('common', 'tags.css', false) ?>
    <?= $this->getCss('common', 'classes.css', false) ?>
    <?= $this->getCss('common', 'structure.css', false) ?>
    <!-- /common css -->

</head>
<body>

<? include $this->getRealTemplatePath('Local/FrontendTop') ?>

<div class="content">
    <h2><?= $this->getHelper('\Krugozor\Framework\Html\Title')->getByIndex(1) ?></h2>

    <? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['common_error']) ?>
</div>

<? include $this->getRealTemplatePath('Local/FrontendBottom') ?>

</body>
</html>