<!DOCTYPE html>
<html lang="ru">
<head>

    <!-- common meta -->
    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="<?= $this->getLang()['meta']['keywords'] ?>"/>
    <meta name="description" content="<?= $this->getLang()['meta']['description'] ?>"/>
    <meta property="og:title" content="<?= $this->getHelper('\Krugozor\Framework\Html\Title')->getTitle() ?>"/>
    <meta property="og:description" content="<?= $this->getLang()['meta']['description'] ?>"/>
    <meta property="og:image" content="/img/local/snippet.jpg"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>
    <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getHtml() ?>
    <!-- common meta -->

    <!-- common css -->
    <?= $this->getCss('common', 'reset.css', false) ?>
    <?= $this->getCss('common', 'tags.css', false) ?>
    <?= $this->getCss('common', 'classes.css', false) ?>
    <?= $this->getCss('common', 'structure.css', false) ?>
    <!-- /common css -->

    <?= $this->getCss() ?>

    <!-- common js -->
    <?= $this->getJs('common', 'library/krugozor.js') ?>
    <?= $this->getJs('common', 'library/krugozor.forms.js') ?>
    <?= $this->getJs('common', 'library/krugozor.ajax.js') ?>
    <!-- /common js -->

    <?= $this->getJs('common', 'tooltip.js') ?>
    <?= $this->getJs('common', 'jquery/jquery-1.11.1.min.js') ?>

</head>
<body>

<? include $this->getRealTemplatePath('Local/FrontendTop') ?>

<div id="<?= $this->getPageId() ?>" class="content">

    <h2><?= $this->getHelper('\Krugozor\Framework\Html\Title')->getByIndex(1) ?></h2>

    <? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

    <form method="post" action="<?= $this->getRequest()->getCanonicalRequestUri()->getEscapeUriValue() ?>">
        <fieldset>
            <legend>Идентификация пользователя</legend>

            <div class="two_column">
                <div class="left_column">
                    <div class="left_column_content">
                        Если Вы забыли свой логин или пароль, введите какие-либо одни ваши данные, которые Вы указали
                        при регистрации &mdash; логин или email-адрес и нажмите на кнопку &laquo;выслать код
                        подтверждения&raquo;. Если при регистрации в системе Вы указали свой email-адрес, то на него
                        придет письмо с уникальной ссылкой. Пройдя по этой ссылке, Вы подтвердите свою принадлежность к
                        указанному аккаунту и новый пароль будет выслан на Ваш регистрационный почтовый ящик.
                    </div>
                </div>
                <div class="right_column">
                    <div class="right_column_content">
                        <div class="table">
                            <?php if ($this->err && $this->err['common_error']->count()): ?>
                                <div class="field_row_fake">
                                    <div></div>
                                    <div class="group">
                                        <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['common_error']) ?>
                                    </div>
                                </div>
                            <?php endif; ?>

                            <div class="field_row">
                                <label class="compulsory" for="user_login">Ваш логин:</label>
                                <div class="group">
                                    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText(
                                        'user[login]',
                                        $this->user_login,
                                        array('maxlength' => 255, 'id' => 'user_login', 'title' => 'Введите логин Вашего аккаунта')
                                    )->getHtml() ?>
                                    <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['user_login']) ?>
                                </div>
                            </div>

                            <div class="field_row_fake">
                                <div></div>
                                <div class="group">или</div>
                            </div>

                            <div class="field_row">
                            <label class="compulsory" for="user_email">Ваш email:</label>
                            <div class="group">
                                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputEmail(
                                    'user[email]',
                                    $this->user_email,
                                    array('maxlength' => 255, 'id' => 'user_email', 'title' => 'Введите email-адрес Вашего аккаунта')
                                )->getHtml() ?>
                                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['user_email']) ?>
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>

        <div class="submit_block">
            <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputSubmit(
                'submit',
                'Выслать код подтверждения'
            )->getHtml() ?>
        </div>
    </form>

</div>

<? include $this->getRealTemplatePath('Local/FrontendBottom') ?>

</body>
</html>