<aside id="payment_popup" class="payment_popup">
	<div class="bheader add_star_header_icon">Хотите привлечь больше внимание на своё объявление и повысить его эффективность?</div>
	<p class="description_strong">Всего <span class="price">за <?=Krugozor_Registry::getInstance()->PAYMENTS['PAYMENT_ACTION_TOP']?> рублей</span> вы можете сделать ваше объявление более заметным &mdash; объявление будет выделено особым цветом, будет находиться выше других бесплатных объявлений, соответственно его увидят больше посетителей сайта:</p>
	<div class="center"><img src="/http/image/desing/vip.jpg" alt=""></div>
	<div class="center">
		<div class="formL">
    		<div>
    			<a id="payment_button" href="http://auth.robokassa.ru/Merchant/Index.aspx" target="_top">оплатить</a>
    			<img alt="robokassa" src="https://auth.robokassa.ru/Merchant/PaymentForm/Images/logo-xl.png" />
    		</div>
        </div>
	</div>
</aside>