<!DOCTYPE html>
<html lang="ru">
<head>

    <!-- common meta -->
    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>
    <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getHtml() ?>
    <!-- /common meta -->

    <!-- common css -->
    <?= $this->getCss('local', 'reset.css') ?>
    <?= $this->getCss('local', 'tags.css') ?>
    <?= $this->getCss('local', 'backend.css') ?>
    <!-- /common css -->
    <?= $this->getCss() ?>

</head>
<body>

<? include $this->getRealTemplatePath('Local/BackendNotification') ?>
<? include $this->getRealTemplatePath('Local/BackendMenu') ?>

<table class="datatable menu">
    <tr>
        <td>
            <a class="add_element" href="/group/backend-edit/">
                <?= $this->getLang()['content']['adding_group'] ?>
            </a>
        </td>
    </tr>
</table>

<table class="datatable">
    <? if ($this->groupList->getList()->count()): ?>
        <colgroup>
            <col><col><col><col><col>
        </colgroup>
        <tr>
            <th colspan="5"><?= $this->getLang()['content']['list_of_groups'] ?></th>
        </tr>
        <tr>
            <td>
                <?php
                $linker = $this->getHelper('\Krugozor\Framework\Helper\SortLink')
                    ->setFieldName('id')
                    ->setAnchor($this->getLang()['content']['id'])
                    ->setUrl($this->getRequest()->getCanonicalRequestUri()->getEscapeUriValue())
                    ->setIconSrc('/img/local/system/icon/')
                    ->setCurrentFieldName($this->groupList->getAlias())
                    ->setCurrentSortOrder($this->groupList->getOrder())
                    ->setQueryStringFromArray(array(
                        'sep' => $this->groupList->getPagination()->getCurrentSeparator(),
                        'page' => $this->groupList->getPagination()->getCurrentPage(),
                    ));

                echo $linker->getHtml();
                ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('name')
                    ->setAnchor($this->getLang()['content']['group_name'])
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('active')
                    ->setAnchor($this->getLang()['content']['group_active'])
                    ->getHtml(); ?>
            </td>
            <td colspan="2"><?= $this->getLang()['content']['actions'] ?></td>
        </tr>

        <? foreach ($this->groupList->getList() as $group): ?>
            <tr>
                <td class="center"><?= $group->getId() ?></td>
                <td><?= $this->getHelper('\Krugozor\Framework\Helper\Format')->run($group->getName(), 'decode', 'hsc') ?></td>
                <td class="center<? if (!$group->getActive()): ?> lighttext"<?php endif; ?>>
                    <span>
                        <? if ($group->getActive()): ?>
                            <?= $this->getLang()['content']['yes'] ?>
                        <? else: ?>
                            <?= $this->getLang()['content']['no'] ?>
                        <? endif; ?>
                    </span>
                </td>
                <td class="td_actions">
                    <a href="/group/backend-edit/?id=<?= $group->getId() ?>">
                        <img src="/img/local/system/icon/edit.png"
                             alt=""/>
                    </a>
                </td>
                <td class="td_actions">
                    <? if (!in_array($group->getAlias(), ['administrator', 'user', 'guest'])): ?>
                        <?php
                        $str = \Krugozor\Framework\Helper\Format::js(
                            $this->getLang()['content']['question_delete_group'],
                            ['group_name' => $group->getName()]
                        );
                        ?>
                        <a onclick="return confirm('<?= $str ?>')"
                           href="/group/backend-delete/?id=<?= $group->getId() ?>&amp;referer=<?= $this->getRequest()->getRequestUri()->getUrlencodeUriValue(true) ?>">
                            <img src="/img/local/system/icon/delete.png"
                                 alt=""/>
                        </a>
                    <? else: ?>
                        <img src="/img/local/system/icon/delete_empty.png"
                             alt=""/>
                    <? endif; ?>
                </td>
            </tr>
        <? endforeach; ?>
    <? else: ?>
        <tr>
            <th><?= $this->getLang()['content']['list_of_groups'] ?></th>
        </tr>
        <tr class="center">
            <td><?= $this->getLang()['content']['empty_list_of_groups'] ?></td>
        </tr>
    <? endif; ?>
</table>

<?php
$pagination = $this->groupList->getPagination();
$pagination
    ->getHelper()
    ->setCssNormalLinkClass('navigation_normal_link')
    ->setRequestUriParameter('field_name', $this->groupList->getAlias())
    ->setRequestUriParameter('sort_order', $this->groupList->getOrder());
?>

<? include $this->getRealTemplatePath('Local/BackendNavigation') ?>
<? include $this->getRealTemplatePath('Local/DebugInfo') ?>

</body>
</html>