<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <?= $this->getHelper('Krugozor_Html_Title')->getHtml() ?>
    <?= $this->getCss('/http/css/tags.css', true) ?>
    <?= $this->getCss('/http/css/backend.css', true) ?>
    <?= $this->getPathToCssModule() ?>
    <?= $this->getJs('/http/js/library/index.js', true); ?>
</head>
<body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>
<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<form method="post" onsubmit="if (window.cform) return cform.checkTextFieldsOnEmpty();"
      action="<?= $this->getRequest()->getRequestUri()->getEscapeUriValue() ?>">

    <table class="datatable edit">
        <colgroup>
            <col/>
            <col/>
        </colgroup>
        <tr>
            <th colspan="2">
                <? if ($this->group->getId()): ?>
                    <?= $this->getLang()['content']['editing_the_group'] ?> &laquo;<?= $this->getHelper('Krugozor_Helper_Format')->run($this->group->getName(), 'decode', 'hsc'); ?>&raquo;
                <? else: ?>
                    <?= $this->getLang()['content']['adding_group'] ?>
                <? endif; ?>
            </th>
        </tr>
        <tr>
            <td class="compulsory"><?= $this->getLang()['content']['group_name'] ?>:</td>
            <td><?= $this->getHelper('Krugozor_Helper_Form')->inputText('group[name]', $this->group->getName(), array('maxlength' => 255, 'class' => 'textLarge'))->getHtml() ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['name']) ?></td>
        </tr>
        <tr>
            <td class="compulsory"><?= $this->getLang()['content']['group_alias'] ?>:</td>
            <td><?= $this->getHelper('Krugozor_Helper_Form')->inputText('group[alias]', $this->group->getAlias(), array('maxlength' => 30, 'class' => 'textLarge'))->getHtml() ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['alias']) ?></td>
        </tr>
        <tr>
            <td class="compulsory"><?= $this->getLang()['content']['group_active'] ?>:</td>
            <td>
                <?
                $select = $this->getHelper('Krugozor_Helper_Form')->inputSelect('group[active]', $this->group->getActive());
                $select->addOption($this->getHelper('Krugozor_Helper_Form')->inputOption(1, $this->getLang()['content']['yes']));
                $select->addOption($this->getHelper('Krugozor_Helper_Form')->inputOption(0, $this->getLang()['content']['no']));
                echo $select->getHtml();
                ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['active']) ?>
            </td>
        </tr>
        <tr>
            <td class="compulsory"><?= $this->getLang()['content']['group_accesss'] ?>:</td>
            <td>
                <? foreach ($this->modules as $module): ?>

                    <fieldset>
                        <legend><?= $module->getName() ?></legend>

                        <? if ($module->getControllers()->count()): ?>
                            <div>
                                <? foreach ($module->getControllers() as $controller): ?>
                                    <div>
                                        <?php
                                        $access = $this->group->getDenormalizedAccesses()->checkAccess($module->getKey(), $controller->getKey());
                                        $label = 'label_' . $module->getId() . '_' . $controller->getId();
                                        ?>
                                        <?= $this->getHelper('Krugozor_Helper_Form')->inputFullCheckbox('group[accesses][' . $module->getId() . '][' . $controller->getId() . ']', 1, 0, $access, array('id' => $label)) ?>
                                        <?= $this->getHelper('Krugozor_Helper_Form')->Label($controller->getName(), $label)->getHtml() ?>
                                    </div>
                                <? endforeach; ?>
                            </div>
                        <? endif; ?>
                    </fieldset>

                <? endforeach; ?>
            </td>
        </tr>
        <tr align="center">
            <td colspan="2">
                <?= $this->getHelper('Krugozor_Helper_Form')->inputHidden('group[id]', $this->group->getId())->getHtml() ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->inputSubmit('submit', $this->getLang()['content']['save_changes'])->getHtml() ?>
                &nbsp;&nbsp;&nbsp;
                <?= $this->getHelper('Krugozor_Helper_Form')->inputFullCheckbox('return_on_page', 1, 0, $this->return_on_page, array('id' => 'label_return_on_page')) ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->Label($this->getLang()['content']['return_to_this_page'], 'label_return_on_page')->getHtml() ?>
            </td>
        </tr>
    </table>

</form>

<script type="text/javascript">
    try {
        var cform = new Krugozor.Forms.Checker(document.forms[0]);
        cform.putFocus();
    } catch (e) {
    }
</script>

<? include $this->getRealTemplatePath('Common/DebugInfo') ?>

</body>
</html>