<!DOCTYPE html>
<html lang="ru">
<head>

    <!-- common meta -->
    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>
    <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getHtml() ?>
    <!-- /common meta -->

    <!-- common css -->
    <?= $this->getCss('common', 'reset.css') ?>
    <?= $this->getCss('common', 'tags.css') ?>
    <?= $this->getCss('common', 'backend.css') ?>
    <!-- /common css -->
    <?= $this->getCss() ?>

</head>
<body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>
<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<table class="datatable">
    <tr>
        <td>
            <a class="add_element" href="/category/backend-edit/">Добавление категории</a>
        </td>
    </tr>
</table>

<table class="datatable">
    <? if ($this->categories): ?>
        <colgroup>
            <col><col><col><col><col>
            <col><col><col><col>
        </colgroup>
        <tr>
            <th colspan="10">Список категорий</th>
        </tr>
        <tr class="head_params">
            <td>ID</td>
            <td>Платная категория</td>
            <td>Имя категории</td>
            <td colspan="6"><?= $this->lang['content']['actions'] ?></td>
        </tr>
        <?= $this->getHelper('\Krugozor\Framework\Module\Category\Helper\TreeBackendTable', $this->categories, $this)->getHtml() ?>
    <? else: ?>
        <tr>
            <th>Список категорий</th>
        </tr>
        <tr class="center">
            <td>
                <?= $this->lang['content']['not_found_request_data'] ?>
            </td>
        </tr>
    <? endif; ?>
</table>

</body>
</html>