<!DOCTYPE html>
<html lang="ru">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />

<?=$this->getHelper('Krugozor_Html_Title')->getHtml()?>

<?=$this->getCss('/http/css/reset.css', false)?>
<?=$this->getCss('/http/css/tags.css', true)?>
<?=$this->getCss('/http/css/backend.css', true)?>

<?=$this->getJs('/http/js/library/index.js', true)?>
<?=$this->getJs('/http/js/library/krugozor.ui.popup.ajaxselect.js', true)?>
<?=$this->getPathToJsModule()?>

</head><body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>
<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<form method="post" action="<?=$this->getRequest()->getRequestUri()->getEscapeUriValue()?>">
    <table class="datatable edit">
        <colgroup>
            <col />
            <col />
        </colgroup>
        <tr>
            <th colspan="2">Добавление списка категорий</th>
        </tr>
        <tr>
            <td class="compulsory">Родительский узел:</td>
            <td>
            <?php
                $select = $this->getHelper('Krugozor_Helper_Form')->inputSelect('data[category]', $this->getRequest()->getRequest('pid', 'decimal'));
                $select->addOption( $this->getHelper('Krugozor_Helper_Form')->inputOption('0', 'Выберите') );
                $categories = $this->getHelper('Krugozor_Module_Category_Helper_BackendSelect', $this->tree)->getHtml();
                foreach ($categories as $option):
                    $select->addOption($option);
                endforeach;
                echo $select->getHtml();
            ?>
            </td>
        </tr>
        <tr>
            <td class="compulsory">Список категорий:</td>
            <td><?=$this->getHelper('Krugozor_Helper_Form')->inputTextarea('data[list]', '')->getHtml()?></td>
        </tr>
        <tr align="center">
            <td colspan="2">
            <?=$this->getHelper('Krugozor_Helper_Form')->inputHidden('data[id]', $this->getRequest()->getRequest('id', 'decimal'))->getHtml()?>
            <?=$this->getHelper('Krugozor_Helper_Form')->inputSubmit('submit', $this->lang['content']['save_changes'])->getHtml()?>
            </td>
        </tr>
    </table>
</form>

</body></html>