<!DOCTYPE html>
<html lang="ru">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />

<?=$this->getHelper('Krugozor_Html_Title')->getHtml()?>

<?=$this->getCss('/http/css/reset.css', false)?>
<?=$this->getCss('/http/css/tags.css', true)?>
<?=$this->getCss('/http/css/backend.css', true)?>

</head><body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>
<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<table class="datatable">
    <tr>
        <td>
            <a class="add_element" href="/category/backend-edit/">Добавление категории</a>
        </td>
    </tr>
</table>

<table class="datatable">
    <? if ($this->categories): ?>
        <colgroup>
            <col width="5%" />
            <col width="5%" />
            <col width="60%" />
            <col width="5%" />
            <col width="5%" />
            <col width="5%" />
            <col width="5%" />
            <col width="5%" />
            <col width="5%" />
        </colgroup>
        <tr>
            <th colspan="10">Список категорий</th>
        </tr>
        <tr class="head_params">
            <td>ID</td>
            <td>Платная категория</td>
            <td>Имя категории</td>
            <td colspan="6"><?=$this->lang['content']['actions']?></td>
        </tr>
        <?=$this->getHelper('Krugozor_Module_Category_Helper_TreeBackendTable', $this->categories, $this)->getHtml()?>
    <? else: ?>
        <tr>
            <th>Список категорий</th>
        </tr>
        <tr class="center">
            <td>
                <?=$this->lang['content']['not_found_request_data']?>
            </td>
        </tr>
    <? endif; ?>
</table>

</body></html>