<!DOCTYPE html>
<html lang="ru">
<head>

    <!-- common meta -->
    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="<?= $this->getLang()['meta']['keywords'] ?>"/>
    <meta name="description" content="<?= $this->getLang()['meta']['description'] ?>"/>
    <meta property="og:title" content="<?= $this->getHelper('\Krugozor\Framework\Html\Title')->getTitle() ?>"/>
    <meta property="og:description" content="<?= $this->getLang()['meta']['description'] ?>"/>
    <meta property="og:image" content="/img/local/snippet.jpg"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>
    <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getHtml() ?>
    <!-- /common meta -->

    <!-- common css -->
    <?= $this->getCss('common', 'reset.css', false) ?>
    <?= $this->getCss('common', 'tags.css', false) ?>
    <?= $this->getCss('common', 'classes.css', false) ?>
    <?= $this->getCss('common', 'structure.css', false) ?>
    <!-- /common css -->
    <?= $this->getCss('advert', '_adverts-list.css', true) ?>
    <?= $this->getCss() ?>

    <?= $this->getJs('common', 'library/krugozor.js') ?>
    <?= $this->getJs('common', 'tooltip.js') ?>
    <?= $this->getJs('common', 'jquery/jquery-1.11.1.min.js') ?>
    <?= $this->getJs('advert', '_adverts-list.js') ?>

</head><body>

<? include $this->getRealTemplatePath('Local/FrontendTop') ?>

<div id="<?=$this->getPageId()?>" class="content">

    <?php if ($this->pagination->getCurrentPage() == 1): ?>
    <div class="category_text">
        <h1>
            <?php $i = 1; foreach ($this->territories as $territory): ?>
                <?php if ($i != 1): ?>/<?php endif; ?>
                <?php if ($this->territories->count() > $i): ?>
                    <a href="<?=$territory->getUrl()?>/categories/"><? if($i==1): ?>Объявления <? endif; ?><?=$territory->getNameRu()?></a>
                <?php endif;?>
            <?php $i++; endforeach; ?>

        Доска бесплатных объявлений <?=$this->territories->getLast()->getNameRu3()?></h1>
        <p><strong>Добро пожаловать на сайт бесплатных объявлений <?=$this->territories->getLast()->getNameRu3()?></strong>!
            Наш сайт является одним из лидирующих сайтов объявлений в <?=$this->territories->getLast()->getNameRu2()?><?php if ($this->territories->city): ?> (<?=$this->territories->region->getNameRu2()?>)<?php endif; ?>,
            на котором вы всегда найдете самые актуальные объявления от частных лиц и организаций.
            Наша доска объявлений представлена в виде иерархического каталога товаров и услуг с множеством категорий (более 1500), охватывающих все основные направления бизнеса, услуг и частной купли-продажи товаров.<br />

            <strong>Купить или продать недвижимость в <?=$this->territories->getLast()->getNameRu2()?></strong>, снять квартиру или комнату,
            <strong>купить или продать в <?=$this->territories->getLast()->getNameRu2()?> автомобиль</strong>, бытовую технику, мебель, детские товары,
            отдать щенка в добрые руки, <strong>подать объявление о предоставлении услуг в <?=$this->territories->getLast()->getNameRu2()?></strong>, найти в <?=$this->territories->getLast()->getNameRu2()?> работу
            или <a href="/advert/frontend-edit-advert/?country=<?php if ($this->territories->country): ?><?=$this->territories->country->getId()?><?php endif; ?>&region=<? if ($this->territories->region): ?><?=$this->territories->region->getId()?><?php endif; ?>&city=<? if ($this->territories->city): ?><?=$this->territories->city->getId()?><?php endif; ?>">подать объявление в <?=$this->territories->getLast()->getNameRu2()?>
            бесплатно и без регистрации</a> &mdash; всё это можно сделать на нашем сайте!<br>

            Все объявления размещаются абсолютно бесплатно, разместить объявление может как физическое, так и юридическое лицо. Ограничений на количество объявлений нет.
        </p>
    </div>
    <?php else: ?>
        <h2>
            <?php $i = 1; foreach ($this->territories as $territory): ?>
                <?php if ($i != 1): ?>/<?php endif; ?>
                <?php if ($this->territories->count() > $i): ?>
                    <a href="<?=$territory->getUrl()?>/categories/"><? if($i==1): ?>Объявления <? endif; ?><?=$territory->getNameRu()?></a>
                <?php else: ?>
                    <? if($i==1): ?>Объявления <? endif; ?><?=$territory->getNameRu()?>
                <?php endif;?>
                <?php $i++; endforeach; ?>
        </h2>
    <?php endif; ?>

	<? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

	<?php if ($this->categories && $this->categories->count()): ?>
    <div class="subcategories categories_list">
        <?=$this->getHelper('\Krugozor\Framework\Module\Category\Helper\Subcategories', $this->categories, $this->territories->getLast()->getUrl() . '/categories')->getHtml()?>
    </div>
	<?php endif; ?>

    <?php if($this->adverts && $this->adverts->count()): ?>

        <div class="three_column three_column_wrap">
            <!--<div class="left_column">
                <div class="left_column_content">

                </div>
            </div>-->
            <div class="center_column">
                <div class="center_column_content">
                    <div class="bheader">Последние добавленные на сайт объявления<?php if ($this->bread_crumbs_postfix_text2): ?> <?=$this->bread_crumbs_postfix_text2?><?php endif; ?></div>
                    <? include_once($this->getRealTemplatePath('Advert/AdvertsList')) ?>
                </div>
            </div>
            <div class="right_column<? if (!$this->regions && !$this->cities): ?>empty<? endif; ?>">
                <div class="right_column_content">

                    <?php if ($this->regions): ?>
                        <div class="bheader">
                            Объявления по регионам<?php if ($this->bread_crumbs_postfix_text2): ?> <?=$this->bread_crumbs_postfix_text2?><?php endif; ?>:
                        </div>
                        <div class="subblock">
                            <ul class="regions cities">
                                <?php foreach ($this->regions as $data): ?>
                                    <li>
                                        <a<?php if ($data->region->getIsImportantRegion()): ?> class="main"<?php endif; ?> href="<?=$this->territories->getLast()->getUrl()?>/<?=$data->region->getNameEn()?>/categories"><?=$data->region->getNameRu()?></a>
                                        <!--&nbsp;<span>[<?/*=$data->region_count->join_count*/?>]</span></li>-->
                                <? endforeach; ?>
                            </ul>
                        </div>
                    <?php endif; ?>

                    <?php if ($this->cities): ?>
                        <div class="bheader">
                            Объявления по населенным пунктам <?=$this->bread_crumbs_postfix_text2?>:
                        </div>
                        <div class="subblock">
                            <ul class="regions cities">
                                <?php foreach ($this->cities as $data): ?>
                                    <li>
                                        <a href="<?=$this->territories->getLast()->getUrl()?>/<?=$data->city->getNameEn()?>/categories"><?=$data->city->getNameRu()?></a>&nbsp;<span>[<?=$data->city_count->join_count?>]</span></li>
                                <? endforeach; ?>
                            </ul>
                        </div>
                    <?php endif; ?>

                </div>
            </div>
        </div>

    <?php else: ?>
        <p>Объявлений не найдено. Вы можете <a href="/advert/frontend-edit-advert/">подать новое объявление</a> бесплатно и без регистрации.</p>
    <?php endif; ?>

    <?php
    $this->pagination
         ->getHelper()
         ->setCssNormalLinkClass('navigation_normal_link')
         ->setCssActiveLinkClass('navigation_open_link')
         ->setRequestUriParameter('type', $this->type)
         ->setViewLastPageLabel(false);
    include_once $this->getRealTemplatePath('Common/FrontendNavigation');
    ?>

    <?php if ($this->pagination->getCurrentPage() == 1): ?>
        <div class="category_text">
            <p><h2>Сайт объявлений <?=\Krugozor\Framework\Registry::getInstance()->HOSTINFO['HOST']?> &mdash; сайт объявлений нового поколения.</h2></p>
            <p>Мы изучили специфику рынка в <?=$this->territories->getLast()->getNameRu2()?>, пожелания пользователей и сделали максимально удобный для вас ресурс,
                способный эффективно помогать вам в реализации ваших потребностей: на нашем сайте объявлений вы можете
                <strong>продать или сдать в аренду недвижимость в <?=$this->territories->getLast()->getNameRu2()?></strong>,
                купить или <strong>продать в <?=$this->territories->getLast()->getNameRu2()?> автомобиль</strong>,
                <strong>подать объявление о продаже земельного участа в <?=$this->territories->getLast()->getNameRu2()?></strong>,
                продать личные вещи, бытовую технику,
                разместить <strong>объявления о предоставлении своих услуг в <?=$this->territories->getLast()->getNameRu2()?></strong> и многое другое!
            </p>

            <p>Мы заботимся о наших пользователях, поэтому мы не делаем шаблонные решения, как это сделано на других сайтах объявлений:</p>
            <ul>
                <li><p>На нашем сайте <strong>объявления можно подавать без обязательной регистрации</strong>.</p></li>
                <li><p>Мы не берем плату за поднятие объявлений в результатах поиска, как это распространено на других досках объявлений,
                    таких как &laquo;Avito&raquo; или &laquo;Из рук в руки&raquo;. <strong>Поднять объявление в результатах поиска можно раз в час абсолютно бесплатно</strong>!</p></li>
                <li><p>Мы заботимся о наших посетителях, поэтому все поступающие к нам объявления проверяются вручную.</p></li>
                <li><p>Количество объявлений, которое вы можете подать на наш сайт &mdash; неограниченно!</p></li>
            </ul>
        </div>
    <?php endif; ?>

</div>

<? include $this->getRealTemplatePath('Local/FrontendBottom') ?>

</body></html>