<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>

    <?= $this->getHelper('Krugozor_Html_Title')->getHtml() ?>

    <?= $this->getCss('/http/css/reset.css', false) ?>
    <?= $this->getCss('/http/css/tags.css', true) ?>
    <?= $this->getCss('/http/css/backend.css', true) ?>

</head>
<body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>

<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<table class="datatable">
    <tr>
        <td>
            <?php
            $select = $this->getHelper('Krugozor_Helper_Form')->inputSelect('id_country', $this->getRequest()->getRequest('id_country', 'string'), array('onchange' => 'window.location.href = "?id_country=" + this.value'));
            $select->addOption($this->getHelper('Krugozor_Helper_Form')->inputOption(0, $this->lang['content']['select_value']));
            foreach ($this->countryList as $country):
                $select->addOption($this->getHelper('Krugozor_Helper_Form')->inputOption($country->getId(), $country->getNameRu()));
            endforeach;
            echo $select->getHtml();
            ?>
        </td>
    </tr>
</table>

<table class="datatable">
    <? if ($this->regionList->getList()->count()): ?>
        <colgroup>
            <col width="5%"/>
            <col width="5%"/>
            <col width="5%"/>
            <col width="30%"/>
            <col width="25%"/>
            <col width="20%"/>
            <col width="5%"/>
            <col width="5%"/>
        </colgroup>
        <tr>
            <th colspan="10">Список регионов</th>
        </tr>
        <tr class="head_params">
            <td>
                <?php
                $linker = $this->getHelper('Krugozor_Helper_SortLink')
                    ->setFieldName('id')
                    ->setAnchor($this->lang['content']['id'])
                    ->setUrl($this->getRequest()->getUri()->getSimpleUriValue())
                    ->setIconSrc('/http/image/system/icon/')
                    ->setCurrentFieldName($this->regionList->getAlias())
                    ->setCurrentSortOrder($this->regionList->getOrder())
                    ->setQueryStringFromArray(array(
                        'sep' => $this->regionList->getPagination()->getCurrentSeparator(),
                        'page' => $this->regionList->getPagination()->getCurrentPage(),
                        'id_country' => $this->getRequest()->getRequest('id_country', 'string')
                    ));

                echo $linker->getHtml();
                ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('country')
                    ->setAnchor('ID Страны')
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('weight')
                    ->setAnchor('Вес')
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('name_ru')
                    ->setAnchor('Регион RU')
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('name_ru2')
                    ->setAnchor('Регион RU')
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('name_en')
                    ->setAnchor('Регион EN')
                    ->getHtml(); ?>
            </td>
            <td colspan="4"><?= $this->lang['content']['actions'] ?></td>
        </tr>

        <? foreach ($this->regionList->getList() as $region): ?>
            <tr class="color_hover center">
                <td id="region_<?= $region->getId() ?>"><?= $region->getId() ?></td>
                <td>
                    <a href="/user/backend-country-edit/?id=<?= $region->getIdCountry() ?>"><?= $region->getIdCountry() ?></a>
                </td>
                <td><?= $region->getWeight() ?></td>
                <td><?= $this->getHelper('Krugozor_Helper_Format')->run($region->getNameRu(), 'decode', 'hsc') ?></td>
                <td><?= $this->getHelper('Krugozor_Helper_Format')->run($region->getNameRu2(), 'decode', 'hsc') ?></td>
                <td><?= $this->getHelper('Krugozor_Helper_Format')->run($region->getNameEn(), 'decode', 'hsc') ?></td>
                <td class="td_actions"><a
                            href="/user/backend-region-edit/?id=<?= $region->getId() ?>&amp;referer=<?= $this->getRequest()->getRequestUri()->getUrlencodeUriValue(true) ?>"><img
                                src="/http/image/system/icon/edit.png" alt=""/></a></td>
                <td class="td_actions"><img src="/http/image/system/icon/delete_empty.png" alt=""/></td>
            </tr>
        <? endforeach; ?>

    <? else: ?>
        <tr>
            <th><h4>Список регионов</h4></th>
        </tr>
        <tr class="center">
            <td>Список регионов пуст</td>
        </tr>
    <? endif; ?>
</table>

<?php
$pagination = $this->regionList->getPagination();
$pagination
    ->getHelper()
    ->setCssNormalLinkClass('navigation_normal_link')
    ->setRequestUriParameter('field_name', $this->regionList->getAlias())
    ->setRequestUriParameter('sort_order', $this->regionList->getOrder())
    ->setRequestUriParameter('id_country', $this->getRequest()->getRequest('id_country', 'string'));
?>

<? include $this->getRealTemplatePath('Common/BackendNavigation') ?>

<? include $this->getRealTemplatePath('Common/DebugInfo') ?>

</body>
</html>