<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>

    <?= $this->getHelper('Krugozor_Html_Title')->getHtml() ?>

    <?= $this->getCss('/http/css/reset.css', false) ?>
    <?= $this->getCss('/http/css/tags.css', true) ?>
    <?= $this->getCss('/http/css/backend.css', true) ?>

</head>
<body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>
<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<form method="post" action="<?= $this->getRequest()->getRequestUri()->getEscapeUriValue() ?>">
    <table class="datatable edit">
        <colgroup>
            <col/>
            <col/>
        </colgroup>
        <tr>
            <th colspan="2">
                <? if ($this->country->getId()): ?>
                    Редактирование страны &laquo;<?= $this->getHelper('Krugozor_Helper_Format')->hsc($this->country->getNameRu()) ?>&raquo;
                <? else: ?>
                    Добавление страны
                <? endif; ?>
            </th>
        </tr>
        <tr>
            <td><strong class="compulsory">Страна активна:</strong></td>
            <td>
                <?php
                $select = $this->getHelper('Krugozor_Helper_Form')->inputSelect('country[active]', $this->country->getActive());
                $select->addOption($this->getHelper('Krugozor_Helper_Form')->inputOption(1, $this->lang['content']['yes']));
                $select->addOption($this->getHelper('Krugozor_Helper_Form')->inputOption(0, $this->lang['content']['no']));
                echo $select->getHtml();
                ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['active']) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Вес:</strong></td>
            <td>
                <?= $this->getHelper('Krugozor_Helper_Form')->inputText('country[weight]', $this->country->getWeight(), array('maxlength' => 10, 'class' => 'textSmall'))->getHtml() ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['weight']) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Страна по умолчанию:</strong></td>
            <td>
                <?= $this->getHelper('Krugozor_Helper_Form')->inputFullCheckbox('country[is_default_country]', 1, 0, $this->country->getIsDefaultCountry()) ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['is_default_country']) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Имя страны RUS (в именительном падеже):</strong></td>
            <td>
                <?= $this->getHelper('Krugozor_Helper_Form')->inputText('country[name_ru]', $this->country->getNameRu(), array('maxlength' => 50, 'class' => 'textSmall'))->getHtml() ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['name_ru']) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Имя страны RUS (в предложном падеже):</strong></td>
            <td>
                <?= $this->getHelper('Krugozor_Helper_Form')->inputText('country[name_ru2]', $this->country->getNameRu2(), array('maxlength' => 50, 'class' => 'textSmall'))->getHtml() ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['name_ru2']) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Имя страны RUS (в родительном падеже):</strong></td>
            <td>
                <?= $this->getHelper('Krugozor_Helper_Form')->inputText('country[name_ru3]', $this->country->getNameRu3(), array('maxlength' => 50, 'class' => 'textSmall'))->getHtml() ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['name_ru3']) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Имя страны ENG:</strong></td>
            <td>
                <?= $this->getHelper('Krugozor_Helper_Form')->inputText('country[name_en]', $this->country->getNameEn(), array('maxlength' => 50, 'class' => 'textSmall'))->getHtml() ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['name_en']) ?>
            </td>
        </tr>
        <tr align="center">
            <td colspan="2">
                <?= $this->getHelper('Krugozor_Helper_Form')->inputHidden('country[id]', $this->country->getId())->getHtml() ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->inputSubmit('submit', $this->lang['content']['save_changes'])->getHtml() ?>
                &nbsp;&nbsp;&nbsp;
                <?= $this->getHelper('Krugozor_Helper_Form')->inputFullCheckbox('return_on_page', 1, 0, $this->getRequest()->getPost()->return_on_page, array('id' => 'label_return_on_page')) ?>
                &nbsp;<?= $this->getHelper('Krugozor_Helper_Form')->Label($this->lang['content']['return_to_this_page'], 'label_return_on_page')->getHtml() ?>
            </td>
        </tr>
    </table>
</form>

<? include $this->getRealTemplatePath('Common/DebugInfo') ?>

</body>
</html>