<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>

    <?= $this->getHelper('Krugozor_Html_Title')->getHtml() ?>

    <?= $this->getCss('/http/css/reset.css', false) ?>
    <?= $this->getCss('/http/css/tags.css', true) ?>
    <?= $this->getCss('/http/css/backend.css', true) ?>

</head>
<body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>
<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<table class="datatable">
    <? if ($this->countryList->getList()->count()): ?>
        <colgroup>
            <col width="5%"/>
            <col width="5%"/>
            <col width="5%"/>
            <col width="25%"/>
            <col width="25%"/>
            <col width="25%"/>
            <col width="5%"/>
            <col width="5%"/>
        </colgroup>
        <tr>
            <th colspan="8">Список стран</th>
        </tr>
        <tr class="head_params">
            <td>
                <?php
                $linker = $this->getHelper('Krugozor_Helper_SortLink')
                    ->setFieldName('id')
                    ->setAnchor($this->lang['content']['id'])
                    ->setUrl($this->getRequest()->getUri()->getSimpleUriValue())
                    ->setIconSrc('/http/image/system/icon/')
                    ->setCurrentFieldName($this->countryList->getAlias())
                    ->setCurrentSortOrder($this->countryList->getOrder())
                    ->setQueryStringFromArray(array(
                        'sep' => $this->countryList->getPagination()->getCurrentSeparator(),
                        'page' => $this->countryList->getPagination()->getCurrentPage(),
                    ));

                echo $linker->getHtml();
                ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('active')
                    ->setAnchor('Активно')
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('weight')
                    ->setAnchor('Вес')
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('name_ru')
                    ->setAnchor('Страна RU')
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('name_ru2')
                    ->setAnchor('Страна RU')
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('name_en')
                    ->setAnchor('Страна EN')
                    ->getHtml(); ?>
            </td>
            <td colspan="4">
                <?= $this->lang['content']['actions'] ?>
            </td>
        </tr>

        <? foreach ($this->countryList->getList() as $country): ?>
            <tr class="color_hover center">
                <td id="country_<?= $country->getId() ?>"><?= $country->getId() ?></td>
                <td class="center lighttext">
                    <? if ($country->getActive()): ?>
                        <?= $this->lang['content']['yes'] ?>
                    <? else: ?>
                        <span><?= $this->lang['content']['no'] ?></span>
                    <? endif; ?>
                </td>
                <td><?= $country->getWeight() ?></td>
                <td>
                    <a href="/user/backend-region-list/?id_country=<?= $country->getId() ?>"><?= $this->getHelper('Krugozor_Helper_Format')->run($country->getNameRu(), 'decode', 'hsc') ?></a>
                </td>
                <td><?= $this->getHelper('Krugozor_Helper_Format')->run($country->getNameRu2(), 'decode', 'hsc') ?></td>
                <td><?= $this->getHelper('Krugozor_Helper_Format')->run($country->getNameEn(), 'decode', 'hsc') ?></td>
                <td class="td_actions"><a
                            href="/user/backend-country-edit/?id=<?= $country->getId() ?>&amp;referer=<?= $this->getRequest()->getRequestUri()->getUrlencodeUriValue(true) ?>"><img
                                src="/http/image/system/icon/edit.png" alt=""/></a></td>
                <td class="td_actions"><img src="/http/image/system/icon/delete_empty.png" alt=""/></td>
            </tr>
        <? endforeach; ?>
    <? else: ?>
        <tr>
            <th><h4>Список стран</h4></th>
        </tr>
        <tr class="center">
            <td><?= $this->lang['content']['not_found_request_data'] ?></td>
        </tr>
    <? endif; ?>
</table>

<?php
$pagination = $this->countryList->getPagination();
$pagination
    ->getHelper()
    ->setCssNormalLinkClass('navigation_normal_link')
    ->setRequestUriParameter('field_name', $this->countryList->getAlias())
    ->setRequestUriParameter('sort_order', $this->countryList->getOrder());
?>

<? include $this->getRealTemplatePath('Common/BackendNavigation') ?>

<? include $this->getRealTemplatePath('Common/DebugInfo') ?>

</body>
</html>