<!DOCTYPE html>
<html lang="ru">
<head>

    <!-- common meta -->
    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>
    <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getHtml() ?>
    <!-- /common meta -->

    <!-- common css -->
    <?= $this->getCss('common', 'reset.css') ?>
    <?= $this->getCss('common', 'tags.css') ?>
    <?= $this->getCss('common', 'backend.css') ?>
    <!-- /common css -->
    <?= $this->getCss() ?>

</head>
<body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>
<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<table class="datatable">
    <tr>
        <td>
            <?php
            $select = $this->getHelper('\Krugozor\Framework\Helper\Form')->inputSelect('id_region', $this->getRequest()->getRequest('id_region', 'string'), array('onchange' => 'window.location.href = "?id_region=" + this.value'));
            $select->addOption($this->getHelper('\Krugozor\Framework\Helper\Form')->inputOption(0, $this->lang['content']['select_value']));
            foreach ($this->regionList as $region):
                $select->addOption($this->getHelper('\Krugozor\Framework\Helper\Form')->inputOption($region->getId(), $region->getNameRu()));
            endforeach;
            echo $select->getHtml();
            ?>
        </td>
    </tr>
</table>

<table class="datatable">
    <? if ($this->cityList->getList()->count()): ?>
        <colgroup>
            <col><col><col><col><col>
            <col><col><col>
        </colgroup>
        <tr>
            <th colspan="8">Список стран</th>
        </tr>
        <tr class="head_params">
            <td>
                <?php
                $linker = $this->getHelper('\Krugozor\Framework\Helper\SortLink')
                    ->setFieldName('id')
                    ->setAnchor($this->lang['content']['id'])
                    ->setUrl($this->getRequest()->getCanonicalRequestUri()->getSimpleUriValue())
                    ->setIconSrc(\Krugozor\Framework\Registry::getInstance()->APPLICATION['SYSTEM_ICONS'])
                    ->setCurrentFieldName($this->cityList->getAlias())
                    ->setCurrentSortOrder($this->cityList->getOrder())
                    ->setQueryStringFromArray(array(
                        'sep' => $this->cityList->getPagination()->getCurrentSeparator(),
                        'page' => $this->cityList->getPagination()->getCurrentPage(),
                        'id_region' => $this->getRequest()->getRequest('id_region', 'string')
                    ));
                echo $linker->getHtml();
                ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('weight')
                    ->setAnchor('Вес')
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('name_ru')
                    ->setAnchor('Город RU')
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('name_ru2')
                    ->setAnchor('Город RU')
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('name_ru3')
                    ->setAnchor('Город RU')
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('name_en')
                    ->setAnchor('Город EN')
                    ->getHtml(); ?>
            </td>
            <td colspan="4">
                <?= $this->lang['content']['actions'] ?>
            </td>
        </tr>

        <? foreach ($this->cityList->getList() as $city): ?>
            <tr class="color_hover center">
                <td id="city_<?= $city->getId() ?>"><?= $city->getId() ?></td>
                <td><?= $city->getWeight() ?></td>
                <td>
                    <a href="/user/backend-region-list/?id_city=<?= $city->getId() ?>"><?= $this->getHelper('\Krugozor\Framework\Helper\Format')->run($city->getNameRu(), 'decode', 'hsc') ?></a>
                </td>
                <td><?= $this->getHelper('\Krugozor\Framework\Helper\Format')->run($city->getNameRu2(), 'decode', 'hsc') ?></td>
                <td><?= $this->getHelper('\Krugozor\Framework\Helper\Format')->run($city->getNameRu3(), 'decode', 'hsc') ?></td>
                <td><?= $this->getHelper('\Krugozor\Framework\Helper\Format')->run($city->getNameEn(), 'decode', 'hsc') ?></td>
                <td class="td_actions"><a
                            href="/user/backend-city-edit/?id=<?= $city->getId() ?>&amp;referer=<?= $this->getRequest()->getRequestUri()->getUrlencodeUriValue(true) ?>"><img
                                src="<?= \Krugozor\Framework\Registry::getInstance()->APPLICATION['SYSTEM_ICONS'] ?>edit.png" alt=""/></a></td>
                <td class="td_actions"><img src="<?= \Krugozor\Framework\Registry::getInstance()->APPLICATION['SYSTEM_ICONS'] ?>delete_empty.png" alt=""/></td>
            </tr>
        <? endforeach; ?>
    <? else: ?>
        <tr>
            <th><h4>Список стран</h4></th>
        </tr>
        <tr class="center">
            <td><?= $this->lang['content']['not_found_request_data'] ?></td>
        </tr>
    <? endif; ?>
</table>

<?php
$pagination = $this->cityList->getPagination();
$pagination
    ->getHelper()
    ->setCssNormalLinkClass('navigation_normal_link')
    ->setRequestUriParameter('field_name', $this->cityList->getAlias())
    ->setRequestUriParameter('sort_order', $this->cityList->getOrder())
    ->setRequestUriParameter('id_region', $this->getRequest()->getRequest('id_region', 'string'));
?>

<? include $this->getRealTemplatePath('Common/BackendNavigation') ?>
<? include $this->getRealTemplatePath('Common/DebugInfo') ?>

</body>
</html>