<!DOCTYPE html>
<html lang="ru">
<head>

    <!-- common meta -->
    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>
    <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getHtml() ?>
    <!-- /common meta -->

    <!-- common css -->
    <?= $this->getCss('common', 'reset.css') ?>
    <?= $this->getCss('common', 'tags.css') ?>
    <?= $this->getCss('common', 'backend.css') ?>
    <!-- /common css -->
    <?= $this->getCss() ?>

</head>
<body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>
<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<table class="datatable">
    <? if ($this->countryList->getList()->count()): ?>
        <colgroup>
            <col><col><col><col><col>
            <col><col><col>
        </colgroup>
        <tr>
            <th colspan="8">Список стран</th>
        </tr>
        <tr class="head_params">
            <td>
                <?php
                $linker = $this->getHelper('\Krugozor\Framework\Helper\SortLink')
                    ->setFieldName('id')
                    ->setAnchor($this->lang['content']['id'])
                    ->setUrl($this->getRequest()->getCanonicalRequestUri()->getSimpleUriValue())
                    ->setIconSrc(\Krugozor\Framework\Registry::getInstance()->APPLICATION['SYSTEM_ICONS'])
                    ->setCurrentFieldName($this->countryList->getAlias())
                    ->setCurrentSortOrder($this->countryList->getOrder())
                    ->setQueryStringFromArray(array(
                        'sep' => $this->countryList->getPagination()->getCurrentSeparator(),
                        'page' => $this->countryList->getPagination()->getCurrentPage(),
                    ));

                echo $linker->getHtml();
                ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('active')
                    ->setAnchor('Активно')
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('weight')
                    ->setAnchor('Вес')
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('name_ru')
                    ->setAnchor('Страна RU')
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('name_ru2')
                    ->setAnchor('Страна RU')
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('name_en')
                    ->setAnchor('Страна EN')
                    ->getHtml(); ?>
            </td>
            <td colspan="4">
                <?= $this->lang['content']['actions'] ?>
            </td>
        </tr>

        <? foreach ($this->countryList->getList() as $country): ?>
            <tr class="color_hover center">
                <td id="country_<?= $country->getId() ?>"><?= $country->getId() ?></td>
                <td class="center lighttext">
                    <? if ($country->getActive()): ?>
                        <?= $this->lang['content']['yes'] ?>
                    <? else: ?>
                        <span><?= $this->lang['content']['no'] ?></span>
                    <? endif; ?>
                </td>
                <td><?= $country->getWeight() ?></td>
                <td>
                    <a href="/user/backend-region-list/?id_country=<?= $country->getId() ?>"><?= $this->getHelper('\Krugozor\Framework\Helper\Format')->run($country->getNameRu(), 'decode', 'hsc') ?></a>
                </td>
                <td><?= $this->getHelper('\Krugozor\Framework\Helper\Format')->run($country->getNameRu2(), 'decode', 'hsc') ?></td>
                <td><?= $this->getHelper('\Krugozor\Framework\Helper\Format')->run($country->getNameEn(), 'decode', 'hsc') ?></td>
                <td class="td_actions"><a
                            href="/user/backend-country-edit/?id=<?= $country->getId() ?>&amp;referer=<?= $this->getRequest()->getRequestUri()->getUrlencodeUriValue(true) ?>"><img
                                src="<?= \Krugozor\Framework\Registry::getInstance()->APPLICATION['SYSTEM_ICONS'] ?>edit.png" alt=""/></a></td>
                <td class="td_actions"><img src="<?= \Krugozor\Framework\Registry::getInstance()->APPLICATION['SYSTEM_ICONS'] ?>delete_empty.png" alt=""/></td>
            </tr>
        <? endforeach; ?>
    <? else: ?>
        <tr>
            <th><h4>Список стран</h4></th>
        </tr>
        <tr class="center">
            <td><?= $this->lang['content']['not_found_request_data'] ?></td>
        </tr>
    <? endif; ?>
</table>

<?php
$pagination = $this->countryList->getPagination();
$pagination
    ->getHelper()
    ->setCssNormalLinkClass('navigation_normal_link')
    ->setRequestUriParameter('field_name', $this->countryList->getAlias())
    ->setRequestUriParameter('sort_order', $this->countryList->getOrder());
?>

<? include $this->getRealTemplatePath('Common/BackendNavigation') ?>

<? include $this->getRealTemplatePath('Common/DebugInfo') ?>

</body>
</html>