<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>

    <?= $this->getHelper('Krugozor_Html_Title')->getHtml() ?>

    <?= $this->getCss('/http/css/reset.css', false) ?>
    <?= $this->getCss('/http/css/tags.css', true) ?>
    <?= $this->getCss('/http/css/backend.css', true) ?>

</head>
<body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>
<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<form method="post" action="<?= $this->getRequest()->getRequestUri()->getEscapeUriValue() ?>">
    <table class="datatable edit">
        <colgroup>
            <col/>
            <col/>
        </colgroup>
        <tr>
            <th colspan="2">
                <? if ($this->region->getId()): ?>
                    Редактирование региона &laquo;<?= $this->getHelper('Krugozor_Helper_Format')->hsc($this->region->getNameRu()) ?>&raquo;
                <? else: ?>
                    Добавление региона
                <? endif; ?>
            </th>
        </tr>
        <tr>
            <td><strong class="compulsory">Страна:</strong></td>
            <td><?
                $select = $this->getHelper('Krugozor_Helper_Form')->inputSelect('region[id_country]', $this->region->getIdCountry());
                $select->addOption($this->getHelper('Krugozor_Helper_Form')->inputOption(0, $this->lang['content']['select_value']));
                foreach ($this->countryList as $country):
                    $select->addOption($this->getHelper('Krugozor_Helper_Form')->inputOption($country->getId(), $country->getNameRu()));
                endforeach;
                echo $select->getHtml();
                ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['id_country']) ?></td>
        </tr>
        <tr>
            <td><strong class="compulsory">Вес:</strong></td>
            <td>
                <?= $this->getHelper('Krugozor_Helper_Form')->inputText('region[weight]', $this->region->getWeight(), array('maxlength' => 10, 'class' => 'textSmall'))->getHtml() ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['weight']) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Важный регион:</strong></td>
            <td>
                <?= $this->getHelper('Krugozor_Helper_Form')->inputFullCheckbox('region[is_important_region]', 1, 0, $this->region->getIsImportantRegion()) ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['is_important_region']) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Имя региона RUS (в именительном падеже):</strong></td>
            <td>
                <?= $this->getHelper('Krugozor_Helper_Form')->inputText('region[name_ru]', $this->region->getNameRu(), array('maxlength' => 50, 'class' => 'textSmall'))->getHtml() ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['name_ru']) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Имя региона RUS (в предложном падеже):</strong></td>
            <td>
                <?= $this->getHelper('Krugozor_Helper_Form')->inputText('region[name_ru2]', $this->region->getNameRu2(), array('maxlength' => 50, 'class' => 'textSmall'))->getHtml() ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['name_ru2']) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Имя региона ENG:</strong></td>
            <td>
                <?= $this->getHelper('Krugozor_Helper_Form')->inputText('region[name_en]', $this->region->getNameEn(), array('maxlength' => 50, 'class' => 'textSmall'))->getHtml() ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['name_en']) ?>
            </td>
        </tr>
        <tr align="center">
            <td colspan="2">
                <?= $this->getHelper('Krugozor_Helper_Form')->inputHidden('region[id]', $this->region->getId())->getHtml() ?>
                <?= $this->getHelper('Krugozor_Helper_Form')->inputSubmit('submit', $this->lang['content']['save_changes'])->getHtml() ?>
                &nbsp;&nbsp;&nbsp;
                <?= $this->getHelper('Krugozor_Helper_Form')->inputFullCheckbox('return_on_page', 1, 0, $this->getRequest()->getPost()->return_on_page, array('id' => 'label_return_on_page')) ?>
                &nbsp;<?= $this->getHelper('Krugozor_Helper_Form')->Label($this->lang['content']['return_to_this_page'], 'label_return_on_page')->getHtml() ?>
            </td>
        </tr>
    </table>
</form>

<? include $this->getRealTemplatePath('Common/DebugInfo') ?>

</body>
</html>