<!DOCTYPE html>
<html lang="ru">
<head>

    <!-- common meta -->
    <?php /* @var $this \Krugozor\Framework\View */ ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>
    <?= $this->getHelper('\Krugozor\Framework\Html\Title')->getHtml() ?>
    <!-- /common meta -->

    <!-- common css -->
    <?= $this->getCss('common', 'reset.css') ?>
    <?= $this->getCss('common', 'tags.css') ?>
    <?= $this->getCss('common', 'backend.css') ?>
    <!-- /common css -->

</head>
<body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>
<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<form method="post" action="<?= $this->getRequest()->getRequestUri()->getEscapeUriValue() ?>">
    <table class="datatable edit">
        <colgroup>
            <col/>
            <col/>
        </colgroup>
        <tr>
            <th colspan="2">
                <? if ($this->city->getId()): ?>
                    Редактирование города &laquo;<?= $this->getHelper('\Krugozor\Framework\Helper\Format')->hsc($this->city->getNameRu()) ?>&raquo;
                <? else: ?>
                    Добавление города
                <? endif; ?>
            </th>
        </tr>
        <tr>
            <td><strong class="compulsory">Вес:</strong></td>
            <td>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText('city[weight]', $this->city->getWeight(), array('maxlength' => 10, 'class' => 'textSmall'))->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['weight']) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Имя города RUS (в именительном падеже):</strong></td>
            <td>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText('city[name_ru]', $this->city->getNameRu(), array('maxlength' => 50, 'class' => 'textSmall'))->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['name_ru']) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Имя города RUS (в предложном падеже):</strong></td>
            <td>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText('city[name_ru2]', $this->city->getNameRu2(), array('maxlength' => 50, 'class' => 'textSmall'))->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['name_ru2']) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Имя города RUS (в родительном падеже):</strong></td>
            <td>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText('city[name_ru3]', $this->city->getNameRu3(), array('maxlength' => 50, 'class' => 'textSmall'))->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['name_ru3']) ?>
            </td>
        </tr>
        <tr>
            <td><strong class="compulsory">Имя города ENG:</strong></td>
            <td>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputText('city[name_en]', $this->city->getNameEn(), array('maxlength' => 50, 'class' => 'textSmall'))->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->getFieldError($this->err['name_en']) ?>
            </td>
        </tr>
        <tr align="center">
            <td colspan="2">
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputHidden('city[id]', $this->city->getId())->getHtml() ?>
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputSubmit('submit', $this->lang['content']['save_changes'])->getHtml() ?>
                &nbsp;&nbsp;&nbsp;
                <?= $this->getHelper('\Krugozor\Framework\Helper\Form')->inputFullCheckbox('return_on_page', 1, 0, $this->getRequest()->getPost()->return_on_page, array('id' => 'label_return_on_page')) ?>
                &nbsp;<?= $this->getHelper('\Krugozor\Framework\Helper\Form')->Label($this->lang['content']['return_to_this_page'], 'label_return_on_page')->getHtml() ?>
            </td>
        </tr>
    </table>
</form>

<? include $this->getRealTemplatePath('Common/DebugInfo') ?>

</body>
</html>