<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>

    <?= $this->getHelper('Krugozor_Html_Title')->getHtml() ?>

    <?= $this->getCss('/http/css/reset.css', false) ?>
    <?= $this->getCss('/http/css/tags.css', true) ?>
    <?= $this->getCss('/http/css/backend.css', true) ?>

</head>
<body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>
<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<table class="datatable">
    <tr>
        <td>
            <?php
            $select = $this->getHelper('Krugozor_Helper_Form')->inputSelect('id_region', $this->getRequest()->getRequest('id_region', 'string'), array('onchange' => 'window.location.href = "?id_region=" + this.value'));
            $select->addOption($this->getHelper('Krugozor_Helper_Form')->inputOption(0, $this->lang['content']['select_value']));
            foreach ($this->regionList as $region):
                $select->addOption($this->getHelper('Krugozor_Helper_Form')->inputOption($region->getId(), $region->getNameRu()));
            endforeach;
            echo $select->getHtml();
            ?>
        </td>
    </tr>
</table>

<table class="datatable">
    <? if ($this->cityList->getList()->count()): ?>
        <colgroup>
            <col width="5%"/>
            <col width="5%"/>
            <col width="20%"/>
            <col width="20%"/>
            <col width="20%"/>
            <col width="20%"/>
            <col width="5%"/>
            <col width="5%"/>
        </colgroup>
        <tr>
            <th colspan="8">Список стран</th>
        </tr>
        <tr class="head_params">
            <td>
                <?php
                $linker = $this->getHelper('Krugozor_Helper_SortLink')
                    ->setFieldName('id')
                    ->setAnchor($this->lang['content']['id'])
                    ->setUrl($this->getRequest()->getUri()->getSimpleUriValue())
                    ->setIconSrc('/http/image/system/icon/')
                    ->setCurrentFieldName($this->cityList->getAlias())
                    ->setCurrentSortOrder($this->cityList->getOrder())
                    ->setQueryStringFromArray(array(
                        'sep' => $this->cityList->getPagination()->getCurrentSeparator(),
                        'page' => $this->cityList->getPagination()->getCurrentPage(),
                        'id_region' => $this->getRequest()->getRequest('id_region', 'string')
                    ));

                echo $linker->getHtml();
                ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('weight')
                    ->setAnchor('Вес')
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('name_ru')
                    ->setAnchor('Страна RU')
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('name_ru2')
                    ->setAnchor('Страна RU')
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('name_ru3')
                    ->setAnchor('Страна RU')
                    ->getHtml(); ?>
            </td>
            <td>
                <?php
                echo $linker->setFieldName('name_en')
                    ->setAnchor('Страна EN')
                    ->getHtml(); ?>
            </td>
            <td colspan="4">
                <?= $this->lang['content']['actions'] ?>
            </td>
        </tr>

        <? foreach ($this->cityList->getList() as $city): ?>
            <tr class="color_hover center">
                <td id="city_<?= $city->getId() ?>"><?= $city->getId() ?></td>
                <td><?= $city->getWeight() ?></td>
                <td>
                    <a href="/user/backend-region-list/?id_city=<?= $city->getId() ?>"><?= $this->getHelper('Krugozor_Helper_Format')->run($city->getNameRu(), 'decode', 'hsc') ?></a>
                </td>
                <td><?= $this->getHelper('Krugozor_Helper_Format')->run($city->getNameRu2(), 'decode', 'hsc') ?></td>
                <td><?= $this->getHelper('Krugozor_Helper_Format')->run($city->getNameRu3(), 'decode', 'hsc') ?></td>
                <td><?= $this->getHelper('Krugozor_Helper_Format')->run($city->getNameEn(), 'decode', 'hsc') ?></td>
                <td class="td_actions"><a
                            href="/user/backend-city-edit/?id=<?= $city->getId() ?>&amp;referer=<?= $this->getRequest()->getRequestUri()->getUrlencodeUriValue(true) ?>"><img
                                src="/http/image/system/icon/edit.png" alt=""/></a></td>
                <td class="td_actions"><img src="/http/image/system/icon/delete_empty.png" alt=""/></td>
            </tr>
        <? endforeach; ?>
    <? else: ?>
        <tr>
            <th><h4>Список стран</h4></th>
        </tr>
        <tr class="center">
            <td><?= $this->lang['content']['not_found_request_data'] ?></td>
        </tr>
    <? endif; ?>
</table>

<?php
$pagination = $this->cityList->getPagination();
$pagination
    ->getHelper()
    ->setCssNormalLinkClass('navigation_normal_link')
    ->setRequestUriParameter('field_name', $this->cityList->getAlias())
    ->setRequestUriParameter('sort_order', $this->cityList->getOrder())
    ->setRequestUriParameter('id_region', $this->getRequest()->getRequest('id_region', 'string'));
?>

<? include $this->getRealTemplatePath('Common/BackendNavigation') ?>

<? include $this->getRealTemplatePath('Common/DebugInfo') ?>

</body>
</html>