<!DOCTYPE html>
<html lang="ru">
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="<?= $this->lang['meta']['keywords'] ?>"/>
    <meta name="description" content="<?= $this->lang['meta']['description'] ?>"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>

    <?= $this->getHelper('Krugozor_Html_Title')->getHtml() ?>

    <?= $this->getCss('/http/css/main.css', false) ?>
    <?= $this->getPathToCssModule(true) ?>

    <?= $this->getJs('/http/js/tooltip.js', false) ?>
    <?= $this->getJs('/http/js/jquery-1.11.1.min.js', false) ?>
    <?= $this->getJs('/http/js/library/index.js', false) ?>
    <?= $this->getJs('/http/js/library/krugozor.locations.js', true); ?>

</head>
<body>

<? include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div id="<?= $this->getPageId() ?>" class="content">

    <? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

    <h2><?= $this->getHelper('Krugozor_Html_Title')->getByIndex(1) ?></h2>

    <form id="<?= $this->getPageId() ?>" method="post"
          action="<?= $this->getRequest()->getUri()->getEscapeUriValue() ?>">

        <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['system_error']) ?>

        <fieldset>
            <legend>Регистрационная информация</legend>

            <?php if ($this->err['common_error']): ?>
                <div class="field_row_fake">
                    <div></div>
                    <div class="group">
                        <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['common_error']) ?>
                    </div>
                </div>
            <?php endif; ?>

            <div class="field_row_fake">
                <div></div>
                <div class="group">
                    <div class="description_before_fields">Регистрационная информация заполняется только один раз.<br/>В
                        последующем Вы сможете подавать объявления на наш сайт<br/>без повторного указания этой
                        информации.
                    </div>
                </div>
            </div>

            <div class="field_row">
                <label class="compulsory" for="user_login"><span class="red_star">*</span> Ваш будущий логин:</label>
                <div class="group">
                    <?= $this->getHelper('Krugozor_Helper_Form')->inputText('user[login]', $this->user->getLogin(), array('maxlength' => Krugozor_Validator_StringLength::VARCHAR_MAX_LENGTH, 'id' => 'user_login', 'required' => 'required'))->getHtml() ?>
                    <div class="animate_field_description">
                        <div class="animate_field_content">
                            <div class="description_before_fields">
                                Придумайте себе логин. Логин не то же, что и имя, а просто уникальный идентификатор,
                                идентифицирующий Вас как участника. Допускается любая комбинация символов латинского
                                алфавита (a—z), цифр (0—9), знака подчёркивания (_) или знака дефис (-).
                            </div>
                        </div>
                        <div class="triangle-right-border"></div>
                        <div class="triangle-right"></div>
                    </div>
                    <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['login']) ?>
                </div>
            </div>

            <div class="field_row">
                <label class="compulsory" for="user_password_1"><span class="red_star">*</span> Ваш будущий
                    пароль:</label>
                <div class="group">
                    <?= $this->getHelper('Krugozor_Helper_Form')->inputText('user[password_1]', $this->password_1, array('maxlength' => Krugozor_Validator_StringLength::VARCHAR_MAX_LENGTH, 'id' => 'user_password_1', 'autocomplete' => 'off', 'required' => 'required'))->getHtml() ?>
                    <div class="animate_field_description">
                        <div class="animate_field_content">
                            <div class="description_before_fields">
                                Придумайте себе пароль. Допускается любая комбинация символов латинского алфавита (a—z),
                                цифр (0—9), знака подчёркивания (_) или знака дефис (-).
                            </div>
                        </div>
                        <div class="triangle-right-border"></div>
                        <div class="triangle-right"></div>
                    </div>
                    <a href="#" onclick="return Krugozor.Forms.hidePassChars('user_password_1', this)">скрыть пароль</a>
                    <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['password_1']) ?>
                </div>
            </div>

            <div class="field_row">
                <label class="compulsory" for="user_captcha">
                    <span class="red_star">*</span> Введите цифры<br/>с изображения:
                </label>
                <div class="group captcha_block">
                    <?= $this->getHelper('Krugozor_Helper_Form')->inputText('captcha_code', $this->captcha_code, array('onkeyup' => 'Krugozor.Forms.filterDigit(this)', 'maxlength' => 4, 'id' => 'user_captcha', 'required' => 'required'))->getHtml() ?><!--
			 -->
                    <div class="animate_field_description animate_field_captcha">
                        <div class="animate_field_content">
                            <div class="description_before_fields">
                                Если Вы не видите число на картинке, нажмите на картинку мышкой
                            </div>
                        </div>
                        <div class="triangle-right-border"></div>
                        <div class="triangle-right"></div>
                    </div><!--
   			 --><img onclick="this.src=this.src+'&amp;'+Math.round(Math.random())" alt=""
                        title="Если Вы не видите число на картинке, нажмите на картинку мышкой"
                        src="/captcha/main/?session_name=<?= $this->session_name ?>&amp;session_id=<?= $this->session_id ?>"/>
                    <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['captcha']) ?>
                </div>
            </div>

        </fieldset>

        <fieldset>
            <legend>Контактная информация</legend>

            <div class="field_row_fake">
                <div></div>
                <div class="group">
                    <div class="description_before_fields">Поля ниже лучше заполнить сейчас, чтобы в каждом новом
                        создаваемом <br/>Вами объявлении Ваши контактные данные подставлялись автоматически.
                    </div>
                </div>
            </div>

            <div class="field_row">
                <label for="user_first_name">Ваше имя:</label>
                <div class="group">
                    <?= $this->getHelper('Krugozor_Helper_Form')->inputText('user[first_name]', $this->user->getFirstName(), array('maxlength' => 30, 'id' => 'user_first_name'))->getHtml() ?>
                    <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['first_name']) ?>
                </div>
            </div>

            <div class="field_row">
                <label for="user_phone">Телефон:</label>
                <div class="group">
                    <?= $this->getHelper('Krugozor_Helper_Form')->inputText('user[phone]', $this->user->getPhone(), array('maxlength' => Krugozor_Validator_StringLength::VARCHAR_MAX_LENGTH, 'id' => 'user_phone'))->getHtml() ?>
                    <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['phone']) ?>
                </div>
            </div>

            <div class="field_row">
                <label for="user_email">Email-адрес:</label>
                <div class="group">
                    <?= $this->getHelper('Krugozor_Helper_Form')->inputEmail('user[email]', $this->user->getEmail()->getValue(), array('maxlength' => Krugozor_Validator_StringLength::VARCHAR_MAX_LENGTH, 'id' => 'user_email'))->getHtml() ?>
                    <div class="animate_field_description">
                        <div class="animate_field_content">
                            <div class="description_before_fields">
                                <p>Указывайте реальный email-адрес, иначе в случае надобности Вы не сможете восстановить
                                    забытый пароль.</p>
                            </div>
                        </div>
                        <div class="triangle-right-border"></div>
                        <div class="triangle-right"></div>
                    </div>
                    <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['email']) ?>
                </div>
            </div>

            <div class="field_row">
                <label for="user_skype">Skype:</label>
                <div class="group">
                    <?= $this->getHelper('Krugozor_Helper_Form')->inputText('user[skype]', $this->user->getSkype(), array('maxlength' => Krugozor_Validator_StringLength::MD5_MAX_LENGTH, 'id' => 'user_skype'))->getHtml() ?>
                    <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['skype']) ?>
                </div>
            </div>

            <div class="field_row">
                <label for="user_icq">ICQ:</label>
                <div class="group">
                    <?= $this->getHelper('Krugozor_Helper_Form')->inputText('user[icq]', $this->user->getIcq(), array('maxlength' => 10, 'onkeyup' => 'Krugozor.Forms.filterDigit(this)', 'id' => 'user_icq'))->getHtml() ?>
                    <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['icq']) ?>
                </div>
            </div>

            <div class="field_row">
                <label for="user_url">URL:</label>
                <div class="group">
                    <?= $this->getHelper('Krugozor_Helper_Form')->inputUrl('user[url]', $this->user->getUrl()->getValue(), array('maxlength' => Krugozor_Validator_StringLength::VARCHAR_MAX_LENGTH, 'id' => 'user_url', 'autocomplete' => 'on'))->getHtml() ?>
                    <div class="animate_field_description">
                        <div class="animate_field_content">
                            <div class="description_before_fields">
                                <p>Введите адрес начиная с http:// или https://</p>
                            </div>
                        </div>
                        <div class="triangle-right-border"></div>
                        <div class="triangle-right"></div>
                    </div>
                    <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['url']) ?>
                </div>
            </div>

            <div class="field_row">
                <label>Место Вашего проживания:</label>
                <div class="group">
                    <div class="fields_wrap cities">
                        <p>
                            <span class="city_field_description">Страна:</span><span id="js_country_select_wrap"></span>
                            <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['country']) ?>
                        </p>
                        <p>
                            <span class="city_field_description">Регион:</span>
                            <span id="js_region_select_wrap"></span>
                            <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['region']) ?>
                        </p>
                        <p>
                            <span class="city_field_description">Город:</span>
                            <span id="js_city_select_wrap"></span>
                            <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['city']) ?>
                        </p>
                    </div>
                </div>
            </div>

        </fieldset>

        <div class="submit_block">
            <?= $this->getHelper('Krugozor_Helper_Form')->inputHidden($this->session_name, $this->session_id)->getHtml() ?>
            <?= $this->getHelper('Krugozor_Helper_Form')->inputSubmit('submit', 'Вперед, на шаг 2!')->getHtml() ?>
        </div>

    </form>

</div> <!-- / Content -->

<script type="text/javascript">
    Krugozor.Location.addCheckedUserLocation(1, '<?=$this->user->getCountry()?>');
    Krugozor.Location.addCheckedUserLocation(2, '<?=$this->user->getRegion()?>');
    Krugozor.Location.addCheckedUserLocation(3, '<?=$this->user->getCity()?>');

    var select_country_attributes = {
        name: 'user[country]',
        value: '<?=$this->user->getCountry()?>'
    };
    var selectCountryObj = Krugozor.Location.createLocation(select_country_attributes, 'Выберите страну проживания');
    document.getElementById('js_country_select_wrap').appendChild(selectCountryObj.SelectElement);

    var select_region_attributes = {
        name: 'user[region]',
        value: '<?=$this->user->getRegion()?>'
    };
    var selectRegionObj = Krugozor.Location.createLocation(select_region_attributes, 'Выберите регион проживания');
    document.getElementById('js_region_select_wrap').appendChild(selectRegionObj.SelectElement);

    var select_city_attributes = {
        name: 'user[city]',
        value: '<?=$this->user->getCity()?>'
    };
    var selectCityObj = Krugozor.Location.createLocation(select_city_attributes, 'Выберите город проживания');
    document.getElementById('js_city_select_wrap').appendChild(selectCityObj.SelectElement);

    selectCountryObj.create(1, 0);
    selectRegionObj.create(2, <?=(int)$this->user->getCountry()?>);
    selectCityObj.create(3, <?=(int)$this->user->getRegion()?>);
</script>

<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>
</body>
</html>