<!DOCTYPE html>
<html lang="ru">
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="<?= $this->lang['meta']['keywords'] ?>"/>
    <meta name="description" content="<?= $this->lang['meta']['description'] ?>"/>
    <link rel="shortcut icon" sizes="16x16" href="/favicon.ico"/>

    <?= $this->getHelper('Krugozor_Html_Title')->getHtml() ?>

    <?= $this->getCss('/http/css/main.css', false) ?>
    <?= $this->getPathToCssModule(true) ?>

    <?= $this->getJs('/http/js/tooltip.js', false) ?>
    <?= $this->getJs('/http/js/jquery-1.11.1.min.js', false) ?>
    <?= $this->getJs('/http/js/library/index.js', false) ?>
    <?= $this->getJs('/http/js/library/krugozor.locations.js', true); ?>

</head>
<body>

<? include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div id="<?= $this->getPageId() ?>" class="content">

    <h2><a class="space_nowrap" href="/my/">Мой личный кабинет</a> / Моя личная информация</h2>

    <? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

    <form id="<?= $this->getPageId() ?>" method="post"
          action="<?= $this->getRequest()->getUri()->getEscapeUriValue() ?>">

        <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['system_error']) ?>

        <fieldset>
            <legend>Регистрационная информация</legend>

            <div class="field_row">
                <label class="compulsory" for="user_login"><span class="red_star">*</span> Ваш логин:</label>
                <div class="group">
                    <?= $this->getHelper('Krugozor_Helper_Form')->inputText('user[login]', $this->user->getLogin(), array('maxlength' => Krugozor_Validator_StringLength::VARCHAR_MAX_LENGTH, 'id' => 'user_login', 'autocomplete' => 'on', 'required' => 'required'))->getHtml() ?>
                    <div class="animate_field_description">
                        <div class="animate_field_content">
                            <div class="description_before_fields">
                                <p>Придумайте себе логин. Логин не то же, что и имя, а просто уникальный идентификатор,
                                    идентифицирующий Вас как участника. Допускается любая комбинация символов латинского
                                    алфавита (a—z), цифр (0—9), знака подчёркивания (_) или знака дефис (-).</p>
                            </div>
                        </div>
                        <div class="triangle-right-border"></div>
                        <div class="triangle-right"></div>
                    </div>
                    <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['login']) ?>
                </div>
            </div>

            <div class="field_row">
                <label class="compulsory" for="user_password_1"><span class="red_star">*</span> Ваш пароль:</label>
                <div class="group">
                    <?= $this->getHelper('Krugozor_Helper_Form')->inputText('user[password_1]', $this->password_1, array('maxlength' => Krugozor_Validator_StringLength::VARCHAR_MAX_LENGTH, 'id' => 'user_password_1', 'autocomplete' => 'off'))->getHtml() ?>
                    <div class="animate_field_description">
                        <div class="animate_field_content">
                            <div class="description_before_fields">
                                <p>Придумайте себе пароль. Допускается любая комбинация символов латинского алфавита
                                    (a—z), цифр (0—9), знака подчёркивания (_) или знака дефис (-).</p>
                            </div>
                        </div>
                        <div class="triangle-right-border"></div>
                        <div class="triangle-right"></div>
                    </div>
                    <a href="#" onclick="return Krugozor.Forms.hidePassChars('user_password_1', this)">скрыть пароль</a>
                    <div class="description_before_fields">Если не хотите менять пароль, то не заполняйте это поле!
                    </div>
                    <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['password_1']) ?>
                </div>
            </div>

            <?php if (0): ?>
                <div class="field_row">
                    <label class="compulsory" for="user_password_2"><span class="red_star">*</span> Повторите
                        пароль:</label>
                    <div class="group">
                        <?= $this->getHelper('Krugozor_Helper_Form')->inputText('user[password_2]', $this->password_2, array('maxlength' => Krugozor_Validator_StringLength::VARCHAR_MAX_LENGTH, 'id' => 'user_password_2'))->getHtml() ?>
                        <span title="В данное поле введите тот же пароль, что Вы ввели в первое поле."
                              class="help">?</span> <a href="#" onclick="return star2chars('user_password_2', this)">скрыть
                            пароль</a>
                        <div>
                            <small>Если не хотите менять пароль, то не заполняйте это поле!</small>
                        </div>
                        <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['password_2']) ?>
                        <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['password']) ?>
                    </div>
                </div>
            <?php endif; ?>

        </fieldset>

        <fieldset>
            <legend>Контактная информация</legend>

            <div class="field_row_fake">
                <div></div>
                <div class="group">
                    <div class="description_before_fields">Поля ниже лучше заполнить сейчас, чтобы в каждом новом
                        создаваемом<br/>Вами объявлении Ваши контактные данные подставлялись автоматически.
                    </div>
                </div>
            </div>

            <div class="field_row">
                <label for="user_first_name">Ваше имя:</label>
                <div class="group">
                    <?= $this->getHelper('Krugozor_Helper_Form')->inputText('user[first_name]', $this->user->getFirstName(), array('maxlength' => 30, 'id' => 'user_first_name'))->getHtml() ?>
                    <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['first_name']) ?>
                </div>
            </div>

            <div class="field_row">
                <label for="user_phone">Ваш телефон:</label>
                <div class="group">
                    <?= $this->getHelper('Krugozor_Helper_Form')->inputText('user[phone]', $this->user->getPhone(), array('maxlength' => Krugozor_Validator_StringLength::VARCHAR_MAX_LENGTH, 'id' => 'user_phone'))->getHtml() ?>
                    <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['phone']) ?>
                </div>
            </div>

            <div class="field_row">
                <label for="user_email">Ваш email-адрес:</label>
                <div class="group">
                    <?= $this->getHelper('Krugozor_Helper_Form')->inputEmail('user[email]', ($this->user->getEmail() ? $this->user->getEmail()->getValue() : ''), array('maxlength' => Krugozor_Validator_StringLength::VARCHAR_MAX_LENGTH, 'id' => 'user_email'))->getHtml() ?>
                    <div class="animate_field_description">
                        <div class="animate_field_content">
                            <div class="description_before_fields">
                                <p>Указывайте реальный email-адрес, иначе в случае надобности Вы не сможете восстановить
                                    забытый пароль.</p>
                            </div>
                        </div>
                        <div class="triangle-right-border"></div>
                        <div class="triangle-right"></div>
                    </div>
                    <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['email']) ?>
                </div>
            </div>

            <div class="field_row">
                <label for="user_url">Ваш URL-адрес:</label>
                <div class="group">
                    <?= $this->getHelper('Krugozor_Helper_Form')->inputUrl('user[url]', $this->user->getUrl()->getValue(), array('maxlength' => Krugozor_Validator_StringLength::VARCHAR_MAX_LENGTH, 'id' => 'user_url', 'autocomplete' => 'on'))->getHtml() ?>
                    <div class="animate_field_description">
                        <div class="animate_field_content">
                            <div class="description_before_fields">
                                <p>Введите адрес начиная с http:// или https://</p>
                            </div>
                        </div>
                        <div class="triangle-right-border"></div>
                        <div class="triangle-right"></div>
                    </div>
                    <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['url']) ?>
                </div>
            </div>

            <div class="field_row">
                <label for="user_icq">ICQ:</label>
                <div class="group">
                    <?= $this->getHelper('Krugozor_Helper_Form')->inputText('user[icq]', $this->user->getIcq(), array('maxlength' => 11, 'id' => 'user_icq', 'onkeyup' => 'Krugozor.Forms.filterDigit(this)'))->getHtml() ?>
                    <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['icq']) ?>
                </div>
            </div>

            <div class="field_row">
                <label for="user_skype">Skype:</label>
                <div class="group">
                    <?= $this->getHelper('Krugozor_Helper_Form')->inputText('user[skype]', $this->user->getSkype(), array('maxlength' => Krugozor_Validator_StringLength::MD5_MAX_LENGTH, 'id' => 'user_skype'))->getHtml() ?>
                    <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['skype']) ?>
                </div>
            </div>

            <div class="field_row">
                <label>Место Вашего проживания:</label>
                <div class="group">
                    <div class="fields_wrap cities">
                        <p>
                            <span class="city_field_description">Страна:</span><span id="js_country_select_wrap"></span>
                            <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['country']) ?>
                        </p>
                        <p>
                            <span class="city_field_description">Регион:</span>
                            <span id="js_region_select_wrap"></span>
                            <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['region']) ?>
                        </p>
                        <p>
                            <span class="city_field_description">Город:</span>
                            <span id="js_city_select_wrap"></span>
                            <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['city']) ?>
                        </p>
                    </div>
                </div>
            </div>

        </fieldset>

        <fieldset>
            <legend>Если не секрет..</legend>

            <div class="field_row">
                <label>Ваш пол:</label>
                <div class="group">
                    <?php foreach (Krugozor_Module_User_Type_Sex::getTypes() as $sex_key => $sex_value): ?>
                        <?= $this->getHelper('Krugozor_Helper_Form')->inputRadio('user[sex]', $sex_key, $this->user->getSex()->getValue(), array('id' => 'user_sex_' . $sex_key))->getHtml() ?> <?= $this->getHelper('Krugozor_Helper_Form')->Label($sex_value, 'user_sex_' . $sex_key)->getHtml() ?>
                        &nbsp;
                    <?php endforeach; ?>
                    <?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['sex']) ?>
                </div>
            </div>

            <div class="field_row">
                <label>Ваш день рождения:</label>
                <div class="group">
                    <div class="fields_wrap">
                        <?= $this->getHelper('Krugozor_Helper_Form')->inputSelectIntegerValues('user[age_day]', 1, 32, $this->user->getAgeDay())->getHtml() ?>

                        <? $select = $this->getHelper('Krugozor_Helper_Form')->inputSelect('user[age_month]', $this->user->getAgeMonth());
                        $select->addOption($this->getHelper('Krugozor_Helper_Form')->inputOption(0, ''));
                        foreach ($this->lang['content']['date']['months_genitive'] as $key => $value):
                            $select->addOption($this->getHelper('Krugozor_Helper_Form')->inputOption($key, $value));
                        endforeach;
                        ?>
                        <?= $select->getHtml(); ?>

                        <?= $this->getHelper('Krugozor_Helper_Form')->inputSelectYears('user[age_year]', $this->user->getAgeYear())->getHtml() ?><?= $this->getHelper('Krugozor_Helper_Form')->getFieldError($this->err['age_day']) ?>
                    </div>
                </div>
            </div>

        </fieldset>

        <div class="submit_block">
            <?= $this->getHelper('Krugozor_Helper_Form')->inputHidden('user[id]', $this->user->getId())->getHtml() ?>
            <?= $this->getHelper('Krugozor_Helper_Form')->inputSubmit('submit', 'Сохранить мои данные')->getHtml() ?>
        </div>

    </form>

</div> <!-- / Content -->

<script type="text/javascript">
    Krugozor.Location.addCheckedUserLocation(1, '<?=$this->user->getCountry()?>');
    Krugozor.Location.addCheckedUserLocation(2, '<?=$this->user->getRegion()?>');
    Krugozor.Location.addCheckedUserLocation(3, '<?=$this->user->getCity()?>');

    var select_country_attributes = {
        name: 'user[country]',
        value: '<?=$this->user->getCountry()?>'
    };
    var selectCountryObj = Krugozor.Location.createLocation(select_country_attributes, 'Выберите страну проживания');
    document.getElementById('js_country_select_wrap').appendChild(selectCountryObj.SelectElement);

    var select_region_attributes = {
        name: 'user[region]',
        value: '<?=$this->user->getRegion()?>'
    };
    var selectRegionObj = Krugozor.Location.createLocation(select_region_attributes, 'Выберите регион проживания');
    document.getElementById('js_region_select_wrap').appendChild(selectRegionObj.SelectElement);

    var select_city_attributes = {
        name: 'user[city]',
        value: '<?=$this->user->getCity()?>'
    };
    var selectCityObj = Krugozor.Location.createLocation(select_city_attributes, 'Выберите город проживания');
    document.getElementById('js_city_select_wrap').appendChild(selectCityObj.SelectElement);

    selectCountryObj.create(1, 0);
    selectRegionObj.create(2, <?=(int)$this->user->getCountry()?>);
    selectCityObj.create(3, <?=(int)$this->user->getRegion()?>);
</script>

<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>
</body>
</html>